"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass

@dataclass
class ProjectInfo:
    """Dataclass for storing project information."""
    title: str
    author: str
    url: str
    description: str
    repo_url_part: str
    ...


PROJECTS = ...
