"""
This type stub file was generated by pyright.
"""

from textual import events, on
from textual.app import App, ComposeResult
from textual.containers import Vertical
from textual.demo._project_data import ProjectInfo
from textual.demo.page import PageScreen

PROJECTS_MD = ...
class Project(Vertical, can_focus=True, can_focus_children=False):
    """Display project information and open repo links."""
    ALLOW_MAXIMIZE = ...
    DEFAULT_CSS = ...
    BINDINGS = ...
    def __init__(self, project_info: ProjectInfo) -> None:
        ...
    
    def compose(self) -> ComposeResult:
        ...
    
    @on(events.Enter)
    @on(events.Leave)
    def on_enter(self, event: events.Enter): # -> None:
        ...
    
    def action_open_repository(self) -> None:
        ...
    


class ProjectsScreen(PageScreen):
    AUTO_FOCUS = ...
    CSS = ...
    def compose(self) -> ComposeResult:
        ...
    


if __name__ == "__main__":
    class GameApp(App):
        def get_default_screen(self) -> Screen:
            ...
        
    
    
    app = ...
