"""
This type stub file was generated by pyright.
"""

import inspect
import weakref
import rich.repr
from typing import Callable, TYPE_CHECKING
from textual import constants
from textual._context import active_app
from textual._log import LogGroup, LogVerbosity
from textual._on import on
from textual._work_decorator import work
from typing_extensions import TypeAlias
from importlib.metadata import version
from textual.app import App as _App

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
__all__ = ["__version__", "log", "on", "work"]
LogCallable: TypeAlias = "Callable"
if TYPE_CHECKING:
    __version__ = ...
else:
    ...
class LoggerError(Exception):
    """Raised when the logger failed."""
    ...


@rich.repr.auto
class Logger:
    """A [logger class](/guide/devtools/#logging-handler) that logs to the Textual [console](/guide/devtools#console)."""
    def __init__(self, log_callable: LogCallable | None, group: LogGroup = ..., verbosity: LogVerbosity = ..., app: _App | None = ...) -> None:
        ...
    
    @property
    def app(self) -> _App | None:
        """The associated application, or `None` if there isn't one."""
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    
    def __call__(self, *args: object, **kwargs) -> None:
        ...
    
    def verbosity(self, verbose: bool) -> Logger:
        """Get a new logger with selective verbosity.

        Args:
            verbose: True to use HIGH verbosity, otherwise NORMAL.

        Returns:
            New logger.
        """
        ...
    
    @property
    def verbose(self) -> Logger:
        """A verbose logger."""
        ...
    
    @property
    def event(self) -> Logger:
        """Logs events."""
        ...
    
    @property
    def debug(self) -> Logger:
        """Logs debug messages."""
        ...
    
    @property
    def info(self) -> Logger:
        """Logs information."""
        ...
    
    @property
    def warning(self) -> Logger:
        """Logs warnings."""
        ...
    
    @property
    def error(self) -> Logger:
        """Logs errors."""
        ...
    
    @property
    def system(self) -> Logger:
        """Logs system information."""
        ...
    
    @property
    def logging(self) -> Logger:
        """Logs from stdlib logging module."""
        ...
    
    @property
    def worker(self) -> Logger:
        """Logs worker information."""
        ...
    


log = ...
