"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Callable, TYPE_CHECKING, TypeVar
from typing_extensions import Protocol, runtime_checkable
from textual._types import AnimationLevel, CallbackType
from textual.app import App

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    AnimationKey = tuple[int, str]
EasingFunction = Callable[[float], float]
class AnimationError(Exception):
    """An issue prevented animation from starting."""
    ...


ReturnType = TypeVar("ReturnType")
@runtime_checkable
class Animatable(Protocol):
    """Protocol for objects that can have their intrinsic values animated.

    For example, the transition between two colors can be animated
    because the class [`Color`][textual.color.Color.blend] satisfies this protocol.
    """
    def blend(self: ReturnType, destination: ReturnType, factor: float) -> ReturnType:
        ...
    


class Animation(ABC):
    on_complete: CallbackType | None = ...
    @abstractmethod
    def __call__(self, time: float, app_animation_level: AnimationLevel = ...) -> bool:
        """Call the animation, return a boolean indicating whether animation is in-progress or complete.

        Args:
            time: The current timestamp

        Returns:
            True if the animation has finished, otherwise False.
        """
        ...
    
    async def invoke_callback(self) -> None:
        """Calls the [`on_complete`][Animation.on_complete] callback if one is provided."""
        ...
    
    @abstractmethod
    async def stop(self, complete: bool = ...) -> None:
        """Stop the animation.

        Args:
            complete: Flag to say if the animation should be taken to completion.
        """
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    


@dataclass
class SimpleAnimation(Animation):
    obj: object
    attribute: str
    start_time: float
    duration: float
    start_value: float | Animatable
    end_value: float | Animatable
    final_value: object
    easing: EasingFunction
    on_complete: CallbackType | None = ...
    level: AnimationLevel = ...
    def __call__(self, time: float, app_animation_level: AnimationLevel = ...) -> bool:
        ...
    
    async def stop(self, complete: bool = ...) -> None:
        """Stop the animation.

        Args:
            complete: Flag to say if the animation should be taken to completion.

        Note:
            [`on_complete`][Animation.on_complete] will be called regardless
            of the value provided for `complete`.
        """
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    


class BoundAnimator:
    def __init__(self, animator: Animator, obj: object) -> None:
        ...
    
    def __call__(self, attribute: str, value: str | float | Animatable, *, final_value: object = ..., duration: float | None = ..., speed: float | None = ..., delay: float = ..., easing: EasingFunction | str = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ...) -> None:
        """Animate an attribute.

        Args:
            attribute: Name of the attribute to animate.
            value: The value to animate to.
            final_value: The final value of the animation. Defaults to `value` if not set.
            duration: The duration (in seconds) of the animation.
            speed: The speed of the animation.
            delay: A delay (in seconds) before the animation starts.
            easing: An easing method.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
        """
        ...
    


class Animator:
    """An object to manage updates to a given attribute over a period of time."""
    def __init__(self, app: App, frames_per_second: int = ...) -> None:
        """Initialise the animator object.

        Args:
            app: The application that owns the animator.
            frames_per_second: The number of frames/second to run the animation at.
        """
        ...
    
    async def start(self) -> None:
        """Start the animator task."""
        ...
    
    async def stop(self) -> None:
        """Stop the animator task."""
        ...
    
    def bind(self, obj: object) -> BoundAnimator:
        """Bind the animator to a given object.

        Args:
            obj: The object to bind to.

        Returns:
            The bound animator.
        """
        ...
    
    def is_being_animated(self, obj: object, attribute: str) -> bool:
        """Does the object/attribute pair have an ongoing or scheduled animation?

        Args:
            obj: An object to check for.
            attribute: The attribute on the object to test for.

        Returns:
            `True` if that attribute is being animated for that object, `False` if not.
        """
        ...
    
    def animate(self, obj: object, attribute: str, value: Any, *, final_value: object = ..., duration: float | None = ..., speed: float | None = ..., easing: EasingFunction | str = ..., delay: float = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ...) -> None:
        """Animate an attribute to a new value.

        Args:
            obj: The object containing the attribute.
            attribute: The name of the attribute.
            value: The destination value of the attribute.
            final_value: The final value, or ellipsis if it is the same as ``value``.
            duration: The duration of the animation, or ``None`` to use speed.
            speed: The speed of the animation.
            easing: An easing function.
            delay: Number of seconds to delay the start of the animation by.
            on_complete: Callback to run after the animation completes.
            level: Minimum level required for the animation to take place (inclusive).
        """
        ...
    
    async def stop_animation(self, obj: object, attribute: str, complete: bool = ...) -> None:
        """Stop an animation on an attribute.

        Args:
            obj: The object containing the attribute.
            attribute: The name of the attribute.
            complete: Should the animation be set to its final value?

        Note:
            If there is no animation scheduled or running, this is a no-op.
        """
        ...
    
    def force_stop_animation(self, obj: object, attribute: str) -> None:
        """Force stop an animation on an attribute. This will immediately stop the animation,
        without running any associated callbacks, setting the attribute to its final value.

        Args:
            obj: The object containing the attribute.
            attribute: The name of the attribute.

        Note:
            If there is no animation scheduled or running, this is a no-op.
        """
        ...
    
    def __call__(self) -> None:
        ...
    
    async def wait_for_idle(self) -> None:
        """Wait for any animations to complete."""
        ...
    
    async def wait_until_complete(self) -> None:
        """Wait for any current and scheduled animations to complete."""
        ...
    


