"""
This type stub file was generated by pyright.
"""

from typing import Mapping, Tuple
from typing_extensions import Final
from textual.keys import Keys

"""
This type stub file was generated by pyright.
"""
class IgnoredSequence:
    """Class used to mark that a sequence should be ignored."""
    ...


IGNORE_SEQUENCE: Final[IgnoredSequence] = ...
ANSI_SEQUENCES_KEYS: Mapping[str, Tuple[Keys, ...] | str | IgnoredSequence] = ...
SYNC_START = ...
SYNC_END = ...
def set_pointer_shape(shape: str) -> str:
    """Generate escape sequence to set pointer (cursor) shape using Kitty protocol.

    Args:
        shape: The pointer shape name (e.g., "default", "pointer", "text", "crosshair", etc.)

    Returns:
        The escape sequence to set the pointer shape.

    See: https://sw.kovidgoyal.net/kitty/pointer-shapes/
    """
    ...

