"""
This type stub file was generated by pyright.
"""

from typing import Sequence, TYPE_CHECKING
from textual.geometry import Size
from textual.layout import DockArrangeResult
from textual.widget import Widget

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
TOP_Z = ...
_get_dock = ...
_get_split = ...
_get_display = ...
def arrange(widget: Widget, children: Sequence[Widget], size: Size, viewport: Size, optimal: bool = ...) -> DockArrangeResult:
    """Arrange widgets by applying docks and calling layouts

    Args:
        widget: The parent (container) widget.
        size: The size of the available area.
        viewport: The size of the viewport (terminal).

    Returns:
        Widget arrangement information.
    """
    ...

