"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class DecodeError(Exception):
    """A problem decoding data."""
    ...


def dump(data: object) -> bytes:
    """Encodes a data structure into bytes.

    Args:
        data: Data structure

    Returns:
        A byte string encoding the data.
    """
    ...

def load(encoded: bytes) -> object:
    """Load an encoded data structure from bytes.

    Args:
        encoded: Encoded data in bytes.

    Raises:
        DecodeError: If an error was encountered decoding the string.

    Returns:
        Decoded data.
    """
    ...

