"""
This type stub file was generated by pyright.
"""

from functools import lru_cache
from typing_extensions import TypeAlias

"""
This type stub file was generated by pyright.
"""
Quad: TypeAlias = "tuple[int, int, int, int]"
BOX_CHARACTERS: dict[Quad, str] = ...
@lru_cache(1024)
def combine_quads(box1: Quad, box2: Quad) -> Quad:
    """Combine two box drawing quads.

    Args:
        box1: Existing box quad.
        box2: New box quad.

    Returns:
        A new box quad.
    """
    ...

