"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
ANSI_COLORS = ...
COLOR_NAME_TO_RGB: dict[str, tuple[int, int, int] | tuple[int, int, int, int]] = ...
