"""
This type stub file was generated by pyright.
"""

from contextvars import ContextVar
from typing import Any, Callable, TYPE_CHECKING
from textual.app import App
from textual.message import Message
from textual.message_pump import MessagePump
from textual.screen import Screen

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
class NoActiveAppError(RuntimeError):
    """Runtime error raised if we try to retrieve the active app when there is none."""
    ...


active_app: ContextVar[App[Any]] = ...
active_message_pump: ContextVar[MessagePump] = ...
prevent_message_types_stack: ContextVar[list[set[type[Message]]]] = ...
visible_screen_stack: ContextVar[list[Screen[object]]] = ...
message_hook: ContextVar[Callable[[Message], None]] = ...
