"""
This type stub file was generated by pyright.
"""

from typing import Generic, Iterator, Sequence, TYPE_CHECKING, TypeVar, overload

"""
This type stub file was generated by pyright.
"""
T = TypeVar("T")
class ImmutableSequenceView(Generic[T]):
    """Class to wrap a sequence of some sort, but not allow modification."""
    def __init__(self, wrap: Sequence[T]) -> None:
        """Initialise the immutable sequence.

        Args:
            wrap: The sequence being wrapped.
        """
        ...
    
    if TYPE_CHECKING:
        @overload
        def __getitem__(self, index: int) -> T:
            ...
        
        @overload
        def __getitem__(self, index: slice) -> ImmutableSequenceView[T]:
            ...
        
    def __getitem__(self, index: int | slice) -> T | ImmutableSequenceView[T]:
        ...
    
    def __iter__(self) -> Iterator[T]:
        ...
    
    def __len__(self) -> int:
        ...
    
    def __length_hint__(self) -> int:
        ...
    
    def __bool__(self) -> bool:
        ...
    
    def __contains__(self, item: T) -> bool:
        ...
    
    def index(self, item: T, start: int = ..., stop: int = ...) -> int:
        """Return the index of the given item.

        Args:
            item: The item to find in the sequence.
            start: Optional start location.
            stop: Optional stop location.

        Returns:
            The index of the item in the sequence.

        Raises:
            ValueError: If the item is not in the sequence.
        """
        ...
    
    def __reversed__(self) -> Iterator[T]:
        ...
    


