"""
This type stub file was generated by pyright.
"""

from typing import Sequence
from typing_extensions import Protocol

"""
This type stub file was generated by pyright.
"""
class EdgeProtocol(Protocol):
    """Any object that defines an edge (such as Layout)."""
    size: int | None
    fraction: int
    min_size: int
    ...


def layout_resolve(total: int, edges: Sequence[EdgeProtocol]) -> list[int]:
    """Divide total space to satisfy size, fraction, and min_size, constraints.

    The returned list of integers should add up to total in most cases, unless it is
    impossible to satisfy all the constraints. For instance, if there are two edges
    with a minimum size of 20 each and `total` is 30 then the returned list will be
    greater than total. In practice, this would mean that a Layout object would
    clip the rows that would overflow the screen height.

    Args:
        total: Total number of characters.
        edges: Edges within total space.

    Returns:
        Number of characters for each edge.
    """
    ...

