"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
LINE_AND_ENDING_PATTERN = ...
def line_split(input_string: str) -> list[tuple[str, str]]:
    r"""
    Splits an arbitrary string into a list of tuples, where each tuple contains a line of text and its line ending.

    Args:
        input_string (str): The string to split.

    Returns:
        list[tuple[str, str]]: A list of tuples, where each tuple contains a line of text and its line ending.

    Example:
        split_string_to_lines_and_endings("Hello\r\nWorld\nThis is a test\rLast line")
        >>> [('Hello', '\r\n'), ('World', '\n'), ('This is a test', '\r'), ('Last line', '')]
    """
    ...

