"""
This type stub file was generated by pyright.
"""

from typing import Callable, Generator, Generic, Iterable, NamedTuple, TypeVar

"""
This type stub file was generated by pyright.
"""
class ParseError(Exception):
    """Base class for parse related errors."""
    ...


class ParseEOF(ParseError):
    """End of Stream."""
    ...


class ParseTimeout(ParseError):
    """Read has timed out."""
    ...


class Read1(NamedTuple):
    """Reads a single character."""
    timeout: float | None = ...


class Peek1(NamedTuple):
    """Reads a single character, but does not advance the parser position."""
    timeout: float | None = ...


T = TypeVar("T")
TokenCallback = Callable[[T], None]
class Parser(Generic[T]):
    """Base class for a simple parser."""
    read1 = Read1
    peek1 = Peek1
    def __init__(self) -> None:
        ...
    
    @property
    def is_eof(self) -> bool:
        """Is the parser at the end of the file (i.e. exhausted)?"""
        ...
    
    def tick(self) -> Iterable[T]:
        """Call at regular intervals to check for timeouts."""
        ...
    
    def feed(self, data: str) -> Iterable[T]:
        """Feed data to be parsed.

        Args:
            data: Data to parser.

        Raises:
            ParseError: If the data could not be parsed.

        Yields:
            T: A generic data type.
        """
        ...
    
    def parse(self, token_callback: TokenCallback) -> Generator[Read1 | Peek1, str, None]:
        """Implement to parse a stream of text.

        Args:
            token_callback: Callable to report a successful parsed data type.

        Yields:
            ParseAwaitable: One of `self.read1` or `self.peek1`
        """
        ...
    


