"""
This type stub file was generated by pyright.
"""

from pathlib import PurePath
from typing import List, Union
from typing_extensions import TypeAlias

"""
This type stub file was generated by pyright.
"""
CSSPathType: TypeAlias = Union[str, PurePath, List[Union[str, PurePath]],]
class CSSPathError(Exception):
    """Raised when supplied CSS path(s) are invalid."""
    ...


