"""
This type stub file was generated by pyright.
"""

from typing import Generic, TypeVar

"""
This type stub file was generated by pyright.
"""
QueueType = TypeVar("QueueType")
class Queue(Generic[QueueType]):
    """A cut-down version of asyncio.Queue

    This has just enough functionality to run the message pumps.

    """
    def __init__(self) -> None:
        ...
    
    def put_nowait(self, value: QueueType) -> None:
        ...
    
    def qsize(self) -> int:
        ...
    
    def empty(self) -> bool:
        ...
    
    def task_done(self) -> None:
        ...
    
    async def get(self) -> QueueType:
        ...
    
    def get_nowait(self) -> QueueType:
        ...
    


