"""
This type stub file was generated by pyright.
"""

from typing import Pattern
from typing_extensions import Final

"""
This type stub file was generated by pyright.
"""
WHITESPACE_REPLACEMENT: Final[str] = ...
REMOVABLE: Final[str] = ...
NONLINGUAL: Final[str] = ...
STRIP_RE: Final[Pattern] = ...
WHITESPACE_RE: Final[Pattern] = ...
def slug(text: str) -> str:
    """Create a Markdown-friendly slug from the given text.

    Args:
        text: The text to generate a slug from.

    Returns:
        A slug for the given text.

    The rules used in generating the slug are based on observations of how
    GitHub-flavoured Markdown works.
    """
    ...

class TrackedSlugs:
    """Provides a class for generating tracked slugs.

    While [`slug`][textual._slug.slug] will generate a slug for a given
    string, it does not guarantee that it is unique for a given context. If
    you want to ensure that the same string generates unique slugs (perhaps
    heading slugs within a Markdown document, as an example), use an
    instance of this class to generate them.

    Example:
        ```python
        >>> slug("hello world")
        'hello-world'
        >>> slug("hello world")
        'hello-world'
        >>> unique = TrackedSlugs()
        >>> unique.slug("hello world")
        'hello-world'
        >>> unique.slug("hello world")
        'hello-world-1'
        ```
    """
    def __init__(self) -> None:
        """Initialise the tracked slug object."""
        ...
    
    def slug(self, text: str) -> str:
        """Create a Markdown-friendly unique slug from the given text.

        Args:
            text: The text to generate a slug from.

        Returns:
            A slug for the given text.
        """
        ...
    


VALID_ID_CHARACTERS = ...
def slug_for_tcss_id(text: str) -> str:
    """Produce a slug usable as a TCSS id from the given text.

    Args:
        text: Text.

    Returns:
        A slugified version of text suitable for use as a TCSS id.
    """
    ...

