"""
This type stub file was generated by pyright.
"""

import rich.repr
from functools import lru_cache
from typing import Callable, Sequence, TYPE_CHECKING
from rich.terminal_theme import TerminalTheme
from textual.color import Color
from textual.content import Content
from textual.filter import LineFilter
from textual.geometry import Region, Size, Spacing
from textual.strip import Strip
from textual.style import Style
from typing_extensions import TypeAlias
from textual.css.styles import StylesBase
from textual.widget import Widget

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
RenderLineCallback: TypeAlias = Callable[[int], Strip]
@rich.repr.auto(angular=True)
class StylesCache:
    """Responsible for rendering CSS Styles and keeping a cache of rendered lines.

    The render method applies border, outline, and padding set in the Styles object to widget content.

    The diagram below shows content (possibly from a Rich renderable) with padding and border. The
    labels A. B. and C. indicate the code path (see comments in render_line below) chosen to render
    the indicated lines.

    ```
    ┏━━━━━━━━━━━━━━━━━━━━━━┓◀── A. border
    ┃                      ┃◀┐
    ┃                      ┃ └─ B. border + padding +
    ┃   Lorem ipsum dolor  ┃◀┐         border
    ┃   sit amet,          ┃ │
    ┃   consectetur        ┃ └─ C. border + padding +
    ┃   adipiscing elit,   ┃     content + padding +
    ┃   sed do eiusmod     ┃           border
    ┃   tempor incididunt  ┃
    ┃                      ┃
    ┃                      ┃
    ┗━━━━━━━━━━━━━━━━━━━━━━┛
    ```
    """
    def __init__(self) -> None:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    
    def set_dirty(self, *regions: Region) -> None:
        """Add a dirty regions."""
        ...
    
    def is_dirty(self, y: int) -> bool:
        """Check if a given line is dirty (needs to be rendered again).

        Args:
            y: Y coordinate of line.

        Returns:
            True if line requires a render, False if can be cached.
        """
        ...
    
    def clear(self) -> None:
        """Clear the styles cache (will cause the content to re-render)."""
        ...
    
    def render_widget(self, widget: Widget, crop: Region) -> list[Strip]:
        """Render the content for a widget.

        Args:
            widget: A widget.
            region: A region of the widget to render.

        Returns:
            Rendered lines.
        """
        ...
    
    def render(self, styles: StylesBase, size: Size, base_background: Color, background: Color, render_content_line: RenderLineCallback, filters: Sequence[LineFilter], border_title: tuple[Content, Color, Color, Style] | None, border_subtitle: tuple[Content, Color, Color, Style] | None, content_size: Size | None = ..., padding: Spacing | None = ..., crop: Region | None = ..., opacity: float = ..., ansi_theme: TerminalTheme = ...) -> list[Strip]:
        """Render a widget content plus CSS styles.

        Args:
            styles: CSS Styles object.
            size: Size of widget.
            base_background: Background color beneath widget.
            background: Background color of widget.
            render_content_line: Callback to render content line.
            console: The console in use by the app.
            border_title: Optional tuple of (title, color, background, style).
            border_subtitle: Optional tuple of (subtitle, color, background, style).
            content_size: Size of content or None to assume full size.
            padding: Override padding from Styles, or None to use styles.padding.
            crop: Region to crop to.
            filters: Additional post-processing for the segments.
            opacity: Widget opacity.
            ansi_theme: Theme for ANSI colors.

        Returns:
            Rendered lines.
        """
        ...
    
    @lru_cache(1024)
    def get_inner_outer(cls, base_background: Color, background: Color) -> tuple[Style, Style]:
        """Get inner and outer background colors."""
        ...
    
    def render_line(self, styles: StylesBase, y: int, size: Size, content_size: Size, padding: Spacing, base_background: Color, background: Color, render_content_line: Callable[[int], Strip], border_title: tuple[Content, Color, Color, Style] | None, border_subtitle: tuple[Content, Color, Color, Style] | None, opacity: float, ansi_theme: TerminalTheme) -> Strip:
        """Render a styled line.

        Args:
            styles: Styles object.
            y: The y coordinate of the line (relative to widget screen offset).
            size: Size of the widget.
            content_size: Size of the content area.
            padding: Padding.
            base_background: Background color of widget beneath this line.
            background: Background color of widget.
            render_content_line: Callback to render a line of content.
            console: The console in use by the app.
            border_title: Optional tuple of (title, color, background, style).
            border_subtitle: Optional tuple of (subtitle, color, background, style).
            opacity: Opacity of line.

        Returns:
            A line of segments.
        """
        ...
    


