"""
This type stub file was generated by pyright.
"""

from functools import lru_cache
from typing_extensions import TypeAlias

"""
This type stub file was generated by pyright.
"""
ActionParseResult: TypeAlias = "tuple[str, str, tuple[object, ...]]"
class SkipAction(Exception):
    """Raise in an action to skip the action (and allow any parent bindings to run)."""
    ...


class ActionError(Exception):
    ...


re_action_args = ...
@lru_cache(maxsize=1024)
def parse(action: str) -> ActionParseResult:
    """Parses an action string.

    Args:
        action: String containing action.

    Raises:
        ActionError: If the action has invalid syntax.

    Returns:
        Action name and arguments.
    """
    ...

