"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import NamedTuple, Sequence
from rich.style import Style
from typing_extensions import Literal, TypeAlias
from textual.color import Color
from textual.geometry import Offset
from textual.strip import StripRenderable

"""
This type stub file was generated by pyright.
"""
CanvasLineType: TypeAlias = Literal["thin", "heavy", "double"]
_LINE_TYPE_INDEX = ...
class _Span(NamedTuple):
    """Associates a sequence of character indices with a color."""
    start: int
    end: int
    color: Color
    ...


class Primitive:
    """Base class for a canvas primitive."""
    def render(self, canvas: Canvas) -> None:
        """Render to the canvas.

        Args:
            canvas: Canvas instance.
        """
        ...
    


@dataclass
class HorizontalLine(Primitive):
    """A horizontal line."""
    origin: Offset
    length: int
    color: Color
    line_type: CanvasLineType = ...
    def render(self, canvas: Canvas) -> None:
        ...
    


@dataclass
class VerticalLine(Primitive):
    """A vertical line."""
    origin: Offset
    length: int
    color: Color
    line_type: CanvasLineType = ...
    def render(self, canvas: Canvas) -> None:
        ...
    


@dataclass
class Rectangle(Primitive):
    """A rectangle."""
    origin: Offset
    width: int
    height: int
    color: Color
    line_type: CanvasLineType = ...
    def render(self, canvas: Canvas) -> None:
        ...
    


class Canvas:
    """A character canvas."""
    def __init__(self, width: int, height: int) -> None:
        """

        Args:
            width: Width of the canvas (in cells).
            height Height of the canvas (in cells).
        """
        ...
    
    @property
    def width(self) -> int:
        """The canvas width."""
        ...
    
    @property
    def height(self) -> int:
        """The canvas height."""
        ...
    
    def x_range(self, start: int, end: int) -> range:
        """Range of x values, clipped to the canvas dimensions.

        Args:
            start: Start index.
            end: End index.

        Returns:
            A range object.
        """
        ...
    
    def y_range(self, start: int, end: int) -> range:
        """Range of y values, clipped to the canvas dimensions.

        Args:
            start: Start index.
            end: End index.

        Returns:
            A range object.
        """
        ...
    
    def render(self, primitives: Sequence[Primitive], base_style: Style) -> StripRenderable:
        """Render the canvas.

        Args:
            primitives: A sequence of primitives.
            base_style: The base style of the canvas.

        Returns:
            A Rich renderable for the canvas.
        """
        ...
    


