"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from textual.app import App, ComposeResult
from textual.widget import Widget

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
__all__ = ["compose"]
def compose(node: App | Widget, compose_result: ComposeResult | None = ...) -> list[Widget]:
    """Compose child widgets from a generator in the same way as [compose][textual.widget.Widget.compose].

    Example:
        ```python
            def on_key(self, event:events.Key) -> None:

                def add_key(key:str) -> ComposeResult:
                    with containers.HorizontalGroup():
                        yield Label("You pressed:")
                        yield Label(key)

                self.mount_all(
                    compose(self, add_key(event.key)),
                )
        ```

    Args:
        node: The parent node.
        compose_result: A compose result, or `None` to call `node.compose()`.

    Returns:
        A list of widgets.
    """
    ...

