"""
This type stub file was generated by pyright.
"""

from typing import ClassVar
from textual.binding import BindingType
from textual.layout import Layout
from textual.reactive import reactive
from textual.widget import Widget

"""
This type stub file was generated by pyright.
"""
class Container(Widget):
    """Simple container widget, with vertical layout."""
    DEFAULT_CSS = ...


class ScrollableContainer(Widget, can_focus=True):
    """A scrollable container with vertical layout, and auto scrollbars on both axis."""
    ALLOW_MAXIMIZE = ...
    DEFAULT_CSS = ...
    BINDINGS: ClassVar[list[BindingType]] = ...
    def __init__(self, *children: Widget, name: str | None = ..., id: str | None = ..., classes: str | None = ..., disabled: bool = ..., can_focus: bool | None = ..., can_focus_children: bool | None = ..., can_maximize: bool | None = ...) -> None:
        """
        Construct a scrollable container.

        Args:
            *children: Child widgets.
            name: The name of the widget.
            id: The ID of the widget in the DOM.
            classes: The CSS classes for the widget.
            disabled: Whether the widget is disabled or not.
            can_focus: Can this container be focused?
            can_focus_children: Can this container's children be focused?
            can_maximized: Allow this container to maximize? `None` to use default logic.,
        """
        ...
    
    @property
    def allow_maximize(self) -> bool:
        ...
    


class Vertical(Widget):
    """An expanding container with vertical layout and no scrollbars."""
    DEFAULT_CSS = ...


class VerticalGroup(Widget):
    """A non-expanding container with vertical layout and no scrollbars."""
    DEFAULT_CSS = ...


class VerticalScroll(ScrollableContainer):
    """A container with vertical layout and an automatic scrollbar on the Y axis."""
    DEFAULT_CSS = ...


class Horizontal(Widget):
    """An expanding container with horizontal layout and no scrollbars."""
    DEFAULT_CSS = ...


class HorizontalGroup(Widget):
    """A non-expanding container with horizontal layout and no scrollbars."""
    DEFAULT_CSS = ...


class HorizontalScroll(ScrollableContainer):
    """A container with horizontal layout and an automatic scrollbar on the X axis."""
    DEFAULT_CSS = ...


class Center(Widget):
    """A container which aligns children on the X axis."""
    DEFAULT_CSS = ...


class Right(Widget):
    """A container which aligns children on the X axis."""
    DEFAULT_CSS = ...


class Middle(Widget):
    """A container which aligns children on the Y axis."""
    DEFAULT_CSS = ...


class CenterMiddle(Widget):
    """A container which aligns its children on both axis."""
    DEFAULT_CSS = ...


class Grid(Widget):
    """A container with grid layout."""
    DEFAULT_CSS = ...


class ItemGrid(Widget):
    """A container with grid layout and automatic columns."""
    DEFAULT_CSS = ...
    stretch_height: reactive[bool] = ...
    min_column_width: reactive[int | None] = ...
    max_column_width: reactive[int | None] = ...
    regular: reactive[bool] = ...
    def __init__(self, *children: Widget, name: str | None = ..., id: str | None = ..., classes: str | None = ..., disabled: bool = ..., min_column_width: int | None = ..., max_column_width: int | None = ..., stretch_height: bool = ..., regular: bool = ...) -> None:
        """
        Construct a ItemGrid.

        Args:
            *children: Child widgets.
            name: The name of the widget.
            id: The ID of the widget in the DOM.
            classes: The CSS classes for the widget.
            disabled: Whether the widget is disabled or not.
            stretch_height: Expand the height of widgets to the row height.
            min_column_width: The smallest permitted column width.
            regular: All rows should have the same number of items.
        """
        ...
    
    def pre_layout(self, layout: Layout) -> None:
        ...
    


