"""
This type stub file was generated by pyright.
"""

import rich.repr
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Type, TypeVar
from rich.style import Style
from typing_extensions import Self
from textual._types import CallbackType
from textual.geometry import Offset, Size
from textual.message import Message
from textual.dom import DOMNode
from textual.timer import Timer as TimerClass, TimerCallback
from textual.widget import Widget

"""
This type stub file was generated by pyright.
"""
MouseEventT = TypeVar("MouseEventT", bound="MouseEvent")
if TYPE_CHECKING:
    ...
@rich.repr.auto
class Event(Message):
    """The base class for all events."""
    ...


@rich.repr.auto
class Callback(Event, bubble=False, verbose=True):
    """Sent by Textual to invoke a callback
    (see [call_next][textual.message_pump.MessagePump.call_next] and
    [call_later][textual.message_pump.MessagePump.call_later]).
    """
    def __init__(self, callback: CallbackType) -> None:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    


@dataclass
class CursorPosition(Event, bubble=False):
    """Internal event used to retrieve the terminal's cursor position."""
    x: int
    y: int
    ...


class Load(Event, bubble=False):
    """
    Sent when the App is running but *before* the terminal is in application mode.

    Use this event to run any setup that doesn't require any visuals such as loading
    configuration and binding keys.

    - [ ] Bubbles
    - [ ] Verbose
    """
    ...


class Idle(Event, bubble=False):
    """Sent when there are no more items in the message queue.

    This is a pseudo-event in that it is created by the Textual system and doesn't go
    through the usual message queue.

    - [ ] Bubbles
    - [ ] Verbose
    """
    ...


class Action(Event):
    __slots__ = ...
    def __init__(self, action: str) -> None:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    


class Resize(Event, bubble=False):
    """Sent when the app or widget has been resized.

    - [ ] Bubbles
    - [ ] Verbose

    Args:
        size: The new size of the Widget.
        virtual_size: The virtual size (scrollable size) of the Widget.
        container_size: The size of the Widget's container widget.
    """
    __slots__ = ...
    def __init__(self, size: Size, virtual_size: Size, container_size: Size | None = ..., pixel_size: Size | None = ...) -> None:
        ...
    
    @classmethod
    def from_dimensions(cls, cells: tuple[int, int], pixels: tuple[int, int] | None) -> Resize:
        """Construct from basic dimensions.

        Args:
            cells: tuple of (<width>, <height>) in cells.
            pixels: tuple of (<width>, <height>) in pixels if known, or `None` if not known.

        """
        ...
    
    def can_replace(self, message: Message) -> bool:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    


class Compose(Event, bubble=False, verbose=True):
    """Sent to a widget to request it to compose and mount children.

    This event is used internally by Textual.
    You won't typically need to explicitly handle it,

    - [ ] Bubbles
    - [X] Verbose
    """
    ...


class Mount(Event, bubble=False, verbose=False):
    """Sent when a widget is *mounted* and may receive messages.

    - [ ] Bubbles
    - [ ] Verbose
    """
    ...


class Unmount(Event, bubble=False, verbose=False):
    """Sent when a widget is unmounted and may no longer receive messages.

    - [ ] Bubbles
    - [ ] Verbose
    """
    ...


class Show(Event, bubble=False):
    """Sent when a widget is first displayed.

    - [ ] Bubbles
    - [ ] Verbose
    """
    ...


class Hide(Event, bubble=False):
    """Sent when a widget has been hidden.

    - [ ] Bubbles
    - [ ] Verbose

    Sent when any of the following conditions apply:

    - The widget is removed from the DOM.
    - The widget is no longer displayed because it has been scrolled or clipped from the terminal or its container.
    - The widget has its `display` attribute set to `False`.
    - The widget's `display` style is set to `"none"`.
    """
    ...


class Ready(Event, bubble=False):
    """Sent to the `App` when the DOM is ready and the first frame has been displayed.

    - [ ] Bubbles
    - [ ] Verbose
    """
    ...


@rich.repr.auto
class MouseCapture(Event, bubble=False):
    """Sent when the mouse has been captured.

    - [ ] Bubbles
    - [ ] Verbose

    When a mouse has been captured, all further mouse events will be sent to the capturing widget.

    Args:
        mouse_position: The position of the mouse when captured.
    """
    def __init__(self, mouse_position: Offset) -> None:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    


@rich.repr.auto
class MouseRelease(Event, bubble=False):
    """Mouse has been released.

    - [ ] Bubbles
    - [ ] Verbose

    Args:
        mouse_position: The position of the mouse when released.
    """
    def __init__(self, mouse_position: Offset) -> None:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    


class InputEvent(Event):
    """Base class for input events."""
    ...


@rich.repr.auto
class Key(InputEvent):
    """Sent when the user hits a key on the keyboard.

    - [X] Bubbles
    - [ ] Verbose

    Args:
        key: The key that was pressed.
        character: A printable character or `None` if it is not printable.
    """
    __slots__ = ...
    def __init__(self, key: str, character: str | None) -> None:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    
    @property
    def name(self) -> str:
        """Name of a key suitable for use as a Python identifier."""
        ...
    
    @property
    def name_aliases(self) -> list[str]:
        """The corresponding name for every alias in `aliases` list."""
        ...
    
    @property
    def is_printable(self) -> bool:
        """Check if the key is printable (produces a unicode character).

        Returns:
            `True` if the key is printable.
        """
        ...
    


@rich.repr.auto
class MouseEvent(InputEvent, bubble=True):
    """Sent in response to a mouse event.

    - [X] Bubbles
    - [ ] Verbose

    Args:
        widget: The widget under the mouse.
        x: The relative x coordinate.
        y: The relative y coordinate.
        delta_x: Change in x since the last message.
        delta_y: Change in y since the last message.
        button: Indexed of the pressed button.
        shift: True if the shift key is pressed.
        meta: True if the meta key is pressed.
        ctrl: True if the ctrl key is pressed.
        screen_x: The absolute x coordinate.
        screen_y: The absolute y coordinate.
        style: The Rich Style under the mouse cursor.
    """
    __slots__ = ...
    def __init__(self, widget: Widget | None, x: float, y: float, delta_x: int, delta_y: int, button: int, shift: bool, meta: bool, ctrl: bool, screen_x: float | None = ..., screen_y: float | None = ..., style: Style | None = ...) -> None:
        ...
    
    @property
    def x(self) -> int:
        """The relative X coordinate of the cell under the mouse."""
        ...
    
    @property
    def y(self) -> int:
        """The relative Y coordinate of the cell under the mouse."""
        ...
    
    @property
    def delta_x(self) -> int:
        """Change in `x` since last message."""
        ...
    
    @property
    def delta_y(self) -> int:
        """Change in `y` since the last message."""
        ...
    
    @property
    def screen_x(self) -> int:
        """X coordinate of the cell relative to top left of screen."""
        ...
    
    @property
    def screen_y(self) -> int:
        """Y coordinate of the cell relative to top left of screen."""
        ...
    
    @property
    def pointer_x(self) -> float:
        """The relative X coordinate of the pointer."""
        ...
    
    @property
    def pointer_y(self) -> float:
        """The relative Y coordinate of the pointer."""
        ...
    
    @property
    def pointer_screen_x(self) -> float:
        """The X coordinate of the pointer relative to the screen."""
        ...
    
    @property
    def pointer_screen_y(self) -> float:
        """The Y coordinate of the pointer relative to the screen."""
        ...
    
    @classmethod
    def from_event(cls: Type[MouseEventT], widget: Widget, event: MouseEvent) -> MouseEventT:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    
    @property
    def control(self) -> Widget | None:
        ...
    
    @property
    def offset(self) -> Offset:
        """The mouse coordinate as an offset.

        Returns:
            Mouse coordinate.
        """
        ...
    
    @property
    def screen_offset(self) -> Offset:
        """Mouse coordinate relative to the screen."""
        ...
    
    @property
    def delta(self) -> Offset:
        """Mouse coordinate delta (change since last event)."""
        ...
    
    @property
    def style(self) -> Style:
        """The (Rich) Style under the cursor."""
        ...
    
    @style.setter
    def style(self, style: Style) -> None:
        ...
    
    def get_content_offset(self, widget: Widget) -> Offset | None:
        """Get offset within a widget's content area, or None if offset is not in content (i.e. padding or border).

        Args:
            widget: Widget receiving the event.

        Returns:
            An offset where the origin is at the top left of the content area.
        """
        ...
    
    def get_content_offset_capture(self, widget: Widget) -> Offset:
        """Get offset from a widget's content area.

        This method works even if the offset is outside the widget content region.

        Args:
            widget: Widget receiving the event.

        Returns:
            An offset where the origin is at the top left of the content area.
        """
        ...
    


@rich.repr.auto
class MouseMove(MouseEvent, bubble=True, verbose=True):
    """Sent when the mouse cursor moves.

    - [X] Bubbles
    - [X] Verbose
    """
    ...


@rich.repr.auto
class MouseDown(MouseEvent, bubble=True, verbose=True):
    """Sent when a mouse button is pressed.

    - [X] Bubbles
    - [X] Verbose
    """
    ...


@rich.repr.auto
class MouseUp(MouseEvent, bubble=True, verbose=True):
    """Sent when a mouse button is released.

    - [X] Bubbles
    - [X] Verbose
    """
    ...


@rich.repr.auto
class MouseScrollDown(MouseEvent, bubble=True, verbose=True):
    """Sent when the mouse wheel is scrolled *down*.

    - [X] Bubbles
    - [X] Verbose
    """
    ...


@rich.repr.auto
class MouseScrollUp(MouseEvent, bubble=True, verbose=True):
    """Sent when the mouse wheel is scrolled *up*.

    - [X] Bubbles
    - [X] Verbose
    """
    ...


@rich.repr.auto
class MouseScrollRight(MouseEvent, bubble=True, verbose=True):
    """Sent when the mouse wheel is scrolled *right*.

    - [X] Bubbles
    - [X] Verbose
    """
    ...


@rich.repr.auto
class MouseScrollLeft(MouseEvent, bubble=True, verbose=True):
    """Sent when the mouse wheel is scrolled *left*.

    - [X] Bubbles
    - [X] Verbose
    """
    ...


class Click(MouseEvent, bubble=True):
    """Sent when a widget is clicked.

    - [X] Bubbles
    - [ ] Verbose

    Args:
        chain: The number of clicks in the chain. 2 is a double click, 3 is a triple click, etc.
    """
    def __init__(self, widget: Widget | None, x: int, y: int, delta_x: int, delta_y: int, button: int, shift: bool, meta: bool, ctrl: bool, screen_x: int | None = ..., screen_y: int | None = ..., style: Style | None = ..., chain: int = ...) -> None:
        ...
    
    @classmethod
    def from_event(cls: Type[Self], widget: Widget, event: MouseEvent, chain: int = ...) -> Self:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    


@rich.repr.auto
class Timer(Event, bubble=False, verbose=True):
    """Sent in response to a timer.

    - [ ] Bubbles
    - [X] Verbose
    """
    __slots__ = ...
    def __init__(self, timer: TimerClass, time: float, count: int = ..., callback: TimerCallback | None = ...) -> None:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    


class Enter(Event, bubble=True, verbose=True):
    """Sent when the mouse is moved over a widget.

    Note that this event bubbles, so a widget may receive this event when the mouse
    moves over a child widget. Check the `node` attribute for the widget directly under
    the mouse.

    - [X] Bubbles
    - [X] Verbose
    """
    __slots__ = ...
    def __init__(self, node: DOMNode) -> None:
        ...
    
    @property
    def control(self) -> DOMNode:
        """Alias for the `node` under the mouse."""
        ...
    


class Leave(Event, bubble=True, verbose=True):
    """Sent when the mouse is moved away from a widget, or if a widget is
    programmatically disabled while hovered.

    Note that this widget bubbles, so a widget may receive Leave events for any child widgets.
    Check the `node` parameter for the original widget that was previously under the mouse.


    - [X] Bubbles
    - [X] Verbose
    """
    __slots__ = ...
    def __init__(self, node: DOMNode) -> None:
        ...
    
    @property
    def control(self) -> DOMNode:
        """Alias for the `node` that was previously under the mouse."""
        ...
    


class Focus(Event, bubble=False):
    """Sent when a widget is focussed.

    - [ ] Bubbles
    - [ ] Verbose

    Args:
        from_app_focus: True if this focus event has been sent because the app itself has
            regained focus (via an AppFocus event). False if the focus came from within
            the Textual app (e.g. via the user pressing tab or a programmatic setting
            of the focused widget).
    """
    def __init__(self, from_app_focus: bool = ...) -> None:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    


class Blur(Event, bubble=False):
    """Sent when a widget is blurred (un-focussed).

    - [ ] Bubbles
    - [ ] Verbose
    """
    ...


class AppFocus(Event, bubble=False):
    """Sent when the app has focus.

    - [ ] Bubbles
    - [ ] Verbose

    Note:
        Only available when running within a terminal that supports
        `FocusIn`, or when running via textual-web.
    """
    ...


class AppBlur(Event, bubble=False):
    """Sent when the app loses focus.

    - [ ] Bubbles
    - [ ] Verbose

    Note:
        Only available when running within a terminal that supports
        `FocusOut`, or when running via textual-web.
    """
    ...


@dataclass
class DescendantFocus(Event, bubble=True, verbose=True):
    """Sent when a child widget is focussed.

    - [X] Bubbles
    - [X] Verbose
    """
    widget: Widget
    @property
    def control(self) -> Widget:
        """The widget that was focused (alias of `widget`)."""
        ...
    


@dataclass
class DescendantBlur(Event, bubble=True, verbose=True):
    """Sent when a child widget is blurred.

    - [X] Bubbles
    - [X] Verbose
    """
    widget: Widget
    @property
    def control(self) -> Widget:
        """The widget that was blurred (alias of `widget`)."""
        ...
    


@rich.repr.auto
class Paste(Event, bubble=True):
    """Event containing text that was pasted into the Textual application.
    This event will only appear when running in a terminal emulator that supports
    bracketed paste mode. Textual will enable bracketed pastes when an app starts,
    and disable it when the app shuts down.

    - [X] Bubbles
    - [ ] Verbose


    Args:
        text: The text that has been pasted.
    """
    def __init__(self, text: str) -> None:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    


@dataclass
class ScreenResume(Event, bubble=False):
    """Sent to screen that has been made active.

    - [ ] Bubbles
    - [ ] Verbose
    """
    refresh_styles: bool = ...
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    


class ScreenSuspend(Event, bubble=False):
    """Sent to screen when it is no longer active.

    - [ ] Bubbles
    - [ ] Verbose
    """
    ...


@rich.repr.auto
class Print(Event, bubble=False):
    """Sent to a widget that is capturing [`print`][print].

    - [ ] Bubbles
    - [ ] Verbose

    Args:
        text: Text that was printed.
        stderr: `True` if the print was to stderr, or `False` for stdout.

    Note:
        Python's [`print`][print] output can be captured with
        [`App.begin_capture_print`][textual.app.App.begin_capture_print].
    """
    def __init__(self, text: str, stderr: bool = ...) -> None:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    


@dataclass
class DeliveryComplete(Event, bubble=False):
    """Sent to App when a file has been delivered."""
    key: str
    path: Path | None = ...
    name: str | None = ...


@dataclass
class DeliveryFailed(Event, bubble=False):
    """Sent to App when a file delivery fails."""
    key: str
    exception: BaseException
    name: str | None = ...


class TextSelected(Event, bubble=True):
    """Sent from the screen when text is selected (Not Input and TextArea)"""
    ...


