"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from typing_extensions import Final, Literal

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
FEATURES: Final = ...
FeatureFlag = Literal["devtools", "debug", "headless"]
def parse_features(features: str) -> frozenset[FeatureFlag]:
    """Parse features env var

    Args:
        features: Comma separated feature flags

    Returns:
        A frozen set of known features.
    """
    ...

