"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import ClassVar, Iterable, NamedTuple, TYPE_CHECKING
from textual._spatial_map import SpatialMap
from textual.geometry import Offset, Region, Size, Spacing
from textual.strip import StripRenderable
from typing_extensions import TypeAlias
from textual.widget import Widget

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
ArrangeResult: TypeAlias = "list[WidgetPlacement]"
@dataclass
class DockArrangeResult:
    """Result of [Layout.arrange][textual.layout.Layout.arrange]."""
    placements: list[WidgetPlacement]
    widgets: set[Widget]
    scroll_spacing: Spacing
    _spatial_map: SpatialMap[WidgetPlacement] | None = ...
    @property
    def spatial_map(self) -> SpatialMap[WidgetPlacement]:
        """A lazy-calculated spatial map."""
        ...
    
    @property
    def total_region(self) -> Region:
        """The total area occupied by the arrangement.

        Returns:
            A Region.
        """
        ...
    
    def get_visible_placements(self, region: Region) -> list[WidgetPlacement]:
        """Get the placements visible within the given region.

        Args:
            region: A region.

        Returns:
            Set of placements.
        """
        ...
    


class WidgetPlacement(NamedTuple):
    """The position, size, and relative order of a widget within its parent."""
    region: Region
    offset: Offset
    margin: Spacing
    widget: Widget
    order: int = ...
    fixed: bool = ...
    overlay: bool = ...
    absolute: bool = ...
    @property
    def reset_origin(self) -> WidgetPlacement:
        """Reset the origin in the placement (moves it to (0, 0))."""
        ...
    
    @classmethod
    def translate(cls, placements: list[WidgetPlacement], translate_offset: Offset) -> list[WidgetPlacement]:
        """Move all non-absolute placements by a given offset.

        Args:
            placements: List of placements.
            offset: Offset to add to placements.

        Returns:
            Placements with adjusted region, or same instance if offset is null.
        """
        ...
    
    @classmethod
    def apply_absolute(cls, placements: list[WidgetPlacement]) -> None:
        """Applies absolute offsets (in place).

        Args:
            placements: A list of placements.
        """
        ...
    
    @classmethod
    def get_bounds(cls, placements: Iterable[WidgetPlacement]) -> Region:
        """Get a bounding region around all placements.

        Args:
            placements: A number of placements.

        Returns:
            An optimal binding box around all placements.
        """
        ...
    
    def process_offset(self, constrain_region: Region, absolute_offset: Offset) -> WidgetPlacement:
        """Apply any absolute offset or constrain rules to the placement.

        Args:
            constrain_region: The container region when applying constrain rules.
            absolute_offset: Default absolute offset that moves widget into screen coordinates.

        Returns:
            Processes placement, may be the same instance.
        """
        ...
    


class Layout(ABC):
    """Base class of the object responsible for arranging Widgets within a container."""
    name: ClassVar[str] = ...
    def __repr__(self) -> str:
        ...
    
    @abstractmethod
    def arrange(self, parent: Widget, children: list[Widget], size: Size, greedy: bool = ...) -> ArrangeResult:
        """Generate a layout map that defines where on the screen the widgets will be drawn.

        Args:
            parent: Parent widget.
            size: Size of container.

        Returns:
            An iterable of widget location
        """
        ...
    
    def get_content_width(self, widget: Widget, container: Size, viewport: Size) -> int:
        """Get the optimal content width by arranging children.

        Args:
            widget: The container widget.
            container: The container size.
            viewport: The viewport size.

        Returns:
            Width of the content.
        """
        ...
    
    def get_content_height(self, widget: Widget, container: Size, viewport: Size, width: int) -> int:
        """Get the content height.

        Args:
            widget: The container widget.
            container: The container size.
            viewport: The viewport.
            width: The content width.

        Returns:
            Content height (in lines).
        """
        ...
    
    def render_keyline(self, container: Widget) -> StripRenderable:
        """Render keylines around all widgets.

        Args:
            container: The container widget.

        Returns:
            A renderable to draw the keylines.
        """
        ...
    


