"""
This type stub file was generated by pyright.
"""

from textual.widget import Widget

"""
This type stub file was generated by pyright.
"""
class Lazy(Widget):
    """Wraps a widget so that it is mounted *lazily*.

    Lazy widgets are mounted after the first refresh. This can be used to display some parts of
    the UI very quickly, followed by the lazy widgets. Technically, this won't make anything
    faster, but it reduces the time the user sees a blank screen and will make apps feel
    more responsive.

    Making a widget lazy is beneficial for widgets which start out invisible, such as tab panes.

    Note that since lazy widgets aren't mounted immediately (by definition), they will not appear
    in queries for a brief interval until they are mounted. Your code should take this into account.

    Example:
        ```python
        def compose(self) -> ComposeResult:
            yield Footer()
            with ColorTabs("Theme Colors", "Named Colors"):
                yield Content(ThemeColorButtons(), ThemeColorsView(), id="theme")
                yield Lazy(NamedColorsView())
        ```

    """
    DEFAULT_CSS = ...
    def __init__(self, widget: Widget) -> None:
        """Create a lazy widget.

        Args:
            widget: A widget that should be mounted after a refresh.
        """
        ...
    
    def compose_add_child(self, widget: Widget) -> None:
        ...
    
    async def mount_composed_widgets(self, widgets: list[Widget]) -> None:
        ...
    


class Reveal(Widget):
    """Similar to [Lazy][textual.lazy.Lazy], but mounts children sequentially.

    This is useful when you have so many child widgets that there is a noticeable delay before
    you see anything. By mounting the children over several frames, the user will feel that
    something is happening.

    Example:
        ```python
        def compose(self) -> ComposeResult:
            with lazy.Reveal(containers.VerticalScroll(can_focus=False)):
                yield Markdown(WIDGETS_MD, classes="column")
                yield Buttons()
                yield Checkboxes()
                yield Datatables()
                yield Inputs()
                yield ListViews()
                yield Logs()
                yield Sparklines()
            yield Footer()
        ```
    """
    DEFAULT_CSS = ...
    def __init__(self, widget: Widget) -> None:
        """
        Args:
            widget: A widget to mount.
        """
        ...
    
    def compose_add_child(self, widget: Widget) -> None:
        ...
    
    async def mount_composed_widgets(self, widgets: list[Widget]) -> None:
        ...
    


