"""
This type stub file was generated by pyright.
"""

from logging import Handler, LogRecord

"""
This type stub file was generated by pyright.
"""
class TextualHandler(Handler):
    """A Logging handler for Textual apps."""
    def __init__(self, stderr: bool = ..., stdout: bool = ...) -> None:
        """Initialize a Textual logging handler.

        Args:
            stderr: Log to stderr when there is no active app.
            stdout: Log to stdout when there is no active app.
        """
        ...
    
    def emit(self, record: LogRecord) -> None:
        """Invoked by logging."""
        ...
    


