"""
This type stub file was generated by pyright.
"""

import rich.repr
from typing import ClassVar, TYPE_CHECKING
from typing_extensions import Self
from textual.dom import DOMNode
from textual.message_pump import MessagePump

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
@rich.repr.auto
class Message:
    """Base class for a message."""
    __slots__ = ...
    ALLOW_SELECTOR_MATCH: ClassVar[set[str]] = ...
    bubble: ClassVar[bool] = ...
    verbose: ClassVar[bool] = ...
    no_dispatch: ClassVar[bool] = ...
    namespace: ClassVar[str] = ...
    handler_name: ClassVar[str]
    def __init__(self) -> None:
        ...
    
    def __post_init__(self) -> None:
        """Allow dataclasses to initialize the object."""
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    
    def __init_subclass__(cls, bubble: bool | None = ..., verbose: bool = ..., no_dispatch: bool | None = ..., namespace: str | None = ...) -> None:
        ...
    
    @property
    def control(self) -> DOMNode | None:
        """The widget associated with this message, or None by default."""
        ...
    
    @property
    def is_forwarded(self) -> bool:
        """Has the message been forwarded?"""
        ...
    
    def set_sender(self, sender: MessagePump) -> Self:
        """Set the sender of the message.

        Args:
            sender: The sender.

        Note:
            When creating a message the sender is automatically set.
            Normally there will be no need for this method to be called.
            This method will be used when strict control is required over
            the sender of a message.

        Returns:
            Self.
        """
        ...
    
    def can_replace(self, message: Message) -> bool:
        """Check if another message may supersede this one.

        Args:
            message: Another message.

        Returns:
            True if this message may replace the given message
        """
        ...
    
    def prevent_default(self, prevent: bool = ...) -> Message:
        """Suppress the default action(s). This will prevent handlers in any base classes
        from being called.

        Args:
            prevent: True if the default action should be suppressed,
                or False if the default actions should be performed.
        """
        ...
    
    def stop(self, stop: bool = ...) -> Message:
        """Stop propagation of the message to parent.

        Args:
            stop: The stop flag.
        """
        ...
    


