"""
This type stub file was generated by pyright.
"""

from rich.console import Console, ConsoleOptions, JustifyMethod, RenderResult, RenderableType
from rich.measure import Measurement
from rich.style import Style

"""
This type stub file was generated by pyright.
"""
class HorizontalPad:
    """Rich renderable to add padding on the left and right of a renderable.

    Note that unlike Rich's Padding class this align each line independently.

    """
    def __init__(self, renderable: RenderableType, left: int, right: int, pad_style: Style, justify: JustifyMethod) -> None:
        """
        Initialize HorizontalPad.

        Args:
            renderable: A Rich renderable.
            left: Left padding.
            right: Right padding.
            pad_style: Style of padding.
            justify: Justify method.
        """
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    
    def __rich_measure__(self, console: Console, options: ConsoleOptions) -> Measurement:
        ...
    


