"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class RLock:
    """A re-entrant asyncio lock."""
    def __init__(self) -> None:
        ...
    
    async def acquire(self) -> None:
        """Wait until the lock can be acquired."""
        ...
    
    def release(self) -> None:
        """Release a previously acquired lock."""
        ...
    
    @property
    def is_locked(self):
        """Return True if lock is acquired."""
        ...
    
    async def __aenter__(self) -> None:
        """Asynchronous context manager to acquire and release lock."""
        ...
    
    async def __aexit__(self, _type, _value, _traceback) -> None:
        """Exit the context manager."""
        ...
    


if __name__ == "__main__":
    async def locks():
        ...
    
