"""
This type stub file was generated by pyright.
"""

import asyncio
import rich.repr
from typing import Any, Awaitable, Callable, ClassVar, Generic, Iterable, NamedTuple, Optional, TYPE_CHECKING, TypeVar, Union
from rich.console import RenderableType
from rich.style import Style
from textual._compositor import MapGeometry
from textual._path import CSSPathType
from textual.await_complete import AwaitComplete
from textual.binding import ActiveBinding
from textual.css.query import QueryType
from textual.css.styles import PointerShape
from textual.geometry import Offset, Region, Size
from textual.layout import DockArrangeResult
from textual.reactive import Reactive, var
from textual.selection import SelectState, Selection
from textual.widget import Widget
from typing_extensions import Final
from textual.command import Provider
from textual.message_pump import MessagePump

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
UPDATE_PERIOD: Final[float] = ...
ScreenResultType = TypeVar("ScreenResultType")
ScreenResultCallbackType = Union[Callable[[Optional[ScreenResultType]], None], Callable[[Optional[ScreenResultType]], Awaitable[None]],]
class HoverWidgets(NamedTuple):
    """Result of [get_hover_widget_at][textual.screen.Screen.get_hover_widget_at]"""
    mouse_over: tuple[Widget, Region]
    hover_over: tuple[Widget, Region] | None
    @property
    def widgets(self) -> tuple[Widget, Widget | None]:
        """Just the widgets."""
        ...
    


@rich.repr.auto
class ResultCallback(Generic[ScreenResultType]):
    """Holds the details of a callback."""
    def __init__(self, requester: MessagePump, callback: ScreenResultCallbackType[ScreenResultType] | None, future: asyncio.Future[ScreenResultType] | None = ...) -> None:
        """Initialise the result callback object.

        Args:
            requester: The object making a request for the callback.
            callback: The callback function.
            future: A Future to hold the result.
        """
        ...
    
    def __call__(self, result: ScreenResultType) -> None:
        """Call the callback, passing the given result.

        Args:
            result: The result to pass to the callback.

        Note:
            If the requested or the callback are `None` this will be a no-op.
        """
        ...
    


@rich.repr.auto
class Screen(Generic[ScreenResultType], Widget):
    """The base class for screens."""
    AUTO_FOCUS: ClassVar[str | None] = ...
    CSS: ClassVar[str] = ...
    CSS_PATH: ClassVar[CSSPathType | None] = ...
    COMPONENT_CLASSES = ...
    DEFAULT_CSS = ...
    TITLE: ClassVar[str | None] = ...
    SUB_TITLE: ClassVar[str | None] = ...
    HORIZONTAL_BREAKPOINTS: ClassVar[list[tuple[int, str]]] | None = ...
    VERTICAL_BREAKPOINTS: ClassVar[list[tuple[int, str]]] | None = ...
    focused: Reactive[Widget | None] = ...
    stack_updates: Reactive[int] = ...
    sub_title: Reactive[str | None] = ...
    title: Reactive[str | None] = ...
    COMMANDS: ClassVar[set[type[Provider] | Callable[[], type[Provider]]]] = ...
    ALLOW_IN_MAXIMIZED_VIEW: ClassVar[str | None] = ...
    ESCAPE_TO_MINIMIZE: ClassVar[bool | None] = ...
    maximized: Reactive[Widget | None] = ...
    selections: var[dict[Widget, Selection]] = ...
    _selecting = ...
    _select_state: Reactive[SelectState | None] = ...
    _mouse_down_offset: var[Offset | None] = ...
    _pointer_shape: var[PointerShape] = ...
    BINDINGS = ...
    def __init__(self, name: str | None = ..., id: str | None = ..., classes: str | None = ...) -> None:
        """
        Initialize the screen.

        Args:
            name: The name of the screen.
            id: The ID of the screen in the DOM.
            classes: The CSS classes for the screen.
        """
        ...
    
    @property
    def is_modal(self) -> bool:
        """Is the screen modal?"""
        ...
    
    @property
    def is_current(self) -> bool:
        """Is the screen current (i.e. visible to user)?"""
        ...
    
    @property
    def layers(self) -> tuple[str, ...]:
        """Layers from parent.

        Returns:
            Tuple of layer names.
        """
        ...
    
    @property
    def size(self) -> Size:
        """The size of the screen."""
        ...
    
    def refresh_bindings(self) -> None:
        """Call to request a refresh of bindings."""
        ...
    
    @property
    def active_bindings(self) -> dict[str, ActiveBinding]:
        """Get currently active bindings for this screen.

        If no widget is focused, then app-level bindings are returned.
        If a widget is focused, then any bindings present in the screen and app are merged and returned.

        This property may be used to inspect current bindings.

        Returns:
            A map of keys to a tuple containing (NAMESPACE, BINDING, ENABLED).
        """
        ...
    
    def arrange(self, size: Size, _optimal: bool = ...) -> DockArrangeResult:
        """Arrange children.

        Args:
            size: Size of container.
            optimal: Ignored on screen.

        Returns:
            Widget locations.
        """
        ...
    
    @property
    def is_active(self) -> bool:
        """Is the screen active (i.e. visible and top of the stack)?"""
        ...
    
    @property
    def allow_select(self) -> bool:
        """Check if this widget permits text selection."""
        ...
    
    def get_loading_widget(self) -> Widget:
        """Get a widget to display a loading indicator.

        The default implementation will defer to App.get_loading_widget.

        Returns:
            A widget in place of this widget to indicate a loading.
        """
        ...
    
    def update_pointer_shape(self) -> None:
        """Get the screen's current pointer shape."""
        ...
    
    def render(self) -> RenderableType:
        """Render method inherited from widget, used to render the screen's background.

        Returns:
            Background renderable.
        """
        ...
    
    def get_offset(self, widget: Widget) -> Offset:
        """Get the absolute offset of a given Widget.

        Args:
            widget: A widget

        Returns:
            The widget's offset relative to the top left of the terminal.
        """
        ...
    
    def get_widget_at(self, x: int, y: int) -> tuple[Widget, Region]:
        """Get the widget at a given coordinate.

        Args:
            x: X Coordinate.
            y: Y Coordinate.

        Returns:
            Widget and screen region.

        Raises:
            NoWidget: If there is no widget under the screen coordinate.
        """
        ...
    
    def get_hover_widgets_at(self, x: int, y: int) -> HoverWidgets:
        """Get the widget, and its region directly under the mouse, and the first
        widget, region pair with a hover style.

        Args:
            x: X Coordinate.
            y: Y Coordinate.

        Returns:
            A pair of (WIDGET, REGION) tuples for the top most and first hover style respectively.

        Raises:
            NoWidget: If there is no widget under the screen coordinate.

        """
        ...
    
    def get_widgets_at(self, x: int, y: int) -> Iterable[tuple[Widget, Region]]:
        """Get all widgets under a given coordinate.

        Args:
            x: X coordinate.
            y: Y coordinate.

        Returns:
            Sequence of (WIDGET, REGION) tuples.
        """
        ...
    
    def get_focusable_widget_at(self, x: int, y: int) -> Widget | None:
        """Get the focusable widget under a given coordinate.

        If the widget directly under the given coordinate is not focusable, then this method will check
        if any of the ancestors are focusable. If no ancestors are focusable, then `None` will be returned.

        Args:
            x: X coordinate.
            y: Y coordinate.

        Returns:
            A `Widget`, or `None` if there is no focusable widget underneath the coordinate.
        """
        ...
    
    def get_style_at(self, x: int, y: int) -> Style:
        """Get the style under a given coordinate.

        Args:
            x: X Coordinate.
            y: Y Coordinate.

        Returns:
            Rich Style object.
        """
        ...
    
    def get_widget_and_offset_at(self, x: int, y: int) -> tuple[Widget | None, Offset | None]:
        """Get the widget under a given coordinate, and an offset within the original content.

        Args:
            x: X Coordinate.
            y: Y Coordinate.

        Returns:
            Tuple of Widget and Offset, both of which may be None.
        """
        ...
    
    def find_widget(self, widget: Widget) -> MapGeometry:
        """Get the screen region of a Widget.

        Args:
            widget: A Widget within the composition.

        Returns:
            Region relative to screen.

        Raises:
            NoWidget: If the widget could not be found in this screen.
        """
        ...
    
    def clear_selection(self) -> None:
        """Clear any selected text."""
        ...
    
    @property
    def focus_chain(self) -> list[Widget]:
        """A list of widgets that may receive focus, in focus order."""
        ...
    
    def focus_next(self, selector: str | type[QueryType] = ...) -> Widget | None:
        """Focus the next widget, optionally filtered by a CSS selector.

        If no widget is currently focused, this will focus the first focusable widget.
        If no focusable widget matches the given CSS selector, focus is set to `None`.

        Args:
            selector: CSS selector to filter
                what nodes can be focused.

        Returns:
            Newly focused widget, or None for no focus. If the return
                is not `None`, then it is guaranteed that the widget returned matches
                the CSS selectors given in the argument.
        """
        ...
    
    def focus_previous(self, selector: str | type[QueryType] = ...) -> Widget | None:
        """Focus the previous widget, optionally filtered by a CSS selector.

        If no widget is currently focused, this will focus the first focusable widget.
        If no focusable widget matches the given CSS selector, focus is set to `None`.

        Args:
            selector: CSS selector to filter
                what nodes can be focused.

        Returns:
            Newly focused widget, or None for no focus. If the return
                is not `None`, then it is guaranteed that the widget returned matches
                the CSS selectors given in the argument.
        """
        ...
    
    def maximize(self, widget: Widget, container: bool = ...) -> bool:
        """Maximize a widget, so it fills the screen.

        Args:
            widget: Widget to maximize.
            container: If one of the widgets ancestors is a maximizeable widget, maximize that instead.

        Returns:
            `True` if the widget was maximized, otherwise `False`.
        """
        ...
    
    def minimize(self) -> None:
        """Restore any maximized widget to normal state."""
        ...
    
    def get_selected_text(self) -> str | None:
        """Get text under selection.

        Returns:
            Selected text, or `None` if no text was selected.
        """
        ...
    
    def action_copy_text(self) -> None:
        """Copy selected text to clipboard."""
        ...
    
    def action_maximize(self) -> None:
        """Action to maximize the currently focused widget."""
        ...
    
    def action_minimize(self) -> None:
        """Action to minimize the currently maximized widget."""
        ...
    
    def action_blur(self) -> None:
        """Action to remove focus (if set)."""
        ...
    
    async def action_focus(self, selector: str) -> None:
        """An [action](/guide/actions) to focus the given widget.

        Args:
            selector: Selector of widget to focus (first match).
        """
        ...
    
    def set_focus(self, widget: Widget | None, scroll_visible: bool = ..., from_app_focus: bool = ...) -> None:
        """Focus (or un-focus) a widget. A focused widget will receive key events first.

        Args:
            widget: Widget to focus, or None to un-focus.
            scroll_visible: Scroll widget into view.
            from_app_focus: True if this focus is due to the app itself having regained
                focus. False if the focus is being set because a widget within the app
                regained focus.
        """
        ...
    
    def dismiss(self, result: ScreenResultType | None = ...) -> AwaitComplete:
        """Dismiss the screen, optionally with a result.

        Any callback provided in [push_screen][textual.app.App.push_screen] will be invoked with the supplied result.

        !!! warning

            Textual will raise a [`ScreenError`][textual.app.ScreenError] if you await the return value from a
            message handler on the Screen being dismissed. If you want to dismiss the current screen, you can
            call `self.dismiss()` _without_ awaiting.

        Args:
            result: The optional result to be passed to the result callback.

        """
        ...
    
    def pop_until_active(self) -> None:
        """Pop any screens on top of this one, until this screen is active.

        Raises:
            ScreenError: If this screen is not in the current mode.

        """
        ...
    
    async def action_dismiss(self, result: ScreenResultType | None = ...) -> None:
        """A wrapper around [`dismiss`][textual.screen.Screen.dismiss] that can be called as an action.

        Args:
            result: The optional result to be passed to the result callback.
        """
        ...
    
    def can_view_entire(self, widget: Widget) -> bool:
        """Check if a given widget is fully within the current screen.

        Note: This doesn't necessarily equate to a widget being visible.
        There are other reasons why a widget may not be visible.

        Args:
            widget: A widget.

        Returns:
            `True` if the entire widget is in view, `False` if it is partially visible or not in view.
        """
        ...
    
    def can_view_partial(self, widget: Widget) -> bool:
        """Check if a given widget is at least partially within the current view.

        Args:
            widget: A widget.

        Returns:
            `True` if the any part of the widget is in view, `False` if it is completely outside of the screen.
        """
        ...
    
    def validate_title(self, title: Any) -> str | None:
        """Ensure the title is a string or `None`."""
        ...
    
    def validate_sub_title(self, sub_title: Any) -> str | None:
        """Ensure the sub-title is a string or `None`."""
        ...
    


@rich.repr.auto
class ModalScreen(Screen[ScreenResultType]):
    """A screen with bindings that take precedence over the App's key bindings.

    The default styling of a modal screen will dim the screen underneath.
    """
    DEFAULT_CSS = ...
    def __init__(self, name: str | None = ..., id: str | None = ..., classes: str | None = ...) -> None:
        ...
    


class SystemModalScreen(ModalScreen[ScreenResultType], inherit_css=False):
    """A variant of `ModalScreen` for internal use.

    This version of `ModalScreen` allows us to build system-level screens;
    the type being used to indicate that the screen should be isolated from
    the main application.

    Note:
        This screen is set to *not* inherit CSS.
    """
    ...


