"""
This type stub file was generated by pyright.
"""

from typing import Any, Awaitable, Callable, Union
from rich.repr import Result, rich_repr
from textual._types import MessageTarget

"""
This type stub file was generated by pyright.
"""
TimerCallback = Union[Callable[[], Awaitable[Any]], Callable[[], Any]]
class EventTargetGone(Exception):
    """Raised if the timer event target has been deleted prior to the timer event being sent."""
    ...


@rich_repr
class Timer:
    """A class to send timer-based events.

    Args:
        event_target: The object which will receive the timer events.
        interval: The time between timer events, in seconds.
        name: A name to assign the event (for debugging).
        callback: An optional callback to invoke when the event is handled.
        repeat: The number of times to repeat the timer, or None to repeat forever.
        skip: Enable skipping of scheduled events that couldn't be sent in time.
        pause: Start the timer paused.
    """
    _timer_count: int = ...
    def __init__(self, event_target: MessageTarget, interval: float, *, name: str | None = ..., callback: TimerCallback | None = ..., repeat: int | None = ..., skip: bool = ..., pause: bool = ...) -> None:
        ...
    
    def __rich_repr__(self) -> Result:
        ...
    
    @property
    def target(self) -> MessageTarget:
        ...
    
    def stop(self) -> None:
        """Stop the timer."""
        ...
    
    def pause(self) -> None:
        """Pause the timer.

        A paused timer will not send events until it is resumed.
        """
        ...
    
    def reset(self) -> None:
        """Reset the timer, so it starts from the beginning."""
        ...
    
    def resume(self) -> None:
        """Resume a paused timer."""
        ...
    


