"""
This type stub file was generated by pyright.
"""

import re
import rich.repr
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Callable, Pattern, Sequence

"""
This type stub file was generated by pyright.
"""
@dataclass
class ValidationResult:
    """The result of calling a `Validator.validate` method."""
    failures: Sequence[Failure] = ...
    @staticmethod
    def merge(results: Sequence[ValidationResult]) -> ValidationResult:
        """Merge multiple ValidationResult objects into one.

        Args:
            results: List of ValidationResult objects to merge.

        Returns:
            Merged ValidationResult object.
        """
        ...
    
    @staticmethod
    def success() -> ValidationResult:
        """Construct a successful ValidationResult.

        Returns:
            A successful ValidationResult.
        """
        ...
    
    @staticmethod
    def failure(failures: Sequence[Failure]) -> ValidationResult:
        """Construct a failure ValidationResult.

        Args:
            failures: The failures.

        Returns:
            A failure ValidationResult.
        """
        ...
    
    @property
    def failure_descriptions(self) -> list[str]:
        """Utility for extracting failure descriptions as strings.

        Useful if you don't care about the additional metadata included in the `Failure` objects.

        Returns:
            A list of the string descriptions explaining the failing validations.
        """
        ...
    
    @property
    def is_valid(self) -> bool:
        """True if the validation was successful."""
        ...
    


@dataclass
class Failure:
    """Information about a validation failure."""
    validator: Validator
    value: str | None = ...
    description: str | None = ...
    def __post_init__(self) -> None:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    


class Validator(ABC):
    '''Base class for the validation of string values.

    Commonly used in conjunction with the `Input` widget, which accepts a
    list of validators via its constructor. This validation framework can also be used to validate any 'stringly-typed'
    values (for example raw command line input from `sys.args`).

    To implement your own `Validator`, subclass this class.

    Example:
        ```python
        def is_palindrome(value: str) -> bool:
            """Check has string has the same code points left to right, as right to left."""
            return value == value[::-1]

        class Palindrome(Validator):
            def validate(self, value: str) -> ValidationResult:
                if is_palindrome(value):
                    return self.success()
                else:
                    return self.failure("Not a palindrome!")
        ```
    '''
    def __init__(self, failure_description: str | None = ...) -> None:
        ...
    
    @abstractmethod
    def validate(self, value: str) -> ValidationResult:
        """Validate the value and return a ValidationResult describing the outcome of the validation.

        Implement this method when defining custom validators.

        Args:
            value: The value to validate.

        Returns:
            The result of the validation ([`self.success()`][textual.validation.Validator.success) or [`self.failure(...)`][textual.validation.Validator.failure]).
        """
        ...
    
    def describe_failure(self, failure: Failure) -> str | None:
        """Return a string description of the Failure.

        Used to provide a more fine-grained description of the failure. A Validator could fail for multiple
        reasons, so this method could be used to provide a different reason for different types of failure.

        !!! warning

            This method is only called if no other description has been supplied. If you supply a description
            inside a call to `self.failure(description="...")`, or pass a description into the constructor of
            the validator, those will take priority, and this method won't be called.

        Args:
            failure: Information about why the validation failed.

        Returns:
            A string description of the failure.
        """
        ...
    
    def success(self) -> ValidationResult:
        """Shorthand for `ValidationResult(True)`.

        Return `self.success()` from [`validate()`][textual.validation.Validator.validate] to indicated that validation *succeeded*.

        Returns:
            A ValidationResult indicating validation succeeded.
        """
        ...
    
    def failure(self, description: str | None = ..., value: str | None = ..., failures: Failure | Sequence[Failure] | None = ...) -> ValidationResult:
        """Shorthand for signaling validation failure.

        Return `self.failure(...)` from [`validate()`][textual.validation.Validator.validate] to indicated that validation *failed*.

        Args:
            description: The failure description that will be used. When used in conjunction with the Input widget,
                this is the description that will ultimately be available inside the handler for `Input.Changed`. If not
                supplied, the `failure_description` from the `Validator` will be used. If that is not supplied either,
                then the `describe_failure` method on `Validator` will be called.
            value: The value that was considered invalid. This is optional, and only needs to be supplied if required
                in your `Input.Changed` handler.
            failures: The reasons the validator failed. If not supplied, a generic `Failure` will be included in the
                ValidationResult returned from this function.

        Returns:
            A ValidationResult representing failed validation, and containing the metadata supplied
                to this function.
        """
        ...
    


class Regex(Validator):
    """A validator that checks the value matches a regex (via `re.fullmatch`)."""
    def __init__(self, regex: str | Pattern[str], flags: int | re.RegexFlag = ..., failure_description: str | None = ...) -> None:
        ...
    
    class NoResults(Failure):
        """Indicates validation failed because the regex could not be found within the value string."""
        ...
    
    
    def validate(self, value: str) -> ValidationResult:
        """Ensure that the value matches the regex.

        Args:
            value: The value that should match the regex.

        Returns:
            The result of the validation.
        """
        ...
    
    def describe_failure(self, failure: Failure) -> str | None:
        """Describes why the validator failed.

        Args:
            failure: Information about why the validation failed.

        Returns:
            A string description of the failure.
        """
        ...
    


class Number(Validator):
    """Validator that ensures the value is a number, with an optional range check."""
    def __init__(self, minimum: float | None = ..., maximum: float | None = ..., failure_description: str | None = ...) -> None:
        ...
    
    class NotANumber(Failure):
        """Indicates a failure due to the value not being a valid number (decimal/integer, inc. scientific notation)"""
        ...
    
    
    class NotInRange(Failure):
        """Indicates a failure due to the number not being within the range [minimum, maximum]."""
        ...
    
    
    def validate(self, value: str) -> ValidationResult:
        """Ensure that `value` is a valid number, optionally within a range.

        Args:
            value: The value to validate.

        Returns:
            The result of the validation.
        """
        ...
    
    def describe_failure(self, failure: Failure) -> str | None:
        """Describes why the validator failed.

        Args:
            failure: Information about why the validation failed.

        Returns:
            A string description of the failure.
        """
        ...
    


class Integer(Number):
    """Validator which ensures the value is an integer which falls within a range."""
    class NotAnInteger(Failure):
        """Indicates a failure due to the value not being a valid integer."""
        ...
    
    
    def validate(self, value: str) -> ValidationResult:
        """Ensure that `value` is an integer, optionally within a range.

        Args:
            value: The value to validate.

        Returns:
            The result of the validation.
        """
        ...
    
    def describe_failure(self, failure: Failure) -> str | None:
        """Describes why the validator failed.

        Args:
            failure: Information about why the validation failed.

        Returns:
            A string description of the failure.
        """
        ...
    


class Length(Validator):
    """Validate that a string is within a range (inclusive)."""
    def __init__(self, minimum: int | None = ..., maximum: int | None = ..., failure_description: str | None = ...) -> None:
        ...
    
    class Incorrect(Failure):
        """Indicates a failure due to the length of the value being outside the range."""
        ...
    
    
    def validate(self, value: str) -> ValidationResult:
        """Ensure that value falls within the maximum and minimum length constraints.

        Args:
            value: The value to validate.

        Returns:
            The result of the validation.
        """
        ...
    
    def describe_failure(self, failure: Failure) -> str | None:
        """Describes why the validator failed.

        Args:
            failure: Information about why the validation failed.

        Returns:
            A string description of the failure.
        """
        ...
    


class Function(Validator):
    """A flexible validator which allows you to provide custom validation logic."""
    def __init__(self, function: Callable[[str], bool], failure_description: str | None = ...) -> None:
        ...
    
    class ReturnedFalse(Failure):
        """Indicates validation failed because the supplied function returned False."""
        ...
    
    
    def validate(self, value: str) -> ValidationResult:
        """Validate that the supplied function returns True.

        Args:
            value: The value to pass into the supplied function.

        Returns:
            A ValidationResult indicating success if the function returned True,
                and failure if the function return False.
        """
        ...
    
    def describe_failure(self, failure: Failure) -> str | None:
        """Describes why the validator failed.

        Args:
            failure: Information about why the validation failed.

        Returns:
            A string description of the failure.
        """
        ...
    


class URL(Validator):
    """Validator that checks if a URL is valid (ensuring a scheme is present)."""
    class InvalidURL(Failure):
        """Indicates that the URL is not valid."""
        ...
    
    
    def validate(self, value: str) -> ValidationResult:
        """Validates that `value` is a valid URL (contains a scheme).

        Args:
            value: The value to validate.

        Returns:
            The result of the validation.
        """
        ...
    
    def describe_failure(self, failure: Failure) -> str | None:
        """Describes why the validator failed.

        Args:
            failure: Information about why the validation failed.

        Returns:
            A string description of the failure.
        """
        ...
    


