"""
This type stub file was generated by pyright.
"""

from typing import Iterable, TYPE_CHECKING, TypeVar, overload
from textual.geometry import Shape
from textual.dom import DOMNode
from textual.widget import Widget

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    WalkType = TypeVar("WalkType", bound=DOMNode)
if TYPE_CHECKING:
    @overload
    def walk_depth_first(root: DOMNode, *, with_root: bool = ...) -> Iterable[DOMNode]:
        ...
    
    @overload
    def walk_depth_first(root: WalkType, filter_type: type[WalkType], *, with_root: bool = ...) -> Iterable[WalkType]:
        ...
    
def walk_depth_first(root: DOMNode, filter_type: type[WalkType] | None = ..., *, with_root: bool = ...) -> Iterable[DOMNode] | Iterable[WalkType]:
    """Walk the tree depth first (parents first).

    !!! note

        Avoid changing the DOM (mounting, removing etc.) while iterating with this function.
        Consider [walk_children][textual.dom.DOMNode.walk_children] which doesn't have this limitation.

    Args:
        root: The root note (starting point).
        filter_type: Optional DOMNode subclass to filter by, or `None` for no filter.
        with_root: Include the root in the walk.

    Returns:
        An iterable of DOMNodes, or the type specified in `filter_type`.
    """
    ...

if TYPE_CHECKING:
    @overload
    def walk_breadth_first(root: DOMNode, *, with_root: bool = ...) -> Iterable[DOMNode]:
        ...
    
    @overload
    def walk_breadth_first(root: WalkType, filter_type: type[WalkType], *, with_root: bool = ...) -> Iterable[WalkType]:
        ...
    
def walk_breadth_first(root: DOMNode, filter_type: type[WalkType] | None = ..., *, with_root: bool = ...) -> Iterable[DOMNode] | Iterable[WalkType]:
    """Walk the tree breadth first (children first).

    !!! note

        Avoid changing the DOM (mounting, removing etc.) while iterating with this function.
        Consider [walk_children][textual.dom.DOMNode.walk_children] which doesn't have this limitation.

    Args:
        root: The root note (starting point).
        filter_type: Optional DOMNode subclass to filter by, or `None` for no filter.
        with_root: Include the root in the walk.

    Returns:
        An iterable of DOMNodes, or the type specified in `filter_type`.
    """
    ...

def walk_breadth_search_id(root: DOMNode, node_id: str, *, with_root: bool = ...) -> DOMNode | None:
    """Special case to walk breadth first searching for a node with a given id.

    This is more efficient than [walk_breadth_first][textual.walk.walk_breadth_first] for this special case, as it can use an index.

    Args:
        root: The root node (starting point).
        node_id: Node id to search for.
        with_root: Consider the root node? If the root has the node id, then return it.

    Returns:
        A DOMNode if a node was found, otherwise `None`.
    """
    ...

def walk_selectable_widgets(root: Widget, bounds: Shape, containers: set[DOMNode]) -> Iterable[Widget]:
    """Walk the tree depth first in select order (top to bottom, then left to right).

    Args:
        root: The root note (starting point).
        bounds: A Shape object that defines the selection bounds.
        bounded: Container widgets that require a bounds check.

    Returns:
        An iterable of DOMNodes.
    """
    ...

