"""
This type stub file was generated by pyright.
"""

import rich.repr
from contextlib import asynccontextmanager
from types import TracebackType
from typing import AsyncGenerator, Callable, ClassVar, Generator, Iterable, Mapping, NamedTuple, Sequence, TYPE_CHECKING, TypeVar, overload
from rich.console import Console, ConsoleOptions, ConsoleRenderable, JustifyMethod, RenderResult as RichRenderResult, RenderableType
from rich.measure import Measurement
from rich.style import Style
from rich.text import Text
from typing_extensions import Self
from textual.app import ComposeResult, RenderResult
from textual import events, messages
from textual._animator import Animatable, EasingFunction
from textual._arrange import DockArrangeResult
from textual._types import AnimationLevel
from textual.await_remove import AwaitRemove
from textual.content import Content, ContentType
from textual.css.query import QueryType
from textual.dom import DOMNode
from textual.geometry import Offset, Region, Size, Spacing
from textual.layout import Layout, WidgetPlacement
from textual.message import Message
from textual.messages import CallbackType, Prune
from textual.notifications import SeverityLevel
from textual.reactive import Reactive
from textual.selection import Selection
from textual.strip import Strip
from textual.style import Style as VisualStyle
from textual.visual import Visual, VisualType
from textual.filter import LineFilter
from textual.scrollbar import ScrollBar, ScrollBarCorner

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
if TYPE_CHECKING:
    ...
_JUSTIFY_MAP: dict[str, JustifyMethod] = ...
_MOUSE_EVENTS_DISALLOW_IF_DISABLED = ...
_MOUSE_EVENTS_ALLOW_IF_DISABLED = ...
@rich.repr.auto
class AwaitMount:
    """An *optional* awaitable returned by [mount][textual.widget.Widget.mount] and [mount_all][textual.widget.Widget.mount_all].

    Example:
        ```python
        await self.mount(Static("foo"))
        ```
    """
    def __init__(self, parent: Widget, widgets: Sequence[Widget]) -> None:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    
    async def __call__(self) -> None:
        """Allows awaiting via a call operation."""
        ...
    
    def __await__(self) -> Generator[None, None, None]:
        ...
    


class _Styled:
    """Apply a style to a renderable.

    Args:
        renderable: Any renderable.
        style: A style to apply across the entire renderable.
    """
    def __init__(self, renderable: ConsoleRenderable, style: Style, link_style: Style | None) -> None:
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RichRenderResult:
        ...
    
    def __rich_measure__(self, console: Console, options: ConsoleOptions) -> Measurement:
        ...
    


class _RenderCache(NamedTuple):
    """Stores results of a previous render."""
    size: Size
    lines: list[Strip]
    ...


class WidgetError(Exception):
    """Base widget error."""
    ...


class MountError(WidgetError):
    """Error raised when there was a problem with the mount request."""
    ...


class PseudoClasses(NamedTuple):
    """Used for render/render_line based widgets that use caching. This structure can be used as a
    cache-key."""
    enabled: bool
    focus: bool
    hover: bool
    ...


class _BorderTitle:
    """Descriptor to set border titles."""
    def __set_name__(self, owner: Widget, name: str) -> None:
        ...
    
    def __set__(self, obj: Widget, title: Text | ContentType | None) -> None:
        """Setting a title accepts a str, Text, or None."""
        ...
    
    def __get__(self, obj: Widget, objtype: type[Widget] | None = ...) -> str | None:
        """Getting a title will return None or a str as console markup."""
        ...
    


class BadWidgetName(Exception):
    """Raised when widget class names do not satisfy the required restrictions."""
    ...


@rich.repr.auto
class Widget(DOMNode):
    """
    A Widget is the base class for Textual widgets.

    See also [static][textual.widgets._static.Static] for starting point for your own widgets.
    """
    DEFAULT_CSS = ...
    COMPONENT_CLASSES: ClassVar[set[str]] = ...
    BORDER_TITLE: ClassVar[str] = ...
    BORDER_SUBTITLE: ClassVar[str] = ...
    ALLOW_MAXIMIZE: ClassVar[bool | None] = ...
    ALLOW_SELECT: ClassVar[bool] = ...
    FOCUS_ON_CLICK: ClassVar[bool] = ...
    BLANK: ClassVar[bool] = ...
    can_focus: bool = ...
    can_focus_children: bool = ...
    expand: Reactive[bool] = ...
    shrink: Reactive[bool] = ...
    auto_links: Reactive[bool] = ...
    disabled: Reactive[bool] = ...
    hover_style: Reactive[Style] = ...
    highlight_link_id: Reactive[str] = ...
    loading: Reactive[bool] = ...
    virtual_size = ...
    has_focus: Reactive[bool] = ...
    mouse_hover: Reactive[bool] = ...
    scroll_x: Reactive[float] = ...
    scroll_y: Reactive[float] = ...
    scroll_target_x = ...
    scroll_target_y = ...
    show_vertical_scrollbar: Reactive[bool] = ...
    show_horizontal_scrollbar: Reactive[bool] = ...
    border_title = ...
    border_subtitle = ...
    _sort_order: ClassVar[int] = ...
    _PSEUDO_CLASSES: ClassVar[dict[str, Callable[[Widget], bool]]] = ...
    def __init__(self, *children: Widget, name: str | None = ..., id: str | None = ..., classes: str | None = ..., disabled: bool = ..., markup: bool = ...) -> None:
        """Initialize a Widget.

        Args:
            *children: Child widgets.
            name: The name of the widget.
            id: The ID of the widget in the DOM.
            classes: The CSS classes for the widget.
            disabled: Whether the widget is disabled or not.
            markup: Enable content markup?
        """
        ...
    
    @property
    def is_mounted(self) -> bool:
        """Check if this widget is mounted."""
        ...
    
    @property
    def siblings(self) -> list[Widget]:
        """Get the widget's siblings (self is removed from the return list).

        Returns:
            A list of siblings.
        """
        ...
    
    @property
    def visible_siblings(self) -> list[Widget]:
        """A list of siblings which will be shown.

        Returns:
            List of siblings.
        """
        ...
    
    @property
    def allow_vertical_scroll(self) -> bool:
        """Check if vertical scroll is permitted.

        May be overridden if you want different logic regarding allowing scrolling.
        """
        ...
    
    @property
    def allow_horizontal_scroll(self) -> bool:
        """Check if horizontal scroll is permitted.

        May be overridden if you want different logic regarding allowing scrolling.
        """
        ...
    
    @property
    def allow_maximize(self) -> bool:
        """Check if the widget may be maximized.

        Returns:
            `True` if the widget may be maximized, or `False` if it should not be maximized.
        """
        ...
    
    @property
    def offset(self) -> Offset:
        """Widget offset from origin.

        Returns:
            Relative offset.
        """
        ...
    
    @offset.setter
    def offset(self, offset: tuple[int, int]) -> None:
        ...
    
    @property
    def opacity(self) -> float:
        """Total opacity of widget."""
        ...
    
    @property
    def is_anchored(self) -> bool:
        """Is this widget anchored?

        See [anchor()][textual.widget.Widget.anchor] for an explanation of anchoring.

        """
        ...
    
    @property
    def is_mouse_over(self) -> bool:
        """Is the mouse currently over this widget?

        Note this will be `True` if the mouse pointer is within the widget's region, even if
        the mouse pointer is not directly over the widget (there could be another widget between
        the mouse pointer and self).

        """
        ...
    
    @property
    def is_maximized(self) -> bool:
        """Is this widget maximized?"""
        ...
    
    @property
    def is_in_maximized_view(self) -> bool:
        """Is this widget, or a parent maximized?"""
        ...
    
    @property
    def text_selection(self) -> Selection | None:
        """Text selection information, or `None` if no text is selected in this widget."""
        ...
    
    @classmethod
    def get_common_ancestor(cls, widget1: Widget, widget2: Widget, *, default: Widget | None = ...) -> Widget:
        """Get a common ancestors to both widgets.

        Raises:
            ValueError: If there is no common ancestor and `default` is not provided (will not occur if both widgets are attached to the same DOM).

        Args:
            widget1: A Widget.
            widget2: A second widgets.
            default: A widget to return if no common ancestor is found.

        Returns:
            A common ancestor widgets.
        """
        ...
    
    def focus_on_click(self) -> bool:
        """Automatically focus the widget on click?

        Implement this if you want to change the default click to focus behavior.
        The default will return the classvar `FOCUS_ON_CLICK`.

        Returns:
            `True` if Textual should set focus automatically on a click, or `False` if it shouldn't.
        """
        ...
    
    def get_line_filters(self) -> Sequence[LineFilter]:
        """Get the line filters enabled for this widget.

        Returns:
            A sequence of [LineFilter][textual.filters.LineFilter] instances.
        """
        ...
    
    def preflight_checks(self) -> None:
        """Called in debug mode to do preflight checks.

        This is used by Textual to log some common errors, but you could implement this
        in custom widgets to perform additional checks.

        """
        ...
    
    def pre_render(self) -> None:
        """Called prior to rendering.

        If you implement this in a subclass, be sure to call the base class method via super.

        """
        ...
    
    def process_layout(self, placements: list[WidgetPlacement]) -> list[WidgetPlacement]:
        """A hook to allow for the manipulation of widget placements before rendering.

        You could use this as a way to modify the positions / margins of widgets if your requirement is
        not supported in TCSS. In practice, this method is rarely needed!

        Args:
            placements: A list of [`WidgetPlacement`][textual.layout.WidgetPlacement] objects.

        Returns:
            A new list of placements.
        """
        ...
    
    def anchor(self, anchor: bool = ...) -> None:
        """Anchor a scrollable widget.

        An anchored widget will stay scrolled the bottom when new content is added, until
        the user moves the scroll position.

        Args:
            anchor: Anchor the widget if `True`, clear the anchor if `False`.

        """
        ...
    
    def release_anchor(self) -> None:
        """Release the [anchor][textual.widget.Widget].

        If a widget is anchored, releasing the anchor will allow the user to scroll as normal.

        """
        ...
    
    @property
    def tooltip(self) -> VisualType | None:
        """Tooltip for the widget, or `None` for no tooltip."""
        ...
    
    @tooltip.setter
    def tooltip(self, tooltip: VisualType | None):
        ...
    
    def with_tooltip(self, tooltip: Visual | RenderableType | None) -> Self:
        """Chainable method to set a tooltip.

        Example:
            ```python
            def compose(self) -> ComposeResult:
                yield Label("Hello").with_tooltip("A greeting")
            ```

        Args:
            tooltip: New tooltip, or `None` to clear the tooltip.

        Returns:
            Self.
        """
        ...
    
    def allow_focus(self) -> bool:
        """Check if the widget is permitted to focus.

        The base class returns [`can_focus`][textual.widget.Widget.can_focus].
        This method may be overridden if additional logic is required.

        Returns:
            `True` if the widget may be focused, or `False` if it may not be focused.
        """
        ...
    
    def allow_focus_children(self) -> bool:
        """Check if a widget's children may be focused.

        The base class returns [`can_focus_children`][textual.widget.Widget.can_focus_children].
        This method may be overridden if additional logic is required.

        Returns:
            `True` if the widget's children may be focused, or `False` if the widget's children may not be focused.
        """
        ...
    
    def compose_add_child(self, widget: Widget) -> None:
        """Add a node to children.

        This is used by the compose process when it adds children.
        There is no need to use it directly, but you may want to override it in a subclass
        if you want children to be attached to a different node.

        Args:
            widget: A Widget to add.
        """
        ...
    
    @property
    def is_disabled(self) -> bool:
        """Is the widget disabled either because `disabled=True` or an ancestor has `disabled=True`."""
        ...
    
    @property
    def has_focus_within(self) -> bool:
        """Are any descendants focused?"""
        ...
    
    @property
    def first_of_type(self) -> bool:
        """Is this the first widget of its type in its siblings?"""
        ...
    
    @property
    def last_of_type(self) -> bool:
        """Is this the last widget of its type in its siblings?"""
        ...
    
    @property
    def first_child(self) -> bool:
        """Is this the first widget in its siblings?"""
        ...
    
    @property
    def last_child(self) -> bool:
        """Is this the last widget in its siblings?"""
        ...
    
    @property
    def is_odd(self) -> bool:
        """Is this widget at an oddly numbered position within its siblings?"""
        ...
    
    @property
    def is_even(self) -> bool:
        """Is this widget at an evenly numbered position within its siblings?"""
        ...
    
    def __enter__(self) -> Self:
        """Use as context manager when composing."""
        ...
    
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> None:
        """Exit compose context manager."""
        ...
    
    def clear_cached_dimensions(self) -> None:
        """Clear cached results of `get_content_width` and `get_content_height`.

        Call if the widget's renderable changes size after the widget has been created.

        !!! note

            This is not required if you are extending [`Static`][textual.widgets.Static].

        """
        ...
    
    def get_loading_widget(self) -> Widget:
        """Get a widget to display a loading indicator.

        The default implementation will defer to App.get_loading_widget.

        Returns:
            A widget in place of this widget to indicate a loading.
        """
        ...
    
    def set_loading(self, loading: bool) -> None:
        """Set or reset the loading state of this widget.

        A widget in a loading state will display a `LoadingIndicator` or a custom widget
        set through overriding the `get_loading_widget` method.

        Args:
            loading: `True` to put the widget into a loading state, or `False` to reset the loading state.
        """
        ...
    
    ExpectType = TypeVar("ExpectType", bound="Widget")
    if TYPE_CHECKING:
        @overload
        def get_child_by_id(self, id: str) -> Widget:
            ...
        
        @overload
        def get_child_by_id(self, id: str, expect_type: type[ExpectType]) -> ExpectType:
            ...
        
    def get_child_by_id(self, id: str, expect_type: type[ExpectType] | None = ...) -> ExpectType | Widget:
        """Return the first child (immediate descendent) of this node with the given ID.

        Args:
            id: The ID of the child.
            expect_type: Require the object be of the supplied type, or None for any type.

        Returns:
            The first child of this node with the ID.

        Raises:
            NoMatches: if no children could be found for this ID
            WrongType: if the wrong type was found.
        """
        ...
    
    if TYPE_CHECKING:
        @overload
        def get_widget_by_id(self, id: str) -> Widget:
            ...
        
        @overload
        def get_widget_by_id(self, id: str, expect_type: type[ExpectType]) -> ExpectType:
            ...
        
    def get_widget_by_id(self, id: str, expect_type: type[ExpectType] | None = ...) -> ExpectType | Widget:
        """Return the first descendant widget with the given ID.

        Performs a depth-first search rooted at this widget.

        Args:
            id: The ID to search for in the subtree.
            expect_type: Require the object be of the supplied type, or None for any type.

        Returns:
            The first descendant encountered with this ID.

        Raises:
            NoMatches: if no children could be found for this ID.
            WrongType: if the wrong type was found.
        """
        ...
    
    def get_child_by_type(self, expect_type: type[ExpectType]) -> ExpectType:
        """Get the first immediate child of a given type.

        Only returns exact matches, and so will not match subclasses of the given type.

        Args:
            expect_type: The type of the child to search for.

        Raises:
            NoMatches: If no matching child is found.

        Returns:
            The first immediate child widget with the expected type.
        """
        ...
    
    def get_component_rich_style(self, *names: str, partial: bool = ..., default: Style | None = ...) -> Style:
        """Get a *Rich* style for a component.

        Args:
            names: Names of components.
            partial: Return a partial style (not combined with parent).
            default: A Style to return if any component style doesn't exist.

        Raises:
            KeyError: If a component style doesn't exist, and no `default` is provided.

        Returns:
            A Rich style object.
        """
        ...
    
    def get_visual_style(self, *component_classes: str, partial: bool = ...) -> VisualStyle:
        """Get the visual style for the widget, including any component styles.

        Args:
            component_classes: Optional component styles.
            partial: Return a partial style (not combined with parent).

        Returns:
            A Visual style instance.

        """
        ...
    
    @overload
    def render_str(self, text_content: str) -> Content:
        ...
    
    @overload
    def render_str(self, text_content: Content) -> Content:
        ...
    
    def render_str(self, text_content: str | Content) -> Content:
        """Convert str into a [Content][textual.content.Content] instance.

        If you pass in an existing Content instance it will be returned unaltered.

        Args:
            text_content: Content or str.

        Returns:
            Content object.
        """
        ...
    
    def arrange(self, size: Size, optimal: bool = ...) -> DockArrangeResult:
        """Arrange child widgets.

        This method is best left alone, unless you have a deep understanding of what it does.

        Args:
            size: Size of container.
            optimal: Whether fr units should expand the widget (`False`) or avoid expanding the widget (`True`).

        Returns:
            Widget locations.
        """
        ...
    
    def mount(self, *widgets: Widget, before: int | str | Widget | None = ..., after: int | str | Widget | None = ...) -> AwaitMount:
        """Mount widgets below this widget (making this widget a container).

        Args:
            *widgets: The widget(s) to mount.
            before: Optional location to mount before. An `int` is the index
                of the child to mount before, a `str` is a `query_one` query to
                find the widget to mount before.
            after: Optional location to mount after. An `int` is the index
                of the child to mount after, a `str` is a `query_one` query to
                find the widget to mount after.

        Returns:
            An awaitable object that waits for widgets to be mounted.

        Raises:
            MountError: If there is a problem with the mount request.

        Note:
            Only one of ``before`` or ``after`` can be provided. If both are
            provided a ``MountError`` will be raised.
        """
        ...
    
    def mount_all(self, widgets: Iterable[Widget], *, before: int | str | Widget | None = ..., after: int | str | Widget | None = ...) -> AwaitMount:
        """Mount widgets from an iterable.

        Args:
            widgets: An iterable of widgets.
            before: Optional location to mount before. An `int` is the index
                of the child to mount before, a `str` is a `query_one` query to
                find the widget to mount before.
            after: Optional location to mount after. An `int` is the index
                of the child to mount after, a `str` is a `query_one` query to
                find the widget to mount after.

        Returns:
            An awaitable object that waits for widgets to be mounted.

        Raises:
            MountError: If there is a problem with the mount request.

        Note:
            Only one of `before` or `after` can be provided. If both are
            provided a `MountError` will be raised.
        """
        ...
    
    def mount_compose(self, compose_result: ComposeResult, *, before: int | str | Widget | None = ..., after: int | str | Widget | None = ...) -> AwaitMount:
        """Mount widgets from the result of a compose method.

        Example:
        ```python
            def on_key(self, event:events.Key) -> None:

                def add_key(key:str) -> ComposeResult:
                    '''Compose key information widgets'''
                    with containers.HorizontalGroup():
                        yield Label("You pressed:")
                        yield Label(key)

                self.mount_compose(add_key(event.key))

        ```

        Args:
            compose_result: The result of a compose method.
            before: Optional location to mount before. An `int` is the index
                of the child to mount before, a `str` is a `query_one` query to
                find the widget to mount before.
            after: Optional location to mount after. An `int` is the index
                of the child to mount after, a `str` is a `query_one` query to
                find the widget to mount after.

        Returns:
            An awaitable object that waits for widgets to be mounted.

        Raises:
            MountError: If there is a problem with the mount request.

        Note:
            Only one of `before` or `after` can be provided. If both are
            provided a `MountError` will be raised.
        """
        ...
    
    if TYPE_CHECKING:
        @overload
        def move_child(self, child: int | Widget, *, before: int | Widget, after: None = ...) -> None:
            ...
        
        @overload
        def move_child(self, child: int | Widget, *, after: int | Widget, before: None = ...) -> None:
            ...
        
    def move_child(self, child: int | Widget, *, before: int | Widget | None = ..., after: int | Widget | None = ...) -> None:
        """Move a child widget within its parent's list of children.

        Args:
            child: The child widget to move.
            before: Child widget or location index to move before.
            after: Child widget or location index to move after.

        Raises:
            WidgetError: If there is a problem with the child or target.

        Note:
            Only one of `before` or `after` can be provided. If neither
            or both are provided a `WidgetError` will be raised.
        """
        ...
    
    def compose(self) -> ComposeResult:
        """Called by Textual to create child widgets.

        This method is called when a widget is mounted or by setting `recompose=True` when
        calling [`refresh()`][textual.widget.Widget.refresh].

        Note that you don't typically need to explicitly call this method.

        Example:
            ```python
            def compose(self) -> ComposeResult:
                yield Header()
                yield Label("Press the button below:")
                yield Button()
                yield Footer()
            ```
        """
        ...
    
    async def recompose(self) -> None:
        """Recompose the widget.

        Recomposing will remove children and call `self.compose` again to remount.
        """
        ...
    
    def get_content_width(self, container: Size, viewport: Size) -> int:
        """Called by textual to get the width of the content area. May be overridden in a subclass.

        Args:
            container: Size of the container (immediate parent) widget.
            viewport: Size of the viewport.

        Returns:
            The optimal width of the content.
        """
        ...
    
    def get_content_height(self, container: Size, viewport: Size, width: int) -> int:
        """Called by Textual to get the height of the content area. May be overridden in a subclass.

        Args:
            container: Size of the container (immediate parent) widget.
            viewport: Size of the viewport.
            width: Width of renderable.

        Returns:
            The height of the content.
        """
        ...
    
    def watch_hover_style(self, previous_hover_style: Style, hover_style: Style) -> None:
        ...
    
    def watch_scroll_x(self, old_value: float, new_value: float) -> None:
        ...
    
    def watch_scroll_y(self, old_value: float, new_value: float) -> None:
        ...
    
    def validate_scroll_x(self, value: float) -> float:
        ...
    
    def validate_scroll_target_x(self, value: float) -> float:
        ...
    
    def validate_scroll_y(self, value: float) -> float:
        ...
    
    def validate_scroll_target_y(self, value: float) -> float:
        ...
    
    @property
    def max_scroll_x(self) -> int:
        """The maximum value of `scroll_x`."""
        ...
    
    @property
    def max_scroll_y(self) -> int:
        """The maximum value of `scroll_y`."""
        ...
    
    @property
    def is_vertical_scroll_end(self) -> bool:
        """Is the vertical scroll position at the maximum?"""
        ...
    
    @property
    def is_horizontal_scroll_end(self) -> bool:
        """Is the horizontal scroll position at the maximum?"""
        ...
    
    @property
    def is_vertical_scrollbar_grabbed(self) -> bool:
        """Is the user dragging the vertical scrollbar?"""
        ...
    
    @property
    def is_horizontal_scrollbar_grabbed(self) -> bool:
        """Is the user dragging the vertical scrollbar?"""
        ...
    
    @property
    def scrollbar_corner(self) -> ScrollBarCorner:
        """The scrollbar corner.

        Note:
            This will *create* a scrollbar corner if one doesn't exist.

        Returns:
            ScrollBarCorner Widget.
        """
        ...
    
    @property
    def vertical_scrollbar(self) -> ScrollBar:
        """The vertical scrollbar (create if necessary).

        Note:
            This will *create* a scrollbar if one doesn't exist.

        Returns:
            ScrollBar Widget.
        """
        ...
    
    @property
    def horizontal_scrollbar(self) -> ScrollBar:
        """The horizontal scrollbar.

        Note:
            This will *create* a scrollbar if one doesn't exist.

        Returns:
            ScrollBar Widget.
        """
        ...
    
    @property
    def scrollbars_enabled(self) -> tuple[bool, bool]:
        """A tuple of booleans that indicate if scrollbars are enabled.

        Returns:
            A tuple of (<vertical scrollbar enabled>, <horizontal scrollbar enabled>)
        """
        ...
    
    @property
    def scrollbars_space(self) -> tuple[int, int]:
        """The number of cells occupied by scrollbars for width and height"""
        ...
    
    @property
    def scrollbar_size_vertical(self) -> int:
        """Get the width used by the *vertical* scrollbar.

        Returns:
            Number of columns in the vertical scrollbar.
        """
        ...
    
    @property
    def scrollbar_size_horizontal(self) -> int:
        """Get the height used by the *horizontal* scrollbar.

        Returns:
            Number of rows in the horizontal scrollbar.
        """
        ...
    
    @property
    def scrollbar_gutter(self) -> Spacing:
        """Spacing required to fit scrollbar(s).

        Returns:
            Scrollbar gutter spacing.
        """
        ...
    
    @property
    def gutter(self) -> Spacing:
        """Spacing for padding / border / scrollbars.

        Returns:
            Additional spacing around content area.
        """
        ...
    
    @property
    def size(self) -> Size:
        """The size of the content area.

        Returns:
            Content area size.
        """
        ...
    
    @property
    def scrollable_size(self) -> Size:
        """The size of the scrollable content.

        Returns:
            Scrollable content size.
        """
        ...
    
    @property
    def outer_size(self) -> Size:
        """The size of the widget (including padding and border).

        Returns:
            Outer size.
        """
        ...
    
    @property
    def container_size(self) -> Size:
        """The size of the container (parent widget).

        Returns:
            Container size.
        """
        ...
    
    @property
    def content_region(self) -> Region:
        """Gets an absolute region containing the content (minus padding and border).

        Returns:
            Screen region that contains a widget's content.
        """
        ...
    
    @property
    def scrollable_content_region(self) -> Region:
        """Gets an absolute region containing the scrollable content (minus padding, border, and scrollbars).

        Returns:
            Screen region that contains a widget's content.
        """
        ...
    
    @property
    def content_offset(self) -> Offset:
        """An offset from the Widget origin where the content begins.

        Returns:
            Offset from widget's origin.
        """
        ...
    
    @property
    def content_size(self) -> Size:
        """The size of the content area.

        Returns:
            Content area size.
        """
        ...
    
    @property
    def region(self) -> Region:
        """The region occupied by this widget, relative to the Screen.

        Returns:
            Region within screen occupied by widget.
        """
        ...
    
    @property
    def dock_gutter(self) -> Spacing:
        """Space allocated to docks in the parent.

        Returns:
            Space to be subtracted from scrollable area.
        """
        ...
    
    @property
    def container_viewport(self) -> Region:
        """The viewport region (parent window).

        Returns:
            The region that contains this widget.
        """
        ...
    
    @property
    def virtual_region(self) -> Region:
        """The widget region relative to its container (which may not be visible,
        depending on scroll offset).


        Returns:
            The virtual region.
        """
        ...
    
    @property
    def window_region(self) -> Region:
        """The region within the scrollable area that is currently visible.

        Returns:
            New region.
        """
        ...
    
    @property
    def virtual_region_with_margin(self) -> Region:
        """The widget region relative to its container (*including margin*), which may not be visible,
        depending on the scroll offset.

        Returns:
            The virtual region of the Widget, inclusive of its margin.
        """
        ...
    
    @property
    def focusable(self) -> bool:
        """Can this widget currently be focused?"""
        ...
    
    @property
    def scroll_offset(self) -> Offset:
        """Get the current scroll offset.

        Returns:
            Offset a container has been scrolled by.
        """
        ...
    
    @property
    def container_scroll_offset(self) -> Offset:
        """The scroll offset the nearest container ancestor."""
        ...
    
    @property
    def is_on_screen(self) -> bool:
        """Check if the node was displayed in the last screen update."""
        ...
    
    def animate(self, attribute: str, value: float | Animatable, *, final_value: object = ..., duration: float | None = ..., speed: float | None = ..., delay: float = ..., easing: EasingFunction | str = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ...) -> None:
        """Animate an attribute.

        Args:
            attribute: Name of the attribute to animate.
            value: The value to animate to.
            final_value: The final value of the animation. Defaults to `value` if not set.
            duration: The duration (in seconds) of the animation.
            speed: The speed of the animation.
            delay: A delay (in seconds) before the animation starts.
            easing: An easing method.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
        """
        ...
    
    async def stop_animation(self, attribute: str, complete: bool = ...) -> None:
        """Stop an animation on an attribute.

        Args:
            attribute: Name of the attribute whose animation should be stopped.
            complete: Should the animation be set to its final value?

        Note:
            If there is no animation scheduled or running, this is a no-op.
        """
        ...
    
    @property
    def layout(self) -> Layout:
        """Get the layout object if set in styles, or a default layout.

        Returns:
            A layout object.
        """
        ...
    
    @property
    def is_container(self) -> bool:
        """Is this widget a container (contains other widgets)?"""
        ...
    
    @property
    def is_scrollable(self) -> bool:
        """Can this widget be scrolled?"""
        ...
    
    @property
    def is_scrolling(self) -> bool:
        """Is this widget currently scrolling?"""
        ...
    
    @property
    def layer(self) -> str:
        """Get the name of this widgets layer.

        Returns:
            Name of layer.
        """
        ...
    
    @property
    def layers(self) -> tuple[str, ...]:
        """Layers of from parent.

        Returns:
            Tuple of layer names.
        """
        ...
    
    @property
    def link_style(self) -> Style:
        """Style of links.

        Returns:
            Rich style.
        """
        ...
    
    @property
    def link_style_hover(self) -> Style:
        """Style of links underneath the mouse cursor.

        Returns:
            Rich Style.
        """
        ...
    
    @property
    def select_container(self) -> Widget:
        """The widget's container used when selecting text..

        Returns:
            A widget which contains this widget.
        """
        ...
    
    @property
    def allow_select(self) -> bool:
        """Check if this widget permits text selection.

        Returns:
            `True` if the widget supports text selection, otherwise `False`.
        """
        ...
    
    def pre_layout(self, layout: Layout) -> None:
        """This method id called prior to a layout operation.

        Implement this method if you want to make updates that should impact
        the layout.

        Args:
            layout: The [Layout][textual.layout.Layout] instance that will be used to arrange this widget's children.

        """
        ...
    
    def set_scroll(self, x: float | None, y: float | None) -> None:
        """Set the scroll position without any validation.

        This is a low-level method for when you want to see the scroll position in the next frame.
        For a more fully featured method, see [`scroll_to`][textual.widget.Widget.scroll_to].

        Args:
            x: Desired `X` coordinate.
            y: Desired `Y` coordinate.
        """
        ...
    
    def scroll_to(self, x: float | None = ..., y: float | None = ..., *, animate: bool = ..., speed: float | None = ..., duration: float | None = ..., easing: EasingFunction | str | None = ..., force: bool = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ..., immediate: bool = ..., release_anchor: bool = ...) -> None:
        """Scroll to a given (absolute) coordinate, optionally animating.

        Args:
            x: X coordinate (column) to scroll to, or `None` for no change.
            y: Y coordinate (row) to scroll to, or `None` for no change.
            animate: Animate to new scroll position.
            speed: Speed of scroll if `animate` is `True`; or `None` to use `duration`.
            duration: Duration of animation, if `animate` is `True` and `speed` is `None`.
            easing: An easing method for the scrolling animation.
            force: Force scrolling even when prohibited by overflow styling.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
            immediate: If `False` the scroll will be deferred until after a screen refresh,
                set to `True` to scroll immediately.
            release_anchor: If `True` call `release_anchor`.

        Note:
            The call to scroll is made after the next refresh.
        """
        ...
    
    def scroll_relative(self, x: float | None = ..., y: float | None = ..., *, animate: bool = ..., speed: float | None = ..., duration: float | None = ..., easing: EasingFunction | str | None = ..., force: bool = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ..., immediate: bool = ...) -> None:
        """Scroll relative to current position.

        Args:
            x: X distance (columns) to scroll, or ``None`` for no change.
            y: Y distance (rows) to scroll, or ``None`` for no change.
            animate: Animate to new scroll position.
            speed: Speed of scroll if `animate` is `True`. Or `None` to use `duration`.
            duration: Duration of animation, if animate is `True` and speed is `None`.
            easing: An easing method for the scrolling animation.
            force: Force scrolling even when prohibited by overflow styling.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
            immediate: If `False` the scroll will be deferred until after a screen refresh,
                set to `True` to scroll immediately.
        """
        ...
    
    def scroll_home(self, *, animate: bool = ..., speed: float | None = ..., duration: float | None = ..., easing: EasingFunction | str | None = ..., force: bool = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ..., immediate: bool = ..., x_axis: bool = ..., y_axis: bool = ...) -> None:
        """Scroll to home position.

        Args:
            animate: Animate scroll.
            speed: Speed of scroll if animate is `True`; or `None` to use duration.
            duration: Duration of animation, if `animate` is `True` and `speed` is `None`.
            easing: An easing method for the scrolling animation.
            force: Force scrolling even when prohibited by overflow styling.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
            immediate: If `False` the scroll will be deferred until after a screen refresh,
                set to `True` to scroll immediately.
            x_axis: Allow scrolling on X axis?
            y_axis: Allow scrolling on Y axis?
        """
        ...
    
    def scroll_end(self, *, animate: bool = ..., speed: float | None = ..., duration: float | None = ..., easing: EasingFunction | str | None = ..., force: bool = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ..., immediate: bool = ..., x_axis: bool = ..., y_axis: bool = ...) -> None:
        """Scroll to the end of the container.

        Args:
            animate: Animate scroll.
            speed: Speed of scroll if `animate` is `True`; or `None` to use `duration`.
            duration: Duration of animation, if `animate` is `True` and `speed` is `None`.
            easing: An easing method for the scrolling animation.
            force: Force scrolling even when prohibited by overflow styling.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
            immediate: If `False` the scroll will be deferred until after a screen refresh,
                set to `True` to scroll immediately.
            x_axis: Allow scrolling on X axis?
            y_axis: Allow scrolling on Y axis?

        """
        ...
    
    def scroll_left(self, *, animate: bool = ..., speed: float | None = ..., duration: float | None = ..., easing: EasingFunction | str | None = ..., force: bool = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ..., immediate: bool = ...) -> None:
        """Scroll one cell left.

        Args:
            animate: Animate scroll.
            speed: Speed of scroll if `animate` is `True`; or `None` to use `duration`.
            duration: Duration of animation, if `animate` is `True` and `speed` is `None`.
            easing: An easing method for the scrolling animation.
            force: Force scrolling even when prohibited by overflow styling.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
            immediate: If `False` the scroll will be deferred until after a screen refresh,
                set to `True` to scroll immediately.
        """
        ...
    
    def scroll_right(self, *, animate: bool = ..., speed: float | None = ..., duration: float | None = ..., easing: EasingFunction | str | None = ..., force: bool = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ..., immediate: bool = ...) -> None:
        """Scroll one cell right.

        Args:
            animate: Animate scroll.
            speed: Speed of scroll if animate is `True`; or `None` to use `duration`.
            duration: Duration of animation, if `animate` is `True` and `speed` is `None`.
            easing: An easing method for the scrolling animation.
            force: Force scrolling even when prohibited by overflow styling.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
            immediate: If `False` the scroll will be deferred until after a screen refresh,
                set to `True` to scroll immediately.
        """
        ...
    
    def scroll_down(self, *, animate: bool = ..., speed: float | None = ..., duration: float | None = ..., easing: EasingFunction | str | None = ..., force: bool = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ..., immediate: bool = ...) -> None:
        """Scroll one line down.

        Args:
            animate: Animate scroll.
            speed: Speed of scroll if `animate` is `True`; or `None` to use `duration`.
            duration: Duration of animation, if `animate` is `True` and `speed` is `None`.
            easing: An easing method for the scrolling animation.
            force: Force scrolling even when prohibited by overflow styling.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
            immediate: If `False` the scroll will be deferred until after a screen refresh,
                set to `True` to scroll immediately.
        """
        ...
    
    def scroll_up(self, *, animate: bool = ..., speed: float | None = ..., duration: float | None = ..., easing: EasingFunction | str | None = ..., force: bool = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ..., immediate: bool = ...) -> None:
        """Scroll one line up.

        Args:
            animate: Animate scroll.
            speed: Speed of scroll if `animate` is `True`; or `None` to use `duration`.
            duration: Duration of animation, if `animate` is `True` and speed is `None`.
            easing: An easing method for the scrolling animation.
            force: Force scrolling even when prohibited by overflow styling.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
            immediate: If `False` the scroll will be deferred until after a screen refresh,
                set to `True` to scroll immediately.
        """
        ...
    
    def scroll_page_up(self, *, animate: bool = ..., speed: float | None = ..., duration: float | None = ..., easing: EasingFunction | str | None = ..., force: bool = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ...) -> None:
        """Scroll one page up.

        Args:
            animate: Animate scroll.
            speed: Speed of scroll if animate is `True`; or `None` to use `duration`.
            duration: Duration of animation, if `animate` is `True` and `speed` is `None`.
            easing: An easing method for the scrolling animation.
            force: Force scrolling even when prohibited by overflow styling.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
        """
        ...
    
    def scroll_page_down(self, *, animate: bool = ..., speed: float | None = ..., duration: float | None = ..., easing: EasingFunction | str | None = ..., force: bool = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ...) -> None:
        """Scroll one page down.

        Args:
            animate: Animate scroll.
            speed: Speed of scroll if animate is `True`; or `None` to use `duration`.
            duration: Duration of animation, if `animate` is `True` and `speed` is `None`.
            easing: An easing method for the scrolling animation.
            force: Force scrolling even when prohibited by overflow styling.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
        """
        ...
    
    def scroll_page_left(self, *, animate: bool = ..., speed: float | None = ..., duration: float | None = ..., easing: EasingFunction | str | None = ..., force: bool = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ...) -> None:
        """Scroll one page left.

        Args:
            animate: Animate scroll.
            speed: Speed of scroll if animate is `True`; or `None` to use `duration`.
            duration: Duration of animation, if `animate` is `True` and `speed` is `None`.
            easing: An easing method for the scrolling animation.
            force: Force scrolling even when prohibited by overflow styling.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
        """
        ...
    
    def scroll_page_right(self, *, animate: bool = ..., speed: float | None = ..., duration: float | None = ..., easing: EasingFunction | str | None = ..., force: bool = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ...) -> None:
        """Scroll one page right.

        Args:
            animate: Animate scroll.
            speed: Speed of scroll if animate is `True`; or `None` to use `duration`.
            duration: Duration of animation, if `animate` is `True` and `speed` is `None`.
            easing: An easing method for the scrolling animation.
            force: Force scrolling even when prohibited by overflow styling.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
        """
        ...
    
    def scroll_to_widget(self, widget: Widget, *, animate: bool = ..., speed: float | None = ..., duration: float | None = ..., easing: EasingFunction | str | None = ..., center: bool = ..., top: bool = ..., origin_visible: bool = ..., force: bool = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ..., immediate: bool = ...) -> bool:
        """Scroll scrolling to bring a widget into view.

        Args:
            widget: A descendant widget.
            animate: `True` to animate, or `False` to jump.
            speed: Speed of scroll if `animate` is `True`; or `None` to use `duration`.
            duration: Duration of animation, if `animate` is `True` and `speed` is `None`.
            easing: An easing method for the scrolling animation.
            top: Scroll widget to top of container.
            origin_visible: Ensure that the top left of the widget is within the window.
            force: Force scrolling even when prohibited by overflow styling.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
            immediate: If `False` the scroll will be deferred until after a screen refresh,
                set to `True` to scroll immediately.

        Returns:
            `True` if any scrolling has occurred in any descendant, otherwise `False`.
        """
        ...
    
    def scroll_to_region(self, region: Region, *, spacing: Spacing | None = ..., animate: bool = ..., speed: float | None = ..., duration: float | None = ..., easing: EasingFunction | str | None = ..., center: bool = ..., top: bool = ..., origin_visible: bool = ..., force: bool = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ..., x_axis: bool = ..., y_axis: bool = ..., immediate: bool = ...) -> Offset:
        """Scrolls a given region into view, if required.

        This method will scroll the least distance required to move `region` fully within
        the scrollable area.

        Args:
            region: A region that should be visible.
            spacing: Optional spacing around the region.
            animate: `True` to animate, or `False` to jump.
            speed: Speed of scroll if `animate` is `True`; or `None` to use `duration`.
            duration: Duration of animation, if `animate` is `True` and `speed` is `None`.
            easing: An easing method for the scrolling animation.
            top: Scroll `region` to top of container.
            origin_visible: Ensure that the top left of the widget is within the window.
            force: Force scrolling even when prohibited by overflow styling.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
            x_axis: Allow scrolling on X axis?
            y_axis: Allow scrolling on Y axis?
            immediate: If `False` the scroll will be deferred until after a screen refresh,
                set to `True` to scroll immediately.

        Returns:
            The distance that was scrolled.
        """
        ...
    
    def scroll_visible(self, animate: bool = ..., *, speed: float | None = ..., duration: float | None = ..., top: bool = ..., easing: EasingFunction | str | None = ..., force: bool = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ..., immediate: bool = ...) -> None:
        """Scroll the container to make this widget visible.

        Args:
            animate: Animate scroll.
            speed: Speed of scroll if animate is `True`; or `None` to use `duration`.
            duration: Duration of animation, if `animate` is `True` and `speed` is `None`.
            top: Scroll to top of container.
            easing: An easing method for the scrolling animation.
            force: Force scrolling even when prohibited by overflow styling.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
            immediate: If `False` the scroll will be deferred until after a screen refresh,
                set to `True` to scroll immediately.
        """
        ...
    
    def scroll_to_center(self, widget: Widget, animate: bool = ..., *, speed: float | None = ..., duration: float | None = ..., easing: EasingFunction | str | None = ..., force: bool = ..., origin_visible: bool = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ..., immediate: bool = ...) -> None:
        """Scroll this widget to the center of self.

        The center of the widget will be scrolled to the center of the container.

        Args:
            widget: The widget to scroll to the center of self.
            animate: Whether to animate the scroll.
            speed: Speed of scroll if animate is `True`; or `None` to use `duration`.
            duration: Duration of animation, if `animate` is `True` and `speed` is `None`.
            easing: An easing method for the scrolling animation.
            force: Force scrolling even when prohibited by overflow styling.
            origin_visible: Ensure that the top left corner of the widget remains visible after the scroll.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
            immediate: If `False` the scroll will be deferred until after a screen refresh,
                set to `True` to scroll immediately.
        """
        ...
    
    def can_view_entire(self, widget: Widget) -> bool:
        """Check if a given widget is *fully* within the current view (scrollable area).

        Note: This doesn't necessarily equate to a widget being visible.
        There are other reasons why a widget may not be visible.

        Args:
            widget: A widget that is a descendant of self.

        Returns:
            `True` if the entire widget is in view, `False` if it is partially visible or not in view.
        """
        ...
    
    def can_view_partial(self, widget: Widget) -> bool:
        """Check if a given widget at least partially visible within the current view (scrollable area).

        Args:
            widget: A widget that is a descendant of self.

        Returns:
            `True` if any part of the widget is visible, `False` if it is outside of the viewable area.
        """
        ...
    
    def __init_subclass__(cls, can_focus: bool | None = ..., can_focus_children: bool | None = ..., inherit_css: bool = ..., inherit_bindings: bool = ...) -> None:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    
    def get_pseudo_class_state(self) -> PseudoClasses:
        """Get an object describing whether each pseudo class is present on this object or not.

        Returns:
            A PseudoClasses object describing the pseudo classes that are present.
        """
        ...
    
    def post_render(self, renderable: RenderableType, base_style: Style) -> ConsoleRenderable:
        """Applies style attributes to the default renderable.

        This method is called by Textual itself.
        It is unlikely you will need to call or implement this method.

        Returns:
            A new renderable.
        """
        ...
    
    def watch_has_focus(self, _has_focus: bool) -> None:
        """Update from CSS if has focus state changes."""
        ...
    
    def watch_disabled(self, disabled: bool) -> None:
        """Update the styles of the widget and its children when disabled is toggled."""
        ...
    
    @property
    def visual_style(self) -> VisualStyle:
        """The widget's current style."""
        ...
    
    def get_selection(self, selection: Selection) -> tuple[str, str] | None:
        """Get the text under the selection.

        !!! note
            Implement this method if are building custom widget. If you just want to get the currently
            selected text, then see [`Screen.get_selected_text`](textual.screen.Screen.get_selected_text)


        Args:
            selection: Selection information.

        Returns:
            Tuple of extracted text and ending (typically "\n" or " "), or `None` if no text could be extracted.
        """
        ...
    
    def selection_updated(self, selection: Selection | None) -> None:
        """Called when the selection is updated.

        Args:
            selection: Selection information or `None` if no selection.
        """
        ...
    
    def render_line(self, y: int) -> Strip:
        """Render a line of content.

        Args:
            y: Y Coordinate of line.

        Returns:
            A rendered line.
        """
        ...
    
    def render_lines(self, crop: Region) -> list[Strip]:
        """Render the widget into lines.

        Args:
            crop: Region within visible area to render.

        Returns:
            A list of list of segments.
        """
        ...
    
    def get_style_at(self, x: int, y: int) -> Style:
        """Get the Rich style in a widget at a given relative offset.

        Args:
            x: X coordinate relative to the widget.
            y: Y coordinate relative to the widget.

        Returns:
            A rich Style object.
        """
        ...
    
    def suppress_click(self) -> None:
        """Suppress a click event.

        This will prevent a [Click][textual.events.Click] event being sent,
        if called after a mouse down event and before the click itself.

        """
        ...
    
    def refresh(self, *regions: Region, repaint: bool = ..., layout: bool = ..., recompose: bool = ...) -> Self:
        """Initiate a refresh of the widget.

        This method sets an internal flag to perform a refresh, which will be done on the
        next idle event. Only one refresh will be done even if this method is called multiple times.

        By default this method will cause the content of the widget to refresh, but not change its size. You can also
        set `layout=True` to perform a layout.

        !!! warning

            It is rarely necessary to call this method explicitly. Updating styles or reactive attributes will
            do this automatically.

        Args:
            *regions: Additional screen regions to mark as dirty.
            repaint: Repaint the widget (will call render() again).
            layout: Also layout widgets in the view.
            recompose: Re-compose the widget (will remove and re-mount children).

        Returns:
            The `Widget` instance.
        """
        ...
    
    def remove(self) -> AwaitRemove:
        """Remove the Widget from the DOM (effectively deleting it).

        Returns:
            An awaitable object that waits for the widget to be removed.
        """
        ...
    
    def remove_children(self, selector: str | type[QueryType] | Iterable[Widget] = ...) -> AwaitRemove:
        """Remove the immediate children of this Widget from the DOM.

        Args:
            selector: A CSS selector or iterable of widgets to remove.

        Returns:
            An awaitable object that waits for the direct children to be removed.
        """
        ...
    
    @asynccontextmanager
    async def batch(self) -> AsyncGenerator[None, None]:
        """Async context manager that combines widget locking and update batching.

        Use this async context manager whenever you want to acquire the widget lock and
        batch app updates at the same time.

        Example:
            ```py
            async with container.batch():
                await container.remove_children(Button)
                await container.mount(Label("All buttons are gone."))
            ```
        """
        ...
    
    def render(self) -> RenderResult:
        """Get [content](/guide/content) for the widget.

        Implement this method in a subclass for custom widgets.

        This method should return [markup](/guide/content#markup), a [Content][textual.content.Content] object, or a [Rich](https://github.com/Textualize/rich) renderable.

        Example:
            ```python
            from textual.app import RenderResult
            from textual.widget import Widget

            class CustomWidget(Widget):
                def render(self) -> RenderResult:
                    return "Welcome to [bold red]Textual[/]!"
            ```

        Returns:
            A string or object to render as the widget's content.
        """
        ...
    
    async def run_action(self, action: str, namespaces: Mapping[str, DOMNode] | None = ...) -> None:
        """Perform a given action, with this widget as the default namespace.

        Args:
            action: Action encoded as a string.
            namespaces: Mapping of namespaces.
        """
        ...
    
    def post_message(self, message: Message) -> bool:
        """Post a message to this widget.

        Args:
            message: Message to post.

        Returns:
            True if the message was posted, False if this widget was closed / closing.
        """
        ...
    
    async def on_prune(self, event: messages.Prune) -> None:
        """Close message loop when asked to prune."""
        ...
    
    def focus(self, scroll_visible: bool = ...) -> Self:
        """Give focus to this widget.

        Args:
            scroll_visible: Scroll parent to make this widget visible.

        Returns:
            The `Widget` instance.
        """
        ...
    
    def blur(self) -> Self:
        """Blur (un-focus) the widget.

        Focus will be moved to the next available widget in the focus chain.

        Returns:
            The `Widget` instance.
        """
        ...
    
    def capture_mouse(self, capture: bool = ...) -> None:
        """Capture (or release) the mouse.

        When captured, mouse events will go to this widget even when the pointer is not directly over the widget.

        Args:
            capture: True to capture or False to release.
        """
        ...
    
    def release_mouse(self) -> None:
        """Release the mouse.

        Mouse events will only be sent when the mouse is over the widget.
        """
        ...
    
    def text_select_all(self) -> None:
        """Select the entire widget."""
        ...
    
    def begin_capture_print(self, stdout: bool = ..., stderr: bool = ...) -> None:
        """Capture text from print statements (or writes to stdout / stderr).

        If printing is captured, the widget will be sent an [`events.Print`][textual.events.Print] message.

        Call [`end_capture_print`][textual.widget.Widget.end_capture_print] to disable print capture.

        Args:
            stdout: Whether to capture stdout.
            stderr: Whether to capture stderr.
        """
        ...
    
    def end_capture_print(self) -> None:
        """End print capture (set with [`begin_capture_print`][textual.widget.Widget.begin_capture_print])."""
        ...
    
    def check_message_enabled(self, message: Message) -> bool:
        """Check if a given message is enabled (allowed to be sent).

        Args:
            message: A message object

        Returns:
            `True` if the message will be sent, or `False` if it is disabled.
        """
        ...
    
    async def broker_event(self, event_name: str, event: events.Event) -> bool:
        ...
    
    def notify_style_update(self) -> None:
        ...
    
    async def handle_key(self, event: events.Key) -> bool:
        ...
    
    async def mount_composed_widgets(self, widgets: list[Widget]) -> None:
        """Called by Textual to mount widgets after compose.

        There is generally no need to implement this method in your application.
        See [Lazy][textual.lazy.Lazy] for a class which uses this method to implement
        *lazy* mounting.

        Args:
            widgets: A list of child widgets.
        """
        ...
    
    def action_scroll_home(self) -> None:
        ...
    
    def action_scroll_end(self) -> None:
        ...
    
    def action_scroll_left(self) -> None:
        ...
    
    def action_scroll_right(self) -> None:
        ...
    
    def action_scroll_up(self) -> None:
        ...
    
    def action_scroll_down(self) -> None:
        ...
    
    def action_page_down(self) -> None:
        ...
    
    def action_page_up(self) -> None:
        ...
    
    def action_page_left(self) -> None:
        ...
    
    def action_page_right(self) -> None:
        ...
    
    def notify(self, message: str, *, title: str = ..., severity: SeverityLevel = ..., timeout: float | None = ..., markup: bool = ...) -> None:
        """Create a notification.

        !!! tip

            This method is thread-safe.

        Args:
            message: The message for the notification.
            title: The title for the notification.
            severity: The severity of the notification.
            timeout: The timeout (in seconds) for the notification, or `None` for default.
            markup: Render the message as content markup?

        See [`App.notify`][textual.app.App.notify] for the full
        documentation for this method.
        """
        ...
    
    def action_notify(self, message: str, title: str = ..., severity: str = ..., markup: bool = ...) -> None:
        ...
    


