"""
This type stub file was generated by pyright.
"""

import enum
import rich.repr
from contextvars import ContextVar
from typing import Awaitable, Callable, Coroutine, Generic, TYPE_CHECKING, TypeVar, Union
from typing_extensions import TypeAlias
from textual.message import Message
from textual.dom import DOMNode

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
active_worker: ContextVar[Worker] = ...
class NoActiveWorker(Exception):
    """There is no active worker."""
    ...


class WorkerError(Exception):
    """A worker related error."""
    ...


class WorkerFailed(WorkerError):
    """The worker raised an exception and did not complete."""
    def __init__(self, error: BaseException) -> None:
        ...
    


class DeadlockError(WorkerError):
    """The operation would result in a deadlock."""
    ...


class WorkerCancelled(WorkerError):
    """The worker was cancelled and did not complete."""
    ...


def get_current_worker() -> Worker:
    """Get the currently active worker.

    Raises:
        NoActiveWorker: If there is no active worker.

    Returns:
        A Worker instance.
    """
    ...

class WorkerState(enum.Enum):
    """A description of the worker's current state."""
    PENDING = ...
    RUNNING = ...
    CANCELLED = ...
    ERROR = ...
    SUCCESS = ...


ResultType = TypeVar("ResultType")
WorkType: TypeAlias = Union[Callable[[], Coroutine[None, None, ResultType]], Callable[[], ResultType], Awaitable[ResultType],]
class _ReprText:
    """Shim to insert a word into the Worker's repr."""
    def __init__(self, text: str) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    


@rich.repr.auto(angular=True)
class Worker(Generic[ResultType]):
    """A class to manage concurrent work (either a task or a thread)."""
    @rich.repr.auto
    class StateChanged(Message, bubble=False, namespace="worker"):
        """The worker state changed."""
        def __init__(self, worker: Worker, state: WorkerState) -> None:
            """Initialize the StateChanged message.

            Args:
                worker: The worker object.
                state: New state.
            """
            ...
        
        def __rich_repr__(self) -> rich.repr.Result:
            ...
        
    
    
    def __init__(self, node: DOMNode, work: WorkType, *, name: str = ..., group: str = ..., description: str = ..., exit_on_error: bool = ..., thread: bool = ...) -> None:
        """Initialize a Worker.

        Args:
            node: The widget, screen, or App that initiated the work.
            work: A callable, coroutine, or other awaitable object to run in the worker.
            name: Name of the worker (short string to help identify when debugging).
            group: The worker group.
            description: Description of the worker (longer string with more details).
            exit_on_error: Exit the app if the worker raises an error. Set to `False` to suppress exceptions.
            thread: Mark the worker as a thread worker.
        """
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    
    @property
    def node(self) -> DOMNode:
        """The node where this worker was run from."""
        ...
    
    @property
    def state(self) -> WorkerState:
        """The current state of the worker."""
        ...
    
    @state.setter
    def state(self, state: WorkerState) -> None:
        """Set the state, and send a message."""
        ...
    
    @property
    def is_cancelled(self) -> bool:
        """Has the work been cancelled?

        Note that cancelled work may still be running.
        """
        ...
    
    @property
    def is_running(self) -> bool:
        """Is the task running?"""
        ...
    
    @property
    def is_finished(self) -> bool:
        """Has the task finished (cancelled, error, or success)?"""
        ...
    
    @property
    def completed_steps(self) -> int:
        """The number of completed steps."""
        ...
    
    @property
    def total_steps(self) -> int | None:
        """The number of total steps, or None if indeterminate."""
        ...
    
    @property
    def progress(self) -> float:
        """Progress as a percentage.

        If the total steps is None, then this will return 0. The percentage will be clamped between 0 and 100.
        """
        ...
    
    @property
    def result(self) -> ResultType | None:
        """The result of the worker, or `None` if there is no result."""
        ...
    
    @property
    def error(self) -> BaseException | None:
        """The exception raised by the worker, or `None` if there was no error."""
        ...
    
    def update(self, completed_steps: int | None = ..., total_steps: int | None = ...) -> None:
        """Update the number of completed steps.

        Args:
            completed_steps: The number of completed seps, or `None` to not change.
            total_steps: The total number of steps, `None` for indeterminate, or -1 to leave unchanged.
        """
        ...
    
    def advance(self, steps: int = ...) -> None:
        """Advance the number of completed steps.

        Args:
            steps: Number of steps to advance.
        """
        ...
    
    async def run(self) -> ResultType:
        """Run the work.

        Implement this method in a subclass, or pass a callable to the constructor.

        Returns:
            Return value of the work.
        """
        ...
    
    def cancel(self) -> None:
        """Cancel the task."""
        ...
    
    async def wait(self) -> ResultType:
        """Wait for the work to complete.

        Raises:
            WorkerFailed: If the Worker raised an exception.
            WorkerCancelled: If the Worker was cancelled before it completed.

        Returns:
            The return value of the work.
        """
        ...
    


