"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import NamedTuple, TYPE_CHECKING, Tuple, overload
from typing_extensions import Literal
from tree_sitter import Node, Query
from textual.geometry import Size

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
Newline = Literal["\r\n", "\n", "\r"]
VALID_NEWLINES = ...
@dataclass
class EditResult:
    """Contains information about an edit that has occurred."""
    end_location: Location
    replaced_text: str
    ...


class DocumentBase(ABC):
    """Describes the minimum functionality a Document implementation must
    provide in order to be used by the TextArea widget."""
    @abstractmethod
    def replace_range(self, start: Location, end: Location, text: str) -> EditResult:
        """Replace the text at the given range.

        Args:
            start: A tuple (row, column) where the edit starts.
            end: A tuple (row, column) where the edit ends.
            text: The text to insert between start and end.

        Returns:
            The new end location after the edit is complete.
        """
        ...
    
    @property
    @abstractmethod
    def text(self) -> str:
        """The text from the document as a string."""
        ...
    
    @property
    @abstractmethod
    def newline(self) -> Newline:
        """Return the line separator used in the document."""
        ...
    
    @property
    @abstractmethod
    def lines(self) -> list[str]:
        """Get the lines of the document as a list of strings.

        The strings should *not* include newline characters. The newline
        character used for the document can be retrieved via the newline
        property.
        """
        ...
    
    @abstractmethod
    def get_line(self, index: int) -> str:
        """Returns the line with the given index from the document.

        This is used in rendering lines, and will be called by the
        TextArea for each line that is rendered.

        Args:
            index: The index of the line in the document.

        Returns:
            The str instance representing the line.
        """
        ...
    
    @abstractmethod
    def get_text_range(self, start: Location, end: Location) -> str:
        """Get the text that falls between the start and end locations.

        Args:
            start: The start location of the selection.
            end: The end location of the selection.

        Returns:
            The text between start (inclusive) and end (exclusive).
        """
        ...
    
    @abstractmethod
    def get_size(self, indent_width: int) -> Size:
        """Get the size of the document.

        The height is generally the number of lines, and the width
        is generally the maximum cell length of all the lines.

        Args:
            indent_width: The width to use for tab characters.

        Returns:
            The Size of the document bounding box.
        """
        ...
    
    def query_syntax_tree(self, query: Query, start_point: tuple[int, int] | None = ..., end_point: tuple[int, int] | None = ...) -> dict[str, list[Node]]:
        """Query the tree-sitter syntax tree.

        The default implementation always returns an empty list.

        To support querying in a subclass, this must be implemented.

        Args:
            query: The tree-sitter Query to perform.
            start_point: The (row, column byte) to start the query at.
            end_point: The (row, column byte) to end the query at.

        Returns:
            A dict mapping captured node names to lists of Nodes with that name.
        """
        ...
    
    def prepare_query(self, query: str) -> Query | None:
        ...
    
    @property
    @abstractmethod
    def line_count(self) -> int:
        """Returns the number of lines in the document."""
        ...
    
    @property
    @abstractmethod
    def start(self) -> Location:
        """Returns the location of the start of the document (0, 0)."""
        ...
    
    @property
    @abstractmethod
    def end(self) -> Location:
        """Returns the location of the end of the document."""
        ...
    
    if TYPE_CHECKING:
        @overload
        def __getitem__(self, line_index: int) -> str:
            ...
        
        @overload
        def __getitem__(self, line_index: slice) -> list[str]:
            ...
        
    @abstractmethod
    def __getitem__(self, line_index: int | slice) -> str | list[str]:
        """Return the content of a line as a string, excluding newline characters.

        Args:
            line_index: The index or slice of the line(s) to retrieve.

        Returns:
            The line or list of lines requested.
        """
        ...
    


class Document(DocumentBase):
    """A document which can be opened in a TextArea."""
    def __init__(self, text: str) -> None:
        ...
    
    @property
    def lines(self) -> list[str]:
        """Get the document as a list of strings, where each string represents a line.

        Newline characters are not included in at the end of the strings.

        The newline character used in this document can be found via the `Document.newline` property.
        """
        ...
    
    @property
    def text(self) -> str:
        """Get the text from the document."""
        ...
    
    @property
    def newline(self) -> Newline:
        """Get the Newline used in this document (e.g. '\r\n', '\n'. etc.)"""
        ...
    
    def get_size(self, tab_width: int) -> Size:
        """The Size of the document, taking into account the tab rendering width.

        Args:
            tab_width: The width to use for tab indents.

        Returns:
            The size (width, height) of the document.
        """
        ...
    
    def replace_range(self, start: Location, end: Location, text: str) -> EditResult:
        """Replace text at the given range.

        This is the only method by which a document may be updated.

        Args:
            start: A tuple (row, column) where the edit starts.
            end: A tuple (row, column) where the edit ends.
            text: The text to insert between start and end.

        Returns:
            The EditResult containing information about the completed
                replace operation.
        """
        ...
    
    def get_text_range(self, start: Location, end: Location) -> str:
        """Get the text that falls between the start and end locations.

        Returns the text between `start` and `end`, including the appropriate
        line separator character as specified by `Document._newline`. Note that
        `_newline` is set automatically to the first line separator character
        found in the document.

        Args:
            start: The start location of the selection.
            end: The end location of the selection.

        Returns:
            The text between start (inclusive) and end (exclusive).
        """
        ...
    
    @property
    def line_count(self) -> int:
        """Returns the number of lines in the document."""
        ...
    
    @property
    def start(self) -> Location:
        """Returns the location of the start of the document (0, 0)."""
        ...
    
    @property
    def end(self) -> Location:
        """Returns the location of the end of the document."""
        ...
    
    def get_index_from_location(self, location: Location) -> int:
        """Given a location, returns the index from the document's text.

        Args:
            location: The location in the document.

        Returns:
            The index in the document's text.
        """
        ...
    
    def get_location_from_index(self, index: int) -> Location:
        """Given a codepoint index in the document's text, returns the corresponding location.

        Args:
            index: The index in the document's text.

        Returns:
            The corresponding location.

        Raises:
            ValueError: If the index is doesn't correspond to a location in the document.
        """
        ...
    
    def get_line(self, index: int) -> str:
        """Returns the line with the given index from the document.

        Args:
            index: The index of the line in the document.

        Returns:
            The string representing the line.
        """
        ...
    
    @overload
    def __getitem__(self, line_index: int) -> str:
        ...
    
    @overload
    def __getitem__(self, line_index: slice) -> list[str]:
        ...
    
    def __getitem__(self, line_index: int | slice) -> str | list[str]:
        """Return the content of a line as a string, excluding newline characters.

        Args:
            line_index: The index or slice of the line(s) to retrieve.

        Returns:
            The line or list of lines requested.
        """
        ...
    


Location = Tuple[int, int]
class Selection(NamedTuple):
    """A range of characters within a document from a start point to the end point.
    The location of the cursor is always considered to be the `end` point of the selection.
    The selection is inclusive of the minimum point and exclusive of the maximum point.
    """
    start: Location = ...
    end: Location = ...
    @classmethod
    def cursor(cls, location: Location) -> Selection:
        """Create a Selection with the same start and end point - a "cursor".

        Args:
            location: The location to create the zero-width Selection.
        """
        ...
    
    @property
    def is_empty(self) -> bool:
        """Return True if the selection has 0 width, i.e. it's just a cursor."""
        ...
    
    def contains_line(self, y: int) -> bool:
        """Check if the given line is within the selection."""
        ...
    


