"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import TYPE_CHECKING
from textual.document._document import EditResult, Location, Selection
from textual.widgets import TextArea

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
@dataclass
class Edit:
    """Implements the Undoable protocol to replace text at some range within a document."""
    text: str
    from_location: Location
    to_location: Location
    maintain_selection_offset: bool
    _original_selection: Selection | None = ...
    _updated_selection: Selection | None = ...
    _edit_result: EditResult | None = ...
    def do(self, text_area: TextArea, record_selection: bool = ...) -> EditResult:
        """Perform the edit operation.

        Args:
            text_area: The `TextArea` to perform the edit on.
            record_selection: If True, record the current selection in the TextArea
                so that it may be restored if this Edit is undone in the future.

        Returns:
            An `EditResult` containing information about the replace operation.
        """
        ...
    
    def undo(self, text_area: TextArea) -> EditResult:
        """Undo the edit operation.

        Looks at the data stored in the edit, and performs the inverse operation of `Edit.do`.

        Args:
            text_area: The `TextArea` to undo the insert operation on.

        Returns:
            An `EditResult` containing information about the replace operation.
        """
        ...
    
    def after(self, text_area: TextArea) -> None:
        """Hook for running code after an Edit has been performed via `Edit.do` *and*
        side effects such as re-wrapping the document and refreshing the display
        have completed.

        For example, we can't record cursor visual offset until we know where the cursor will
        land *after* wrapping has been performed, so we must wait until here to do it.

        Args:
            text_area: The `TextArea` this operation was performed on.
        """
        ...
    
    @property
    def top(self) -> Location:
        """The Location impacted by this edit that is nearest the start of the document."""
        ...
    
    @property
    def bottom(self) -> Location:
        """The Location impacted by this edit that is nearest the end of the document."""
        ...
    


