"""
This type stub file was generated by pyright.
"""

from typing import Iterable, TYPE_CHECKING
from rich.console import Console, ConsoleOptions, RenderResult
from rich.segment import Segment
from textual.color import Color
from textual.screen import Screen

if TYPE_CHECKING:
    ...
class BackgroundScreen:
    """Tints a renderable and removes links / meta."""
    def __init__(self, screen: Screen, color: Color) -> None:
        """Initialize a BackgroundScreen instance.

        Args:
            screen: A Screen instance.
            color: A color (presumably with alpha).
        """
        ...
    
    @classmethod
    def process_segments(cls, segments: Iterable[Segment], color: Color) -> Iterable[Segment]:
        """Apply tint to segments and remove meta + styles

        Args:
            segments: Incoming segments.
            color: Color of tint.

        Returns:
            Segments with applied tint.
        """
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    


