"""
This type stub file was generated by pyright.
"""

from rich.console import Console, ConsoleOptions, RenderResult
from rich.style import StyleType
from textual.color import Gradient

"""
This type stub file was generated by pyright.
"""
class Bar:
    """Thin horizontal bar with a portion highlighted.

    Args:
        highlight_range: The range to highlight.
        highlight_style: The style of the highlighted range of the bar.
        background_style: The style of the non-highlighted range(s) of the bar.
        width: The width of the bar, or `None` to fill available width.
        gradient: Optional gradient object.
    """
    HALF_BAR_LEFT: str = ...
    BAR: str = ...
    HALF_BAR_RIGHT: str = ...
    def __init__(self, highlight_range: tuple[float, float] = ..., highlight_style: StyleType = ..., background_style: StyleType = ..., clickable_ranges: dict[str, tuple[int, int]] | None = ..., width: int | None = ..., gradient: Gradient | None = ...) -> None:
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    


