"""
This type stub file was generated by pyright.
"""

from rich.console import Console, ConsoleOptions, RenderResult
from rich.measure import Measurement
from rich.style import Style, StyleType

DIGITS = ...
DIGITS3X3_BOLD = ...
DIGITS3X3 = ...
class Digits:
    """Renders a 3X3 unicode 'font' for numerical values.

    Args:
        text: Text to display.
        style: Style to apply to the digits.

    """
    REPLACEMENTS = ...
    def __init__(self, text: str, style: StyleType = ...) -> None:
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    
    def render(self, style: Style) -> RenderResult:
        """Render with the given style

        Args:
            style: Rich Style.

        Returns:
            Result of render.
        """
        ...
    
    @classmethod
    def get_width(cls, text: str) -> int:
        """Calculate the width without rendering.

        Args:
            text: Text which may be displayed in the `Digits` widget.

        Returns:
            width of the text (in cells).
        """
        ...
    
    def __rich_measure__(self, console: Console, options: ConsoleOptions) -> Measurement:
        ...
    


