"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from rich.measure import Measurement
from rich.console import Console, ConsoleOptions, RenderResult, RenderableType
from rich.style import StyleType

if TYPE_CHECKING:
    ...
class Styled:
    """A renderable which allows you to apply a style before and after another renderable.
    This can be used to layer styles on top of each other, like a style sandwich. This is used,
    for example, in the DataTable to layer default CSS styles + user renderables (e.g. Text objects
    stored in the cells of the table) + CSS component styles on top of each other."""
    def __init__(self, renderable: RenderableType, pre_style: StyleType, post_style: StyleType) -> None:
        """Construct a Styled.

        Args:
            renderable (RenderableType): Any renderable.
            pre_style (StyleType): A style to apply across the entire renderable.
                Will be applied before the styles from the renderable itself.
            post_style (StyleType): A style to apply across the entire renderable.
                Will be applied after the styles from the renderable itself.
        """
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    
    def __rich_measure__(self, console: Console, options: ConsoleOptions) -> Measurement:
        ...
    


