"""
This type stub file was generated by pyright.
"""

from typing import Iterable
from rich.console import RenderableType
from rich.segment import Segment
from rich.terminal_theme import TerminalTheme
from textual.color import Color

class Tint:
    """Applies a color on top of an existing renderable."""
    def __init__(self, renderable: RenderableType, color: Color) -> None:
        """Wrap a renderable to apply a tint color.

        Args:
            renderable: A renderable.
            color: A color (presumably with alpha).
        """
        ...
    
    @classmethod
    def process_segments(cls, segments: Iterable[Segment], color: Color, ansi_theme: TerminalTheme, background: Color = ...) -> Iterable[Segment]:
        """Apply tint to segments.

        Args:
            segments: Incoming segments.
            color: Color of tint.
            ansi_theme: The TerminalTheme defining how to map ansi colors to hex.
            background: Background color.

        Returns:
            Segments with applied tint.
        """
        ...
    


