"""
This type stub file was generated by pyright.
"""

import rich.repr
from typing import TYPE_CHECKING
from rich.console import ConsoleRenderable, RenderableType
from typing_extensions import Literal, Self
from textual.app import RenderResult
from rich.style import Style
from textual.content import Content, ContentText
from textual.geometry import Size
from textual.message import Message
from textual.reactive import reactive
from textual.widget import Widget

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
ButtonVariant = Literal["default", "primary", "success", "warning", "error"]
_VALID_BUTTON_VARIANTS = ...
class InvalidButtonVariant(Exception):
    """Exception raised if an invalid button variant is used."""
    ...


class Button(Widget, can_focus=True):
    """A simple clickable button.

    Clicking the button will send a [Button.Pressed][textual.widgets.Button.Pressed] message,
    unless the `action` parameter is provided.

    """
    ALLOW_SELECT = ...
    DEFAULT_CSS = ...
    BINDINGS = ...
    label: reactive[ContentText] = ...
    variant = ...
    compact = ...
    flat = ...
    class Pressed(Message):
        """Event sent when a `Button` is pressed and there is no Button action.

        Can be handled using `on_button_pressed` in a subclass of
        [`Button`][textual.widgets.Button] or in a parent widget in the DOM.
        """
        def __init__(self, button: Button) -> None:
            ...
        
        @property
        def control(self) -> Button:
            """An alias for [Pressed.button][textual.widgets.Button.Pressed.button].

            This will be the same value as [Pressed.button][textual.widgets.Button.Pressed.button].
            """
            ...
        
    
    
    def __init__(self, label: ContentText | None = ..., variant: ButtonVariant = ..., *, name: str | None = ..., id: str | None = ..., classes: str | None = ..., disabled: bool = ..., tooltip: RenderableType | None = ..., action: str | None = ..., compact: bool = ..., flat: bool = ...) -> None:
        """Create a Button widget.

        Args:
            label: The text that appears within the button.
            variant: The variant of the button.
            name: The name of the button.
            id: The ID of the button in the DOM.
            classes: The CSS classes of the button.
            disabled: Whether the button is disabled or not.
            tooltip: Optional tooltip.
            action: Optional action to run when clicked.
            compact: Enable compact button style.
            flat: Enable alternative flat look buttons.
        """
        ...
    
    def get_content_width(self, container: Size, viewport: Size) -> int:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    
    def validate_variant(self, variant: str) -> str:
        ...
    
    def watch_variant(self, old_variant: str, variant: str):
        ...
    
    def watch_flat(self, flat: bool) -> None:
        ...
    
    def validate_label(self, label: ContentText) -> Content:
        """Parse markup for self.label"""
        ...
    
    def render(self) -> RenderResult:
        ...
    
    def post_render(self, renderable: RenderableType, base_style: Style) -> ConsoleRenderable:
        ...
    
    def press(self) -> Self:
        """Animate the button and send the [Pressed][textual.widgets.Button.Pressed] message.

        Can be used to simulate the button being pressed by a user.

        Returns:
            The button instance.
        """
        ...
    
    def action_press(self) -> None:
        """Activate a press of the button."""
        ...
    
    @classmethod
    def success(cls, label: ContentText | None = ..., *, name: str | None = ..., id: str | None = ..., classes: str | None = ..., disabled: bool = ..., flat: bool = ...) -> Button:
        """Utility constructor for creating a success Button variant.

        Args:
            label: The text that appears within the button.
            name: The name of the button.
            id: The ID of the button in the DOM.
            classes: The CSS classes of the button.
            disabled: Whether the button is disabled or not.
            flat: Enable alternative flat look buttons.

        Returns:
            A [`Button`][textual.widgets.Button] widget of the 'success'
                [variant][textual.widgets.button.ButtonVariant].
        """
        ...
    
    @classmethod
    def warning(cls, label: ContentText | None = ..., *, name: str | None = ..., id: str | None = ..., classes: str | None = ..., disabled: bool = ..., flat: bool = ...) -> Button:
        """Utility constructor for creating a warning Button variant.

        Args:
            label: The text that appears within the button.
            name: The name of the button.
            id: The ID of the button in the DOM.
            classes: The CSS classes of the button.
            disabled: Whether the button is disabled or not.
            flat: Enable alternative flat look buttons.

        Returns:
            A [`Button`][textual.widgets.Button] widget of the 'warning'
                [variant][textual.widgets.button.ButtonVariant].
        """
        ...
    
    @classmethod
    def error(cls, label: ContentText | None = ..., *, name: str | None = ..., id: str | None = ..., classes: str | None = ..., disabled: bool = ..., flat: bool = ...) -> Button:
        """Utility constructor for creating an error Button variant.

        Args:
            label: The text that appears within the button.
            name: The name of the button.
            id: The ID of the button in the DOM.
            classes: The CSS classes of the button.
            disabled: Whether the button is disabled or not.
            flat: Enable alternative flat look buttons.

        Returns:
            A [`Button`][textual.widgets.Button] widget of the 'error'
                [variant][textual.widgets.button.ButtonVariant].
        """
        ...
    


