"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from textual.app import RenderResult
from textual.geometry import Size
from textual.selection import Selection
from textual.widget import Widget

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
class Digits(Widget):
    """A widget to display numerical values using a 3x3 grid of unicode characters."""
    DEFAULT_CSS = ...
    def __init__(self, value: str = ..., *, name: str | None = ..., id: str | None = ..., classes: str | None = ..., disabled: bool = ...) -> None:
        """Initialize a Digits widget.

        Args:
            value: Value to display in widget.
            name: The name of the widget.
            id: The ID of the widget in the DOM.
            classes: The CSS classes of the widget.
            disabled: Whether the widget is disabled or not.

        """
        ...
    
    @property
    def value(self) -> str:
        """The current value displayed in the Digits."""
        ...
    
    def get_selection(self, selection: Selection) -> str | None:
        ...
    
    def update(self, value: str) -> None:
        """Update the Digits with a new value.

        Args:
            value: New value to display.

        Raises:
            TypeError: If the value isn't a `str`.
        """
        ...
    
    def render(self) -> RenderResult:
        """Render digits."""
        ...
    
    def get_content_width(self, container: Size, viewport: Size) -> int:
        """Called by textual to get the width of the content area.

        Args:
            container: Size of the container (immediate parent) widget.
            viewport: Size of the viewport.

        Returns:
            The optimal width of the content.
        """
        ...
    
    def get_content_height(self, container: Size, viewport: Size, width: int) -> int:
        """Called by Textual to get the height of the content area.

        Args:
            container: Size of the container (immediate parent) widget.
            viewport: Size of the viewport.
            width: Width of renderable.

        Returns:
            The height of the content.
        """
        ...
    


