"""
This type stub file was generated by pyright.
"""

from textual.app import ComposeResult, RenderResult
from textual.content import Content
from textual.events import Click
from textual.reactive import Reactive
from textual.widget import Widget
from textual.widgets import Static

"""
This type stub file was generated by pyright.
"""
class HeaderIcon(Widget):
    """Display an 'icon' on the left of the header."""
    DEFAULT_CSS = ...
    icon = ...
    def on_mount(self) -> None:
        ...
    
    async def on_click(self, event: Click) -> None:
        """Launch the command palette when icon is clicked."""
        ...
    
    def render(self) -> RenderResult:
        """Render the header icon.

        Returns:
            The rendered icon.
        """
        ...
    


class HeaderClockSpace(Widget):
    """The space taken up by the clock on the right of the header."""
    DEFAULT_CSS = ...
    def render(self) -> RenderResult:
        """Render the header clock space.

        Returns:
            The rendered space.
        """
        ...
    


class HeaderClock(HeaderClockSpace):
    """Display a clock on the right of the header."""
    DEFAULT_CSS = ...
    time_format: Reactive[str] = ...
    def render(self) -> RenderResult:
        """Render the header clock.

        Returns:
            The rendered clock.
        """
        ...
    


class HeaderTitle(Static):
    """Display the title / subtitle in the header."""
    DEFAULT_CSS = ...


class Header(Widget):
    """A header widget with icon and clock."""
    DEFAULT_CSS = ...
    DEFAULT_CLASSES = ...
    tall: Reactive[bool] = ...
    icon: Reactive[str] = ...
    time_format: Reactive[str] = ...
    def __init__(self, show_clock: bool = ..., *, name: str | None = ..., id: str | None = ..., classes: str | None = ..., icon: str | None = ..., time_format: str | None = ...) -> None:
        """Initialise the header widget.

        Args:
            show_clock: ``True`` if the clock should be shown on the right of the header.
            name: The name of the header widget.
            id: The ID of the header widget in the DOM.
            classes: The CSS classes of the header widget.
            icon: Single character to use as an icon, or `None` for default.
            time_format: Time format (used by strftime) for clock, or `None` for default.
        """
        ...
    
    def compose(self) -> ComposeResult:
        ...
    
    def watch_tall(self, tall: bool) -> None:
        ...
    
    def format_title(self) -> Content:
        """Format the title and subtitle.

        Defers to [App.format_title][textual.app.App.format_title] by default.
        Override this method if you want to customize how the title is displayed in the header.

        Returns:
            Content for title display.
        """
        ...
    
    @property
    def screen_title(self) -> str:
        """The title that this header will display.

        This depends on [`Screen.title`][textual.screen.Screen.title] and [`App.title`][textual.app.App.title].
        """
        ...
    
    @property
    def screen_sub_title(self) -> str:
        """The sub-title that this header will display.

        This depends on [`Screen.sub_title`][textual.screen.Screen.sub_title] and [`App.sub_title`][textual.app.App.sub_title].
        """
        ...
    


