"""
This type stub file was generated by pyright.
"""

from typing import Literal
from textual.visual import VisualType
from textual.widgets._static import Static

"""
This type stub file was generated by pyright.
"""
LabelVariant = Literal["success", "error", "warning", "primary", "secondary", "accent"]
class Label(Static):
    """A simple label widget for displaying text-oriented renderables."""
    DEFAULT_CSS = ...
    def __init__(self, content: VisualType = ..., *, variant: LabelVariant | None = ..., expand: bool = ..., shrink: bool = ..., markup: bool = ..., name: str | None = ..., id: str | None = ..., classes: str | None = ..., disabled: bool = ...) -> None:
        ...
    


