"""
This type stub file was generated by pyright.
"""

import rich.repr
from dataclasses import dataclass
from typing import ClassVar, Iterable, Sequence, TYPE_CHECKING
from textual.binding import BindingType
from textual.geometry import Region, Size
from textual.message import Message
from textual.reactive import reactive
from textual.scroll_view import ScrollView
from textual.strip import Strip
from textual.visual import VisualType
from typing_extensions import Self, TypeAlias

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
OptionListContent: TypeAlias = "Option | VisualType | None"
class OptionListError(Exception):
    """An error occurred in the option list."""
    ...


class DuplicateID(OptionListError):
    """Raised if a duplicate ID is used when adding options to an option list."""
    ...


class OptionDoesNotExist(OptionListError):
    """Raised when a request has been made for an option that doesn't exist."""
    ...


@rich.repr.auto
class Option:
    """This class holds details of options in the list."""
    def __init__(self, prompt: VisualType, id: str | None = ..., disabled: bool = ...) -> None:
        """Initialise the option.

        Args:
            prompt: The prompt (text displayed) for the option.
            id: An option ID for the option.
            disabled: Disable the option (will be shown grayed out, and will not be selectable).

        """
        ...
    
    @property
    def prompt(self) -> VisualType:
        """The original prompt."""
        ...
    
    @property
    def id(self) -> str | None:
        """Optional ID for the option."""
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    


@dataclass
class _LineCache:
    """Cached line information."""
    lines: list[tuple[int, int]] = ...
    heights: dict[int, int] = ...
    index_to_line: dict[int, int] = ...
    def clear(self) -> None:
        """Reset all caches."""
        ...
    


class OptionList(ScrollView, can_focus=True):
    """A navigable list of options."""
    ALLOW_SELECT = ...
    BINDINGS: ClassVar[list[BindingType]] = ...
    DEFAULT_CSS = ...
    COMPONENT_CLASSES: ClassVar[set[str]] = ...
    highlighted: reactive[int | None] = ...
    _mouse_hovering_over: reactive[int | None] = ...
    compact: reactive[bool] = ...
    class OptionMessage(Message):
        """Base class for all option messages."""
        def __init__(self, option_list: OptionList, option: Option, index: int) -> None:
            """Initialise the option message.

            Args:
                option_list: The option list that owns the option.
                index: The index of the option that the message relates to.
            """
            ...
        
        @property
        def control(self) -> OptionList:
            """The option list that sent the message.

            This is an alias for [`OptionMessage.option_list`][textual.widgets.OptionList.OptionMessage.option_list]
            and is used by the [`on`][textual.on] decorator.
            """
            ...
        
        def __rich_repr__(self) -> rich.repr.Result:
            ...
        
    
    
    class OptionHighlighted(OptionMessage):
        """Message sent when an option is highlighted.

        Can be handled using `on_option_list_option_highlighted` in a subclass of
        `OptionList` or in a parent node in the DOM.
        """
        ...
    
    
    class OptionSelected(OptionMessage):
        """Message sent when an option is selected.

        Can be handled using `on_option_list_option_selected` in a subclass of
        `OptionList` or in a parent node in the DOM.
        """
        ...
    
    
    def __init__(self, *content: OptionListContent, name: str | None = ..., id: str | None = ..., classes: str | None = ..., disabled: bool = ..., markup: bool = ..., compact: bool = ...) -> None:
        """Initialize an OptionList.

        Args:
            *content: Positional arguments become the options.
            name: Name of the OptionList.
            id: The ID of the OptionList in the DOM.
            classes: Initial CSS classes.
            disabled: Disable the widget?
            markup: Strips should be rendered as content markup if `True`, or plain text if `False`.
            compact: Enable compact style?
        """
        ...
    
    @property
    def options(self) -> Sequence[Option]:
        """Sequence of options in the OptionList.

        !!! note "This is read-only"

        """
        ...
    
    @property
    def option_count(self) -> int:
        """The number of options."""
        ...
    
    @property
    def highlighted_option(self) -> Option | None:
        """The currently highlighted option, or `None` if no option is highlighted.

        Returns:
            An Option, or `None`.
        """
        ...
    
    def clear_options(self) -> Self:
        """Clear the content of the option list.

        Returns:
            The `OptionList` instance.
        """
        ...
    
    def set_options(self, options: Iterable[OptionListContent]) -> Self:
        """Set options, potentially clearing existing options.

        Args:
            options: Options to set.

        Returns:
            The `OptionList` instance.
        """
        ...
    
    def add_options(self, new_options: Iterable[OptionListContent]) -> Self:
        """Add new options.

        Args:
            new_options: Content of new options.

        Returns:
            The `OptionList` instance.
        """
        ...
    
    def add_option(self, option: Option | VisualType | None = ...) -> Self:
        """Add a new option to the end of the option list.

        Args:
            option: New option to add, or `None` for a separator.

        Returns:
            The `OptionList` instance.

        Raises:
            DuplicateID: If there is an attempt to use a duplicate ID.
        """
        ...
    
    def get_option(self, option_id: str) -> Option:
        """Get the option with the given ID.

        Args:
            option_id: The ID of the option to get.

        Returns:
            The option with the ID.

        Raises:
            OptionDoesNotExist: If no option has the given ID.
        """
        ...
    
    def get_option_index(self, option_id: str) -> int:
        """Get the index (offset in `self.options`) of the option with the given ID.

        Args:
            option_id: The ID of the option to get the index of.

        Returns:
            The index of the item with the given ID.

        Raises:
            OptionDoesNotExist: If no option has the given ID.
        """
        ...
    
    def get_option_at_index(self, index: int) -> Option:
        """Get the option at the given index.

        Args:
            index: The index of the option to get.

        Returns:
            The option at that index.

        Raises:
            OptionDoesNotExist: If there is no option with the given index.
        """
        ...
    
    def enable_option_at_index(self, index: int) -> Self:
        """Enable the option at the given index.

        Returns:
            The `OptionList` instance.

        Raises:
            OptionDoesNotExist: If there is no option with the given index.
        """
        ...
    
    def disable_option_at_index(self, index: int) -> Self:
        """Disable the option at the given index.

        Returns:
            The `OptionList` instance.

        Raises:
            OptionDoesNotExist: If there is no option with the given index.
        """
        ...
    
    def enable_option(self, option_id: str) -> Self:
        """Enable the option with the given ID.

        Args:
            option_id: The ID of the option to enable.

        Returns:
            The `OptionList` instance.

        Raises:
            OptionDoesNotExist: If no option has the given ID.
        """
        ...
    
    def disable_option(self, option_id: str) -> Self:
        """Disable the option with the given ID.

        Args:
            option_id: The ID of the option to disable.

        Returns:
            The `OptionList` instance.

        Raises:
            OptionDoesNotExist: If no option has the given ID.
        """
        ...
    
    def remove_option(self, option_id: str) -> Self:
        """Remove the option with the given ID.

        Args:
            option_id: The ID of the option to remove.

        Returns:
            The `OptionList` instance.

        Raises:
            OptionDoesNotExist: If no option has the given ID.
        """
        ...
    
    def remove_option_at_index(self, index: int) -> Self:
        """Remove the option at the given index.

        Args:
            index: The index of the option to remove.

        Returns:
            The `OptionList` instance.

        Raises:
            OptionDoesNotExist: If there is no option with the given index.
        """
        ...
    
    def replace_option_prompt(self, option_id: str, prompt: VisualType) -> Self:
        """Replace the prompt of the option with the given ID.

        Args:
            option_id: The ID of the option to replace the prompt of.
            prompt: The new prompt for the option.

        Returns:
            The `OptionList` instance.

        Raises:
            OptionDoesNotExist: If no option has the given ID.
        """
        ...
    
    def replace_option_prompt_at_index(self, index: int, prompt: VisualType) -> Self:
        """Replace the prompt of the option at the given index.

        Args:
            index: The index of the option to replace the prompt of.
            prompt: The new prompt for the option.

        Returns:
            The `OptionList` instance.

        Raises:
            OptionDoesNotExist: If there is no option with the given index.
        """
        ...
    
    def notify_style_update(self) -> None:
        ...
    
    def on_show(self) -> None:
        ...
    
    def on_mount(self) -> None:
        ...
    
    def get_content_width(self, container: Size, viewport: Size) -> int:
        """Get maximum width of options."""
        ...
    
    def get_content_height(self, container: Size, viewport: Size, width: int) -> int:
        """Get height for the given width."""
        ...
    
    def render_lines(self, crop: Region) -> list[Strip]:
        ...
    
    def render_line(self, y: int) -> Strip:
        ...
    
    def validate_highlighted(self, highlighted: int | None) -> int | None:
        """Validate the `highlighted` property value on access."""
        ...
    
    def watch_highlighted(self, highlighted: int | None) -> None:
        """React to the highlighted option having changed."""
        ...
    
    def scroll_to_highlight(self, top: bool = ...) -> None:
        """Scroll to the highlighted option.

        Args:
            top: Ensure highlighted option is at the top of the widget.
        """
        ...
    
    def action_cursor_up(self) -> None:
        """Move the highlight up to the previous enabled option."""
        ...
    
    def action_cursor_down(self) -> None:
        """Move the highlight down to the next enabled option."""
        ...
    
    def action_first(self) -> None:
        """Move the highlight to the first enabled option."""
        ...
    
    def action_last(self) -> None:
        """Move the highlight to the last enabled option."""
        ...
    
    def action_page_up(self):
        """Move the highlight up one page."""
        ...
    
    def action_page_down(self):
        """Move the highlight down one page."""
        ...
    
    def action_select(self) -> None:
        """Select the currently highlighted option.

        If an option is selected then a
        [OptionList.OptionSelected][textual.widgets.OptionList.OptionSelected] will be posted.
        """
        ...
    


