"""
This type stub file was generated by pyright.
"""

from typing import Type
from textual._types import UnusedParameter
from textual.app import ComposeResult, RenderResult
from textual.clock import Clock
from textual.color import Gradient
from textual.reactive import reactive
from textual.renderables.bar import Bar as BarRenderable
from textual.widget import Widget
from textual.widgets import Label

"""
This type stub file was generated by pyright.
"""
UNUSED = ...
class Bar(Widget, can_focus=False):
    """The bar portion of the progress bar."""
    COMPONENT_CLASSES = ...
    DEFAULT_CSS = ...
    percentage: reactive[float | None] = ...
    gradient: reactive[Gradient | None] = ...
    def __init__(self, name: str | None = ..., id: str | None = ..., classes: str | None = ..., disabled: bool = ..., clock: Clock | None = ..., gradient: Gradient | None = ..., bar_renderable: Type[BarRenderable] = ...) -> None:
        """Create a bar for a [`ProgressBar`][textual.widgets.ProgressBar]."""
        ...
    
    def watch_percentage(self, percentage: float | None) -> None:
        """Manage the timer that enables the indeterminate bar animation."""
        ...
    
    def render(self) -> RenderResult:
        """Render the bar with the correct portion filled."""
        ...
    
    def render_indeterminate(self) -> RenderResult:
        """Render a frame of the indeterminate progress bar animation."""
        ...
    


class PercentageStatus(Label):
    """A label to display the percentage status of the progress bar."""
    DEFAULT_CSS = ...
    percentage: reactive[int | None] = ...
    def render(self) -> RenderResult:
        ...
    


class ETAStatus(Label):
    """A label to display the estimated time until completion of the progress bar."""
    DEFAULT_CSS = ...
    eta: reactive[float | None] = ...
    def render(self) -> RenderResult:
        """Render the ETA display."""
        ...
    


class ProgressBar(Widget, can_focus=False):
    """A progress bar widget."""
    DEFAULT_CSS = ...
    progress: reactive[float] = ...
    total: reactive[float | None] = ...
    percentage: reactive[float | None] = ...
    _display_eta: reactive[int | None] = ...
    gradient: reactive[Gradient | None] = ...
    BAR_RENDERABLE: Type[BarRenderable] = ...
    def __init__(self, total: float | None = ..., *, show_bar: bool = ..., show_percentage: bool = ..., show_eta: bool = ..., name: str | None = ..., id: str | None = ..., classes: str | None = ..., disabled: bool = ..., clock: Clock | None = ..., gradient: Gradient | None = ...) -> None:
        """Create a Progress Bar widget.

        The progress bar uses "steps" as the measurement unit.

        Example:
            ```py
            class MyApp(App):
                def compose(self):
                    yield ProgressBar(total=100)

                def key_space(self):
                    self.query_one(ProgressBar).advance(5)
            ```

        Args:
            total: The total number of steps in the progress if known.
            show_bar: Whether to show the bar portion of the progress bar.
            show_percentage: Whether to show the percentage status of the bar.
            show_eta: Whether to show the ETA countdown of the progress bar.
            name: The name of the widget.
            id: The ID of the widget in the DOM.
            classes: The CSS classes for the widget.
            disabled: Whether the widget is disabled or not.
            clock: An optional clock object (leave as default unless testing).
            gradient: An optional Gradient object (will replace CSS styles in the bar).
        """
        ...
    
    def on_mount(self) -> None:
        ...
    
    def compose(self) -> ComposeResult:
        ...
    
    def advance(self, advance: float = ...) -> None:
        """Advance the progress of the progress bar by the given amount.

        Example:
            ```py
            progress_bar.advance(10)  # Advance 10 steps.
            ```

        Args:
            advance: Number of steps to advance progress by.
        """
        ...
    
    def update(self, *, total: None | float | UnusedParameter = ..., progress: float | UnusedParameter = ..., advance: float | UnusedParameter = ...) -> None:
        """Update the progress bar with the given options.

        Example:
            ```py
            progress_bar.update(
                total=200,  # Set new total to 200 steps.
                progress=50,  # Set the progress to 50 (out of 200).
            )
            ```

        Args:
            total: New total number of steps.
            progress: Set the progress to the given number of steps.
            advance: Advance the progress by this number of steps.
        """
        ...
    


