"""
This type stub file was generated by pyright.
"""

from textual.widgets._toggle_button import ToggleButton

"""
This type stub file was generated by pyright.
"""
class RadioButton(ToggleButton):
    """A radio button widget that represents a boolean value.

    Note:
        A `RadioButton` is best used within a [RadioSet][textual.widgets.RadioSet].
    """
    BUTTON_INNER = ...
    class Changed(ToggleButton.Changed):
        """Posted when the value of the radio button changes.

        This message can be handled using an `on_radio_button_changed` method.
        """
        @property
        def radio_button(self) -> RadioButton:
            """The radio button that was changed."""
            ...
        
        @property
        def control(self) -> RadioButton:
            """Alias for [Changed.radio_button][textual.widgets.RadioButton.Changed.radio_button]."""
            ...
        
    
    


