"""
This type stub file was generated by pyright.
"""

import rich.repr
from dataclasses import dataclass
from typing import ClassVar
from textual.app import ComposeResult, RenderResult
from textual.await_complete import AwaitComplete
from textual.binding import BindingType
from textual.content import Content, ContentText
from textual.geometry import Offset
from textual.message import Message
from textual.reactive import reactive
from textual.visual import VisualType
from textual.widget import Widget
from textual.widgets import Static

"""
This type stub file was generated by pyright.
"""
class Underline(Widget):
    """The animated underline beneath tabs."""
    DEFAULT_CSS = ...
    COMPONENT_CLASSES = ...
    highlight_start = ...
    highlight_end = ...
    show_highlight: reactive[bool] = ...
    class Clicked(Message):
        """Inform ancestors the underline was clicked."""
        offset: Offset
        def __init__(self, offset: Offset) -> None:
            ...
        
    
    
    def render(self) -> RenderResult:
        """Render the bar."""
        ...
    


class Tab(Static):
    """A Widget to manage a single tab within a Tabs widget."""
    DEFAULT_CSS = ...
    ALLOW_SELECT = ...
    @dataclass
    class TabMessage(Message):
        """Tab-related messages.

        These are mostly intended for internal use when interacting with `Tabs`.
        """
        tab: Tab
        @property
        def control(self) -> Tab:
            """The tab that is the object of this message.

            This is an alias for the attribute `tab` and is used by the
            [`on`][textual.on] decorator.
            """
            ...
        
    
    
    class Clicked(TabMessage):
        """A tab was clicked."""
        ...
    
    
    class Disabled(TabMessage):
        """A tab was disabled."""
        ...
    
    
    class Enabled(TabMessage):
        """A tab was enabled."""
        ...
    
    
    class Relabelled(TabMessage):
        """A tab was relabelled."""
        ...
    
    
    def __init__(self, label: ContentText, *, id: str | None = ..., classes: str | None = ..., disabled: bool = ...) -> None:
        """Initialise a Tab.

        Args:
            label: The label to use in the tab.
            id: Optional ID for the widget.
            classes: Space separated list of class names.
            disabled: Whether the tab is disabled or not.
        """
        ...
    
    @property
    def label(self) -> Content:
        """The label for the tab."""
        ...
    
    @label.setter
    def label(self, label: ContentText) -> None:
        ...
    
    def update(self, content: VisualType = ...) -> None:
        ...
    
    @property
    def label_text(self) -> str:
        """Undecorated text of the label."""
        ...
    


class Tabs(Widget, can_focus=True):
    """A row of tabs."""
    DEFAULT_CSS = ...
    BINDINGS: ClassVar[list[BindingType]] = ...
    class TabError(Exception):
        """Exception raised when there is an error relating to tabs."""
        ...
    
    
    class TabMessage(Message):
        """Parent class for all messages that have to do with a specific tab."""
        ALLOW_SELECTOR_MATCH = ...
        def __init__(self, tabs: Tabs, tab: Tab) -> None:
            """Initialize event.

            Args:
                tabs: The Tabs widget.
                tab: The tab that is the object of this message.
            """
            ...
        
        @property
        def control(self) -> Tabs:
            """The tabs widget containing the tab that is the object of this message.

            This is an alias for the attribute `tabs` and is used by the
            [`on`][textual.on] decorator.
            """
            ...
        
        def __rich_repr__(self) -> rich.repr.Result:
            ...
        
    
    
    class TabActivated(TabMessage):
        """Sent when a new tab is activated."""
        ...
    
    
    class TabDisabled(TabMessage):
        """Sent when a tab is disabled."""
        ...
    
    
    class TabEnabled(TabMessage):
        """Sent when a tab is enabled."""
        ...
    
    
    class TabHidden(TabMessage):
        """Sent when a tab is hidden."""
        ...
    
    
    class TabShown(TabMessage):
        """Sent when a tab is shown."""
        ...
    
    
    class Cleared(Message):
        """Sent when there are no active tabs.

        This can occur when Tabs are cleared, if all tabs are hidden, or if the
        currently active tab is unset.
        """
        def __init__(self, tabs: Tabs) -> None:
            """Initialize the event.

            Args:
                tabs: The tabs widget.
            """
            ...
        
        @property
        def control(self) -> Tabs:
            """The tabs widget which was cleared.

            This is an alias for [`Cleared.tabs`][textual.widgets.Tabs.Cleared] which
            is used by the [`on`][textual.on] decorator.
            """
            ...
        
        def __rich_repr__(self) -> rich.repr.Result:
            ...
        
    
    
    active: reactive[str] = ...
    def __init__(self, *tabs: Tab | ContentText, active: str | None = ..., name: str | None = ..., id: str | None = ..., classes: str | None = ..., disabled: bool = ...) -> None:
        """Construct a Tabs widget.

        Args:
            *tabs: Positional argument should be explicit Tab objects, or a str or Text.
            active: ID of the tab which should be active on start.
            name: Optional name for the tabs widget.
            id: Optional ID for the widget.
            classes: Optional initial classes for the widget.
            disabled: Whether the widget is disabled or not.
        """
        ...
    
    @property
    def tab_count(self) -> int:
        """Total number of tabs."""
        ...
    
    def add_tab(self, tab: Tab | ContentText, *, before: Tab | str | None = ..., after: Tab | str | None = ...) -> AwaitComplete:
        """Add a new tab to the end of the tab list.

        Args:
            tab: A new tab object, or a label (str or Text).
            before: Optional tab or tab ID to add the tab before.
            after: Optional tab or tab ID to add the tab after.

        Returns:
            An optionally awaitable object that waits for the tab to be mounted and
                internal state to be fully updated to reflect the new tab.

        Raises:
            Tabs.TabError: If there is a problem with the addition request.

        Note:
            Only one of `before` or `after` can be provided. If both are
            provided a `Tabs.TabError` will be raised.
        """
        ...
    
    def clear(self) -> AwaitComplete:
        """Clear all the tabs.

        Returns:
            An awaitable object that waits for the tabs to be removed.
        """
        ...
    
    def get_tab(self, tab_id: str) -> Tab | None:
        """Get a tab from its ID.

        Args:
            tab_id: The tab ID.

        Returns:
            The Tab instance, or `None` if no tab with the given ID.
        """
        ...
    
    def remove_tab(self, tab_or_id: Tab | str | None) -> AwaitComplete:
        """Remove a tab.

        Args:
            tab_or_id: The Tab to remove or its id.

        Returns:
            An optionally awaitable object that waits for the tab to be removed.
        """
        ...
    
    def validate_active(self, active: str) -> str:
        """Check id assigned to active attribute is a valid tab."""
        ...
    
    @property
    def active_tab(self) -> Tab | None:
        """The currently active tab, or None if there are no active tabs."""
        ...
    
    def compose(self) -> ComposeResult:
        ...
    
    def watch_active(self, previously_active: str, active: str) -> None:
        """Handle a change to the active tab."""
        ...
    
    def action_next_tab(self) -> None:
        """Make the next tab active."""
        ...
    
    def action_previous_tab(self) -> None:
        """Make the previous tab active."""
        ...
    
    def disable(self, tab_id: str) -> Tab:
        """Disable the indicated tab.

        Args:
            tab_id: The ID of the [`Tab`][textual.widgets.Tab] to disable.

        Returns:
            The [`Tab`][textual.widgets.Tab] that was targeted.

        Raises:
            TabError: If there are any issues with the request.
        """
        ...
    
    def enable(self, tab_id: str) -> Tab:
        """Enable the indicated tab.

        Args:
            tab_id: The ID of the [`Tab`][textual.widgets.Tab] to enable.

        Returns:
            The [`Tab`][textual.widgets.Tab] that was targeted.

        Raises:
            TabError: If there are any issues with the request.
        """
        ...
    
    def hide(self, tab_id: str) -> Tab:
        """Hide the indicated tab.

        Args:
            tab_id: The ID of the [`Tab`][textual.widgets.Tab] to hide.

        Returns:
            The [`Tab`][textual.widgets.Tab] that was targeted.

        Raises:
            TabError: If there are any issues with the request.
        """
        ...
    
    def show(self, tab_id: str) -> Tab:
        """Show the indicated tab.

        Args:
            tab_id: The ID of the [`Tab`][textual.widgets.Tab] to show.

        Returns:
            The [`Tab`][textual.widgets.Tab] that was targeted.

        Raises:
            TabError: If there are any issues with the request.
        """
        ...
    


