"""
This type stub file was generated by pyright.
"""

from typing import ClassVar
from textual.containers import Container
from textual.content import Content
from textual.notifications import Notification, Notifications
from textual.widgets._static import Static

"""Widgets for showing notification messages in toasts."""
class ToastHolder(Container, inherit_css=False):
    """Container that holds a single toast.

    Used to control the alignment of each of the toasts in the main toast
    container.
    """
    DEFAULT_CSS = ...


class Toast(Static, inherit_css=False):
    """A widget for displaying short-lived notifications."""
    DEFAULT_CSS = ...
    COMPONENT_CLASSES: ClassVar[set[str]] = ...
    DEFAULT_CLASSES = ...
    def __init__(self, notification: Notification) -> None:
        """Initialise the toast.

        Args:
            notification: The notification to show in the toast.
        """
        ...
    
    def render(self) -> Content:
        """Render the toast's content.

        Returns:
            A Rich renderable for the title and content of the Toast.
        """
        ...
    


class ToastRack(Container, inherit_css=False):
    """A container for holding toasts."""
    DEFAULT_CSS = ...
    DEFAULT_CLASSES = ...
    def show(self, notifications: Notifications) -> None:
        """Show the notifications as toasts.

        Args:
            notifications: The notifications to show.
        """
        ...
    


