"""
This type stub file was generated by pyright.
"""

import rich.repr
from dataclasses import dataclass
from typing import ClassVar, Generic, NewType, TYPE_CHECKING, TypeVar
from rich.style import Style
from rich.text import Text, TextType
from textual._immutable_sequence_view import ImmutableSequenceView
from textual.binding import BindingType
from textual.geometry import Region
from textual.message import Message
from textual.scroll_view import ScrollView
from textual.strip import Strip
from typing_extensions import Self, TypeAlias

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
NodeID = NewType("NodeID", int)
TreeDataType = TypeVar("TreeDataType")
EventTreeDataType = TypeVar("EventTreeDataType")
LineCacheKey: TypeAlias = "tuple[int | tuple, ...]"
TOGGLE_STYLE = ...
class RemoveRootError(Exception):
    """Exception raised when trying to remove the root of a [`TreeNode`][textual.widgets.tree.TreeNode]."""
    ...


class UnknownNodeID(Exception):
    """Exception raised when referring to an unknown [`TreeNode`][textual.widgets.tree.TreeNode] ID."""
    ...


class AddNodeError(Exception):
    """Exception raised when there is an error with a request to add a node."""
    ...


@dataclass
class _TreeLine(Generic[TreeDataType]):
    path: list[TreeNode[TreeDataType]]
    last: bool
    @property
    def node(self) -> TreeNode[TreeDataType]:
        """The node associated with this line."""
        ...
    


class TreeNodes(ImmutableSequenceView["TreeNode[TreeDataType]"]):
    """An immutable collection of `TreeNode`."""
    ...


@rich.repr.auto
class TreeNode(Generic[TreeDataType]):
    """An object that represents a "node" in a tree control."""
    def __init__(self, tree: Tree[TreeDataType], parent: TreeNode[TreeDataType] | None, id: NodeID, label: Text, data: TreeDataType | None = ..., *, expanded: bool = ..., allow_expand: bool = ...) -> None:
        """Initialise the node.

        Args:
            tree: The tree that the node is being attached to.
            parent: The parent node that this node is being attached to.
            id: The ID of the node.
            label: The label for the node.
            data: Optional data to associate with the node.
            expanded: Should the node be attached in an expanded state?
            allow_expand: Should the node allow being expanded by the user?
        """
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    
    @property
    def tree(self) -> Tree[TreeDataType]:
        """The tree that this node is attached to."""
        ...
    
    @property
    def children(self) -> TreeNodes[TreeDataType]:
        """The child nodes of a TreeNode."""
        ...
    
    @property
    def siblings(self) -> TreeNodes[TreeDataType]:
        """The siblings of this node (includes self)."""
        ...
    
    @property
    def line(self) -> int:
        """The line number for this node, or -1 if it is not displayed."""
        ...
    
    @property
    def id(self) -> NodeID:
        """The ID of the  node."""
        ...
    
    @property
    def parent(self) -> TreeNode[TreeDataType] | None:
        """The parent of the node."""
        ...
    
    @property
    def next_sibling(self) -> TreeNode[TreeDataType] | None:
        """The next sibling below the node."""
        ...
    
    @property
    def previous_sibling(self) -> TreeNode[TreeDataType] | None:
        """The previous sibling below the node."""
        ...
    
    @property
    def is_expanded(self) -> bool:
        """Is the node expanded?"""
        ...
    
    @property
    def is_collapsed(self) -> bool:
        """Is the node collapsed?"""
        ...
    
    @property
    def is_last(self) -> bool:
        """Is this the last child node of its parent?"""
        ...
    
    @property
    def is_root(self) -> bool:
        """Is this node the root of the tree?"""
        ...
    
    @property
    def allow_expand(self) -> bool:
        """Is this node allowed to expand?"""
        ...
    
    @allow_expand.setter
    def allow_expand(self, allow_expand: bool) -> None:
        ...
    
    def expand(self) -> Self:
        """Expand the node (show its children).

        Returns:
            The `TreeNode` instance.
        """
        ...
    
    def expand_all(self) -> Self:
        """Expand the node (show its children) and all those below it.

        Returns:
            The `TreeNode` instance.
        """
        ...
    
    def collapse(self) -> Self:
        """Collapse the node (hide its children).

        Returns:
            The `TreeNode` instance.
        """
        ...
    
    def collapse_all(self) -> Self:
        """Collapse the node (hide its children) and all those below it.

        Returns:
            The `TreeNode` instance.
        """
        ...
    
    def toggle(self) -> Self:
        """Toggle the node's expanded state.

        Returns:
            The `TreeNode` instance.
        """
        ...
    
    def toggle_all(self) -> Self:
        """Toggle the node's expanded state and make all those below it match.

        Returns:
            The `TreeNode` instance.
        """
        ...
    
    @property
    def label(self) -> TextType:
        """The label for the node."""
        ...
    
    @label.setter
    def label(self, new_label: TextType) -> None:
        ...
    
    def set_label(self, label: TextType) -> None:
        """Set a new label for the node.

        Args:
            label: A ``str`` or ``Text`` object with the new label.
        """
        ...
    
    def add(self, label: TextType, data: TreeDataType | None = ..., *, before: int | TreeNode[TreeDataType] | None = ..., after: int | TreeNode[TreeDataType] | None = ..., expand: bool = ..., allow_expand: bool = ...) -> TreeNode[TreeDataType]:
        """Add a node to the sub-tree.

        Args:
            label: The new node's label.
            data: Data associated with the new node.
            before: Optional index or `TreeNode` to add the node before.
            after: Optional index or `TreeNode` to add the node after.
            expand: Node should be expanded.
            allow_expand: Allow user to expand the node via keyboard or mouse.

        Returns:
            A new Tree node

        Raises:
            AddNodeError: If there is a problem with the addition request.

        Note:
            Only one of `before` or `after` can be provided. If both are
            provided a `AddNodeError` will be raised.
        """
        ...
    
    def add_leaf(self, label: TextType, data: TreeDataType | None = ..., *, before: int | TreeNode[TreeDataType] | None = ..., after: int | TreeNode[TreeDataType] | None = ...) -> TreeNode[TreeDataType]:
        """Add a 'leaf' node (a node that can not expand).

        Args:
            label: Label for the node.
            data: Optional data.
            before: Optional index or `TreeNode` to add the node before.
            after: Optional index or `TreeNode` to add the node after.

        Returns:
            New node.

        Raises:
            AddNodeError: If there is a problem with the addition request.

        Note:
            Only one of `before` or `after` can be provided. If both are
            provided a `AddNodeError` will be raised.
        """
        ...
    
    def remove(self) -> None:
        """Remove this node from the tree.

        Raises:
            RemoveRootError: If there is an attempt to remove the root.
        """
        ...
    
    def remove_children(self) -> None:
        """Remove any child nodes of this node."""
        ...
    
    def refresh(self) -> None:
        """Initiate a refresh (repaint) of this node."""
        ...
    


class Tree(Generic[TreeDataType], ScrollView, can_focus=True):
    """A widget for displaying and navigating data in a tree."""
    ICON_NODE = ...
    ICON_NODE_EXPANDED = ...
    BINDINGS: ClassVar[list[BindingType]] = ...
    ALLOW_SELECT = ...
    COMPONENT_CLASSES: ClassVar[set[str]] = ...
    DEFAULT_CSS = ...
    show_root = ...
    hover_line = ...
    cursor_line = ...
    show_guides = ...
    guide_depth = ...
    auto_expand = ...
    center_scroll = ...
    LINES: dict[str, tuple[str, str, str, str]] = ...
    class NodeCollapsed(Generic[EventTreeDataType], Message):
        """Event sent when a node is collapsed.

        Can be handled using `on_tree_node_collapsed` in a subclass of `Tree` or in a
        parent node in the DOM.
        """
        def __init__(self, node: TreeNode[EventTreeDataType]) -> None:
            ...
        
        @property
        def control(self) -> Tree[EventTreeDataType]:
            """The tree that sent the message."""
            ...
        
    
    
    class NodeExpanded(Generic[EventTreeDataType], Message):
        """Event sent when a node is expanded.

        Can be handled using `on_tree_node_expanded` in a subclass of `Tree` or in a
        parent node in the DOM.
        """
        def __init__(self, node: TreeNode[EventTreeDataType]) -> None:
            ...
        
        @property
        def control(self) -> Tree[EventTreeDataType]:
            """The tree that sent the message."""
            ...
        
    
    
    class NodeHighlighted(Generic[EventTreeDataType], Message):
        """Event sent when a node is highlighted.

        Can be handled using `on_tree_node_highlighted` in a subclass of `Tree` or in a
        parent node in the DOM.
        """
        def __init__(self, node: TreeNode[EventTreeDataType]) -> None:
            ...
        
        @property
        def control(self) -> Tree[EventTreeDataType]:
            """The tree that sent the message."""
            ...
        
    
    
    class NodeSelected(Generic[EventTreeDataType], Message):
        """Event sent when a node is selected.

        Can be handled using `on_tree_node_selected` in a subclass of `Tree` or in a
        parent node in the DOM.
        """
        def __init__(self, node: TreeNode[EventTreeDataType]) -> None:
            ...
        
        @property
        def control(self) -> Tree[EventTreeDataType]:
            """The tree that sent the message."""
            ...
        
    
    
    def __init__(self, label: TextType, data: TreeDataType | None = ..., *, name: str | None = ..., id: str | None = ..., classes: str | None = ..., disabled: bool = ...) -> None:
        """Initialise a Tree.

        Args:
            label: The label of the root node of the tree.
            data: The optional data to associate with the root node of the tree.
            name: The name of the Tree.
            id: The ID of the tree in the DOM.
            classes: The CSS classes of the tree.
            disabled: Whether the tree is disabled or not.
        """
        ...
    
    def add_json(self, json_data: object, node: TreeNode | None = ...) -> None:
        """Adds JSON data to a node.

        Args:
            json_data: An object decoded from JSON.
            node: Node to add data to.

        """
        ...
    
    @property
    def cursor_node(self) -> TreeNode[TreeDataType] | None:
        """The currently selected node, or ``None`` if no selection."""
        ...
    
    @property
    def last_line(self) -> int:
        """The index of the last line."""
        ...
    
    def process_label(self, label: TextType) -> Text:
        """Process a `str` or `Text` value into a label.

        May be overridden in a subclass to change how labels are rendered.

        Args:
            label: Label.

        Returns:
            A Rich Text object.
        """
        ...
    
    def render_label(self, node: TreeNode[TreeDataType], base_style: Style, style: Style) -> Text:
        """Render a label for the given node. Override this to modify how labels are rendered.

        Args:
            node: A tree node.
            base_style: The base style of the widget.
            style: The additional style for the label.

        Returns:
            A Rich Text object containing the label.
        """
        ...
    
    def get_label_width(self, node: TreeNode[TreeDataType]) -> int:
        """Get the width of the nodes label.

        The default behavior is to call `render_label` and return the cell length. This method may be
        overridden in a sub-class if it can be done more efficiently.

        Args:
            node: A node.

        Returns:
            Width in cells.
        """
        ...
    
    def clear(self) -> Self:
        """Clear all nodes under root.

        Returns:
            The `Tree` instance.
        """
        ...
    
    def reset(self, label: TextType, data: TreeDataType | None = ...) -> Self:
        """Clear the tree and reset the root node.

        Args:
            label: The label for the root node.
            data: Optional data for the root node.

        Returns:
            The `Tree` instance.
        """
        ...
    
    def move_cursor(self, node: TreeNode[TreeDataType] | None, animate: bool = ...) -> None:
        """Move the cursor to the given node, or reset cursor.

        Args:
            node: A tree node, or None to reset cursor.
            animate: Enable animation
        """
        ...
    
    def move_cursor_to_line(self, line: int, animate=...) -> None:
        """Move the cursor to the given line.

        Args:
            line: The line number (negative indexes are offsets from the last line).
            animate: Enable scrolling animation.

        Raises:
            IndexError: If the line doesn't exist.
        """
        ...
    
    def select_node(self, node: TreeNode[TreeDataType] | None) -> None:
        """Move the cursor to the given node and select it, or reset cursor.

        Args:
            node: A tree node to move the cursor to and select, or None to reset cursor.
        """
        ...
    
    def unselect(self) -> None:
        """Hide and reset the cursor."""
        ...
    
    def get_node_at_line(self, line_no: int) -> TreeNode[TreeDataType] | None:
        """Get the node for a given line.

        Args:
            line_no: A line number.

        Returns:
            A tree node, or ``None`` if there is no node at that line.
        """
        ...
    
    def get_node_by_id(self, node_id: NodeID) -> TreeNode[TreeDataType]:
        """Get a tree node by its ID.

        Args:
            node_id: The ID of the node to get.

        Returns:
            The node associated with that ID.

        Raises:
            UnknownNodeID: Raised if the `TreeNode` ID is unknown.
        """
        ...
    
    def validate_cursor_line(self, value: int) -> int:
        """Prevent cursor line from going outside of range.

        Args:
            value: The value to test.

        Return:
            A valid version of the given value.
        """
        ...
    
    def validate_guide_depth(self, value: int) -> int:
        """Restrict guide depth to reasonable range.

        Args:
            value: The value to test.

        Return:
            A valid version of the given value.
        """
        ...
    
    def watch_hover_line(self, previous_hover_line: int, hover_line: int) -> None:
        ...
    
    def watch_cursor_line(self, previous_line: int, line: int) -> None:
        ...
    
    def watch_guide_depth(self, guide_depth: int) -> None:
        ...
    
    def watch_show_root(self, show_root: bool) -> None:
        ...
    
    def scroll_to_line(self, line: int, animate: bool = ...) -> None:
        """Scroll to the given line.

        Args:
            line: A line number.
            animate: Enable animation.
        """
        ...
    
    def scroll_to_node(self, node: TreeNode[TreeDataType], animate: bool = ...) -> None:
        """Scroll to the given node.

        Args:
            node: Node to scroll into view.
            animate: Animate scrolling.
        """
        ...
    
    def render_lines(self, crop: Region) -> list[Strip]:
        ...
    
    def render_line(self, y: int) -> Strip:
        ...
    
    def notify_style_update(self) -> None:
        ...
    
    def action_cursor_up(self) -> None:
        """Move the cursor up one node."""
        ...
    
    def action_cursor_down(self) -> None:
        """Move the cursor down one node."""
        ...
    
    def action_page_down(self) -> None:
        """Move the cursor down a page's-worth of nodes."""
        ...
    
    def action_page_up(self) -> None:
        """Move the cursor up a page's-worth of nodes."""
        ...
    
    def action_scroll_home(self) -> None:
        """Move the cursor to the top of the tree."""
        ...
    
    def action_scroll_end(self) -> None:
        """Move the cursor to the bottom of the tree.

        Note:
            Here bottom means vertically, not branch depth.
        """
        ...
    
    def action_toggle_node(self) -> None:
        """Toggle the expanded state of the target node."""
        ...
    
    def action_select_cursor(self) -> None:
        """Cause a select event for the target node.

        Note:
            If `auto_expand` is `True` use of this action on a non-leaf node
            will cause both an expand/collapse event to occur, as well as a
            selected event.
        """
        ...
    
    def action_cursor_parent(self) -> None:
        """Move the cursor to the parent node."""
        ...
    
    def action_cursor_parent_next_sibling(self) -> None:
        """Move the cursor to the parent's next sibling."""
        ...
    
    def action_cursor_previous_sibling(self) -> None:
        """Move the cursor to previous sibling, or to the parent if there are no more siblings."""
        ...
    
    def action_cursor_next_sibling(self) -> None:
        """Move the cursor to the next sibling, or to the paren't sibling if there are no more siblings."""
        ...
    
    def action_toggle_expand_all(self) -> None:
        """Expand or collapse all siblings.

        If all the siblings are collapsed then they will be expanded.
        Otherwise they will all be collapsed.

        """
        ...
    


