"""
This type stub file was generated by pyright.
"""

import rich.repr
from typing import TYPE_CHECKING
from textual.driver import Driver
from textual.message import Message
from textual.app import App

if TYPE_CHECKING:
    ...
@rich.repr.auto(angular=True)
class LinuxDriver(Driver):
    """Powers display and input for Linux / MacOS"""
    def __init__(self, app: App, *, debug: bool = ..., mouse: bool = ..., size: tuple[int, int] | None = ...) -> None:
        """Initialize Linux driver.

        Args:
            app: The App instance.
            debug: Enable debug mode.
            mouse: Enable mouse support.
            size: Initial size of the terminal or `None` to detect.
        """
        ...
    
    @property
    def can_suspend(self) -> bool:
        """Can this driver be suspended?"""
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    
    def write(self, data: str) -> None:
        """Write data to the output device.

        Args:
            data: Raw data.
        """
        ...
    
    def start_application_mode(self): # -> None:
        """Start application mode."""
        ...
    
    def disable_input(self) -> None:
        """Disable further input."""
        ...
    
    def stop_application_mode(self) -> None:
        """Stop application mode, restore state."""
        ...
    
    def close(self) -> None:
        """Perform cleanup."""
        ...
    
    def run_input_thread(self) -> None:
        """Wait for input and dispatch events."""
        ...
    
    def process_message(self, message: Message) -> None:
        ...
    


