"""
This type stub file was generated by pyright.
"""

import threading
from asyncio import AbstractEventLoop
from ctypes import Structure, Union
from ctypes.wintypes import HANDLE
from typing import Callable, IO, List, Optional, TYPE_CHECKING
from textual.events import Event
from textual.app import App

if TYPE_CHECKING:
    ...
KERNEL32 = ...
ENABLE_ECHO_INPUT = ...
ENABLE_EXTENDED_FLAGS = ...
ENABLE_INSERT_MODE = ...
ENABLE_LINE_INPUT = ...
ENABLE_MOUSE_INPUT = ...
ENABLE_PROCESSED_INPUT = ...
ENABLE_QUICK_EDIT_MODE = ...
ENABLE_WINDOW_INPUT = ...
ENABLE_VIRTUAL_TERMINAL_INPUT = ...
ENABLE_PROCESSED_OUTPUT = ...
ENABLE_WRAP_AT_EOL_OUTPUT = ...
ENABLE_VIRTUAL_TERMINAL_PROCESSING = ...
DISABLE_NEWLINE_AUTO_RETURN = ...
ENABLE_LVB_GRID_WORLDWIDE = ...
STD_INPUT_HANDLE = ...
STD_OUTPUT_HANDLE = ...
WAIT_TIMEOUT = ...
GetStdHandle = ...
class COORD(Structure):
    """https://docs.microsoft.com/en-us/windows/console/coord-str"""
    _fields_ = ...


class uChar(Union):
    """https://docs.microsoft.com/en-us/windows/console/key-event-record-str"""
    _fields_ = ...


class KEY_EVENT_RECORD(Structure):
    """https://docs.microsoft.com/en-us/windows/console/key-event-record-str"""
    _fields_ = ...


class MOUSE_EVENT_RECORD(Structure):
    """https://docs.microsoft.com/en-us/windows/console/mouse-event-record-str"""
    _fields_ = ...


class WINDOW_BUFFER_SIZE_RECORD(Structure):
    """https://docs.microsoft.com/en-us/windows/console/window-buffer-size-record-str"""
    _fields_ = ...


class MENU_EVENT_RECORD(Structure):
    """https://docs.microsoft.com/en-us/windows/console/menu-event-record-str"""
    _fields_ = ...


class FOCUS_EVENT_RECORD(Structure):
    """https://docs.microsoft.com/en-us/windows/console/focus-event-record-str"""
    _fields_ = ...


class InputEvent(Union):
    """https://docs.microsoft.com/en-us/windows/console/input-record-str"""
    _fields_ = ...


class INPUT_RECORD(Structure):
    """https://docs.microsoft.com/en-us/windows/console/input-record-str"""
    _fields_ = ...


def set_console_mode(file: IO, mode: int) -> bool:
    """Set the console mode for a given file (stdout or stdin).

    Args:
        file: A file like object.
        mode: New mode.

    Returns:
        True on success, otherwise False.
    """
    ...

def get_console_mode(file: IO) -> int:
    """Get the console mode for a given file (stdout or stdin)

    Args:
        file: A file-like object.

    Returns:
        The current console mode.
    """
    ...

def enable_application_mode() -> Callable[[], None]:
    """Enable application mode.

    Returns:
        A callable that will restore terminal to previous state.
    """
    ...

def wait_for_handles(handles: List[HANDLE], timeout: int = ...) -> Optional[HANDLE]:
    """
    Waits for multiple handles. (Similar to 'select') Returns the handle which is ready.
    Returns `None` on timeout.
    http://msdn.microsoft.com/en-us/library/windows/desktop/ms687025(v=vs.85).aspx
    Note that handles should be a list of `HANDLE` objects, not integers. See
    this comment in the patch by @quark-zju for the reason why:
        ''' Make sure HANDLE on Windows has a correct size
        Previously, the type of various HANDLEs are native Python integer
        types. The ctypes library will treat them as 4-byte integer when used
        in function arguments. On 64-bit Windows, HANDLE is 8-byte and usually
        a small integer. Depending on whether the extra 4 bytes are zero-ed out
        or not, things can happen to work, or break. '''
    This function returns either `None` or one of the given `HANDLE` objects.
    (The return value can be tested with the `is` operator.)
    """
    ...

class EventMonitor(threading.Thread):
    """A thread to send key / window events to Textual loop."""
    def __init__(self, loop: AbstractEventLoop, app: App, exit_event: threading.Event, process_event: Callable[[Event], None]) -> None:
        ...
    
    def run(self) -> None:
        ...
    
    def on_size_change(self, width: int, height: int) -> None:
        """Called when terminal size changes."""
        ...
    


