"""
This type stub file was generated by pyright.
"""

from textual.layout import Layout

LAYOUT_MAP: dict[str, type[Layout]] = ...
class MissingLayout(Exception):
    ...


def get_layout(name: str) -> Layout:
    """Get a named layout object.

    Args:
        name: Name of the layout.

    Raises:
        MissingLayout: If the named layout doesn't exist.

    Returns:
        A layout object.
    """
    ...

