"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from textual.geometry import Size
from textual.layout import ArrangeResult, Layout
from textual.widget import Widget

if TYPE_CHECKING:
    ...
class HorizontalLayout(Layout):
    """Used to layout Widgets horizontally on screen, from left to right. Since Widgets naturally
    fill the space of their parent container, all widgets used in a horizontal layout should have a specified.
    """
    name = ...
    def arrange(self, parent: Widget, children: list[Widget], size: Size, greedy: bool = ...) -> ArrangeResult:
        ...
    


