"""
This type stub file was generated by pyright.
"""

import rich.repr
from typing import Generic, Iterable, Literal, NamedTuple, Sequence, TYPE_CHECKING, TypeVar
from rich.style import Style
from typing_extensions import TypeAlias
from textual.color import Color
from textual.css.scalar import Scalar, ScalarOffset, Unit
from textual.css.transition import Transition
from textual.geometry import Spacing, SpacingDimensions
from textual.canvas import CanvasLineType
from textual.layout import Layout
from textual.css.styles import StylesBase
from textual.css.types import AlignHorizontal, AlignVertical, DockEdge, EdgeType

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
BorderDefinition: TypeAlias = "Sequence[tuple[EdgeType, str | Color] | None] | tuple[EdgeType, str | Color] | Literal['none']"
PropertyGetType = TypeVar("PropertyGetType")
PropertySetType = TypeVar("PropertySetType")
EnumType = TypeVar("EnumType", covariant=True)
class GenericProperty(Generic[PropertyGetType, PropertySetType]):
    """Descriptor that abstracts away common machinery for other style descriptors.

    Args:
        default: The default value (or a factory thereof) of the property.
        layout: Whether to refresh the node layout on value change.
        refresh_children: Whether to refresh the node children on value change.
    """
    def __init__(self, default: PropertyGetType, layout: bool = ..., refresh_children: bool = ...) -> None:
        ...
    
    def validate_value(self, value: object) -> PropertyGetType:
        """Validate the setter value.

        Args:
            value: The value being set.

        Returns:
            The value to be set.
        """
        ...
    
    def __set_name__(self, owner: StylesBase, name: str) -> None:
        ...
    
    def __get__(self, obj: StylesBase, objtype: type[StylesBase] | None = ...) -> PropertyGetType:
        ...
    
    def __set__(self, obj: StylesBase, value: PropertySetType | None) -> None:
        ...
    


class IntegerProperty(GenericProperty[int, int]):
    def validate_value(self, value: object) -> int:
        ...
    


class BooleanProperty(GenericProperty[bool, bool]):
    """A property that requires a True or False value."""
    def validate_value(self, value: object) -> bool:
        ...
    


class ScalarProperty:
    """Descriptor for getting and setting scalar properties. Scalars are numeric values with a unit, e.g. "50vh"."""
    def __init__(self, units: set[Unit] | None = ..., percent_unit: Unit = ..., allow_auto: bool = ...) -> None:
        ...
    
    def __set_name__(self, owner: StylesBase, name: str) -> None:
        ...
    
    def __get__(self, obj: StylesBase, objtype: type[StylesBase] | None = ...) -> Scalar | None:
        """Get the scalar property.

        Args:
            obj: The ``Styles`` object.
            objtype: The ``Styles`` class.

        Returns:
            The Scalar object or ``None`` if it's not set.
        """
        ...
    
    def __set__(self, obj: StylesBase, value: float | int | Scalar | str | None) -> None:
        """Set the scalar property.

        Args:
            obj: The ``Styles`` object.
            value: The value to set the scalar property to.
                You can directly pass a float or int value, which will be interpreted with
                a default unit of Cells. You may also provide a string such as ``"50%"``,
                as you might do when writing CSS. If a string with no units is supplied,
                Cells will be used as the unit. Alternatively, you can directly supply
                a ``Scalar`` object.

        Raises:
            StyleValueError: If the value is of an invalid type, uses an invalid unit, or
                cannot be parsed for any other reason.
        """
        ...
    


class ScalarListProperty:
    """Descriptor for lists of scalars.

    Args:
        percent_unit: The dimension to which percentage scalars will be relative to.
        refresh_children: Whether to refresh the node children on value change.
    """
    def __init__(self, percent_unit: Unit, refresh_children: bool = ...) -> None:
        ...
    
    def __set_name__(self, owner: StylesBase, name: str) -> None:
        ...
    
    def __get__(self, obj: StylesBase, objtype: type[StylesBase] | None = ...) -> tuple[Scalar, ...] | None:
        ...
    
    def __set__(self, obj: StylesBase, value: str | Iterable[str | float] | None) -> None:
        ...
    


class BoxProperty:
    """Descriptor for getting and setting outlines and borders along a single edge.
    For example "border-right", "outline-bottom", etc.
    """
    def __init__(self, default_color: Color) -> None:
        ...
    
    def __set_name__(self, owner: StylesBase, name: str) -> None:
        ...
    
    def __get__(self, obj: StylesBase, objtype: type[StylesBase] | None = ...) -> tuple[EdgeType, Color]:
        """Get the box property.

        Args:
            obj: The ``Styles`` object.
            objtype: The ``Styles`` class.

        Returns:
            A ``tuple[EdgeType, Style]`` containing the string type of the box and
                its style. Example types are "round", "solid", and "dashed".
        """
        ...
    
    def __set__(self, obj: StylesBase, border: tuple[EdgeType, str | Color] | Literal["none"] | None):
        """Set the box property.

        Args:
            obj: The ``Styles`` object.
            value: A 2-tuple containing the type of box to use,
                e.g. "dashed", and the ``Style`` to be used. You can supply the ``Style`` directly, or pass a
                ``str`` (e.g. ``"blue on #f0f0f0"`` ) or ``Color`` instead.

        Raises:
            StyleValueError: If the string supplied for the color is not a valid color.
        """
        ...
    


@rich.repr.auto
class Edges(NamedTuple):
    """Stores edges for border / outline."""
    top: tuple[EdgeType, Color]
    right: tuple[EdgeType, Color]
    bottom: tuple[EdgeType, Color]
    left: tuple[EdgeType, Color]
    def __bool__(self) -> bool:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    
    @property
    def spacing(self) -> Spacing:
        """Get spacing created by borders.

        Returns:
            Spacing for top, right, bottom, and left.
        """
        ...
    


class BorderProperty:
    """Descriptor for getting and setting full borders and outlines.

    Args:
        layout: True if the layout should be refreshed after setting, False otherwise.
    """
    def __init__(self, layout: bool) -> None:
        ...
    
    def __set_name__(self, owner: StylesBase, name: str) -> None:
        ...
    
    def __get__(self, obj: StylesBase, objtype: type[StylesBase] | None = ...) -> Edges:
        """Get the border.

        Args:
            obj: The ``Styles`` object.
            objtype: The ``Styles`` class.

        Returns:
            An ``Edges`` object describing the type and style of each edge.
        """
        ...
    
    def __set__(self, obj: StylesBase, border: BorderDefinition | None) -> None:
        """Set the border.

        Args:
            obj: The ``Styles`` object.
            border:
                A ``tuple[EdgeType, str | Color | Style]`` representing the type of box to use and the ``Style`` to apply
                to the box.
                Alternatively, you can supply a sequence of these tuples and they will be applied per-edge.
                If the sequence is of length 1, all edges will be decorated according to the single element.
                If the sequence is length 2, the first ``tuple`` will be applied to the top and bottom edges.
                If the sequence is length 4, the tuples will be applied to the edges in the order: top, right, bottom, left.

        Raises:
            StyleValueError: When the supplied ``tuple`` is not of valid length (1, 2, or 4).
        """
        ...
    


class KeylineProperty:
    """Descriptor for getting and setting keyline information."""
    def __get__(self, obj: StylesBase, objtype: type[StylesBase] | None = ...) -> tuple[CanvasLineType, Color]:
        ...
    
    def __set__(self, obj: StylesBase, keyline: tuple[str, Color] | None):
        ...
    


class SpacingProperty:
    """Descriptor for getting and setting spacing properties (e.g. padding and margin)."""
    def __set_name__(self, owner: StylesBase, name: str) -> None:
        ...
    
    def __get__(self, obj: StylesBase, objtype: type[StylesBase] | None = ...) -> Spacing:
        """Get the Spacing.

        Args:
            obj: The ``Styles`` object.
            objtype: The ``Styles`` class.

        Returns:
            The Spacing. If unset, returns the null spacing ``(0, 0, 0, 0)``.
        """
        ...
    
    def __set__(self, obj: StylesBase, spacing: SpacingDimensions | None):
        """Set the Spacing.

        Args:
            obj: The ``Styles`` object.
            style: You can supply the ``Style`` directly, or a
                string (e.g. ``"blue on #f0f0f0"``).

        Raises:
            ValueError: When the value is malformed,
                e.g. a ``tuple`` with a length that is not 1, 2, or 4.
        """
        ...
    


class DockProperty:
    """Descriptor for getting and setting the dock property. The dock property
    allows you to specify which edge you want to fix a Widget to.
    """
    def __get__(self, obj: StylesBase, objtype: type[StylesBase] | None = ...) -> DockEdge:
        """Get the Dock property.

        Args:
            obj: The ``Styles`` object.
            objtype: The ``Styles`` class.

        Returns:
            The edge name as a string. Returns "none" if unset or if "none" has been explicitly set.
        """
        ...
    
    def __set__(self, obj: StylesBase, dock_name: str):
        """Set the Dock property.

        Args:
            obj: The ``Styles`` object.
            dock_name: The name of the dock to attach this widget to.
        """
        ...
    


class SplitProperty:
    """Descriptor for getting and setting the split property.
    The split property allows you to specify which edge you want to split.
    """
    def __get__(self, obj: StylesBase, objtype: type[StylesBase] | None = ...) -> DockEdge:
        """Get the Split property.

        Args:
            obj: The ``Styles`` object.
            objtype: The ``Styles`` class.

        Returns:
            The edge name as a string. Returns "none" if unset or if "none" has been explicitly set.
        """
        ...
    
    def __set__(self, obj: StylesBase, dock_name: str):
        """Set the Dock property.

        Args:
            obj: The ``Styles`` object.
            dock_name: The name of the dock to attach this widget to.
        """
        ...
    


class LayoutProperty:
    """Descriptor for getting and setting layout."""
    def __set_name__(self, owner: StylesBase, name: str) -> None:
        ...
    
    def __get__(self, obj: StylesBase, objtype: type[StylesBase] | None = ...) -> Layout | None:
        """
        Args:
            obj: The Styles object.
            objtype: The Styles class.

        Returns:
            The `Layout` object.
        """
        ...
    
    def __set__(self, obj: StylesBase, layout: str | Layout | None):
        """
        Args:
            obj: The Styles object.
            layout: The layout to use. You can supply the name of the layout
                or a `Layout` object.
        """
        ...
    


class OffsetProperty:
    """Descriptor for getting and setting the offset property.
    Offset consists of two values, x and y, that a widget's position
    will be adjusted by before it is rendered.
    """
    def __set_name__(self, owner: StylesBase, name: str) -> None:
        ...
    
    def __get__(self, obj: StylesBase, objtype: type[StylesBase] | None = ...) -> ScalarOffset:
        """Get the offset.

        Args:
            obj: The ``Styles`` object.
            objtype: The ``Styles`` class.

        Returns:
            The ``ScalarOffset`` indicating the adjustment that
                will be made to widget position prior to it being rendered.
        """
        ...
    
    def __set__(self, obj: StylesBase, offset: tuple[int | str, int | str] | ScalarOffset | None):
        """Set the offset.

        Args:
            obj: The ``Styles`` class.
            offset: A ScalarOffset object, or a 2-tuple of the form ``(x, y)`` indicating
                the x and y offsets. When the ``tuple`` form is used, x and y can be specified
                as either ``int`` or ``str``. The string format allows you to also specify
                any valid scalar unit e.g. ``("0.5vw", "0.5vh")``.

        Raises:
            ScalarParseError: If any of the string values supplied in the 2-tuple cannot
                be parsed into a Scalar. For example, if you specify a non-existent unit.
        """
        ...
    


class StringEnumProperty(Generic[EnumType]):
    """Descriptor for getting and setting string properties and ensuring that the set
    value belongs in the set of valid values.

    Args:
        valid_values: The set of valid values that the descriptor can take.
        default: The default value (or a factory thereof) of the property.
        layout: Whether to refresh the node layout on value change.
        refresh_children: Whether to refresh the node children on value change.
        display: Does this property change display?
    """
    def __init__(self, valid_values: set[str], default: EnumType, layout: bool = ..., refresh_children: bool = ..., refresh_parent: bool = ..., display: bool = ..., pointer: bool = ...) -> None:
        ...
    
    def __set_name__(self, owner: StylesBase, name: str) -> None:
        ...
    
    def __get__(self, obj: StylesBase, objtype: type[StylesBase] | None = ...) -> EnumType:
        """Get the string property, or the default value if it's not set.

        Args:
            obj: The `Styles` object.
            objtype: The `Styles` class.

        Returns:
            The string property value.
        """
        ...
    
    def __set__(self, obj: StylesBase, value: EnumType | None = ...):
        """Set the string property and ensure it is in the set of allowed values.

        Args:
            obj: The `Styles` object.
            value: The string value to set the property to.

        Raises:
            StyleValueError: If the value is not in the set of valid values.
        """
        ...
    


class OverflowProperty(StringEnumProperty):
    """Descriptor for overflow styles that forces widgets to refresh scrollbars."""
    ...


class NameProperty:
    """Descriptor for getting and setting name properties."""
    def __set_name__(self, owner: StylesBase, name: str) -> None:
        ...
    
    def __get__(self, obj: StylesBase, objtype: type[StylesBase] | None) -> str:
        """Get the name property.

        Args:
            obj: The ``Styles`` object.
            objtype: The ``Styles`` class.

        Returns:
            The name.
        """
        ...
    
    def __set__(self, obj: StylesBase, name: str | None):
        """Set the name property.

        Args:
            obj: The ``Styles`` object.
            name: The name to set the property to.

        Raises:
            StyleTypeError: If the value is not a ``str``.
        """
        ...
    


class NameListProperty:
    def __set_name__(self, owner: StylesBase, name: str) -> None:
        ...
    
    def __get__(self, obj: StylesBase, objtype: type[StylesBase] | None = ...) -> tuple[str, ...]:
        ...
    
    def __set__(self, obj: StylesBase, names: str | tuple[str] | None = ...):
        ...
    


class ColorProperty:
    """Descriptor for getting and setting color properties."""
    def __init__(self, default_color: Color | str) -> None:
        ...
    
    def __set_name__(self, owner: StylesBase, name: str) -> None:
        ...
    
    def __get__(self, obj: StylesBase, objtype: type[StylesBase] | None = ...) -> Color:
        """Get a ``Color``.

        Args:
            obj: The ``Styles`` object.
            objtype: The ``Styles`` class.

        Returns:
            The Color.
        """
        ...
    
    def __set__(self, obj: StylesBase, color: Color | str | None) -> None:
        """Set the Color.

        Args:
            obj: The ``Styles`` object.
            color: The color to set. Pass a ``Color`` instance directly,
                or pass a ``str`` which will be parsed into a color (e.g. ``"red""``, ``"rgb(20, 50, 80)"``,
                ``"#f4e32d"``).

        Raises:
            ColorParseError: When the color string is invalid.
        """
        ...
    


class ScrollbarColorProperty(ColorProperty):
    """A descriptor to set scrollbar color(s)."""
    def __set__(self, obj: StylesBase, color: Color | str | None) -> None:
        ...
    


class StyleFlagsProperty:
    """Descriptor for getting and set style flag properties (e.g. ``bold italic underline``)."""
    def __set_name__(self, owner: StylesBase, name: str) -> None:
        ...
    
    def __get__(self, obj: StylesBase, objtype: type[StylesBase] | None = ...) -> Style:
        """Get the ``Style``.

        Args:
            obj: The ``Styles`` object.
            objtype: The ``Styles`` class.

        Returns:
            The ``Style`` object.
        """
        ...
    
    def __set__(self, obj: StylesBase, style_flags: Style | str | None) -> None:
        """Set the style using a style flag string.

        Args:
            obj: The ``Styles`` object.
            style_flags: The style flags to set as a string. For example,
                ``"bold italic"``.

        Raises:
            StyleValueError: If the value is an invalid style flag.
        """
        ...
    


class TransitionsProperty:
    """Descriptor for getting transitions properties"""
    def __get__(self, obj: StylesBase, objtype: type[StylesBase] | None = ...) -> dict[str, Transition]:
        """Get a mapping of properties to the transitions applied to them.

        Args:
            obj: The ``Styles`` object.
            objtype: The ``Styles`` class.

        Returns:
            A ``dict`` mapping property names to the ``Transition`` applied to them.
                e.g. ``{"offset": Transition(...), ...}``. If no transitions have been set, an empty ``dict``
                is returned.
        """
        ...
    
    def __set__(self, obj: StylesBase, transitions: dict[str, Transition] | None) -> None:
        ...
    


class FractionalProperty:
    """Property that can be set either as a float (e.g. 0.1) or a
    string percentage (e.g. '10%'). Values will be clamped to the range (0, 1).
    """
    def __init__(self, default: float = ..., children: bool = ...) -> None:
        """
        Args:
            default: Default value if the rule wasn't explicitly set.
            children: If `True`, then updating this value will also refresh children.
                Otherwise only this widget will be refreshed.
        """
        ...
    
    def __set_name__(self, owner: StylesBase, name: str) -> None:
        ...
    
    def __get__(self, obj: StylesBase, type: type[StylesBase]) -> float:
        """Get the property value as a float between 0 and 1.

        Args:
            obj: The ``Styles`` object.
            objtype: The ``Styles`` class.

        Returns:
            The value of the property (in the range (0, 1)).
        """
        ...
    
    def __set__(self, obj: StylesBase, value: float | str | None) -> None:
        """Set the property value, clamping it between 0 and 1.

        Args:
            obj: The Styles object.
            value: The value to set as a float between 0 and 1, or
                as a percentage string such as '10%'.
        """
        ...
    


class AlignProperty:
    """Combines the horizontal and vertical alignment properties into a single property."""
    def __set_name__(self, owner: StylesBase, name: str) -> None:
        ...
    
    def __get__(self, obj: StylesBase, type: type[StylesBase]) -> tuple[AlignHorizontal, AlignVertical]:
        ...
    
    def __set__(self, obj: StylesBase, value: tuple[AlignHorizontal, AlignVertical]) -> None:
        ...
    


class HatchProperty:
    """Property to expose hatch style."""
    def __get__(self, obj: StylesBase, type: type[StylesBase]) -> tuple[str, Color] | Literal["none"]:
        ...
    
    def __set__(self, obj: StylesBase, value: tuple[str, Color | str] | Literal["none"] | None) -> None:
        ...
    


