"""
This type stub file was generated by pyright.
"""

from rich.console import Console, ConsoleOptions, RenderResult
from textual.css._help_renderables import HelpText
from textual.css.tokenizer import Token, TokenError

class DeclarationError(Exception):
    def __init__(self, name: str, token: Token, message: str | HelpText) -> None:
        ...
    


class StyleTypeError(TypeError):
    ...


class UnresolvedVariableError(TokenError):
    ...


class StyleValueError(ValueError):
    """Raised when the value of a style property is not valid

    Attributes:
        help_text: Optional HelpText to be rendered when this
            error is raised.
    """
    def __init__(self, *args: object, help_text: HelpText | None = ...) -> None:
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    


class StylesheetError(Exception):
    ...


