"""
This type stub file was generated by pyright.
"""

import rich.repr
from pathlib import PurePath
from typing import Final, Iterable, NamedTuple, Sequence
from rich.console import Console, ConsoleOptions, RenderResult, RenderableType
from textual.css.errors import StylesheetError
from textual.css.model import RuleSet
from textual.css.styles import RulesMap
from textual.css.types import CSSLocation
from textual.dom import DOMNode
from textual.style import Style

_DEFAULT_STYLES = ...
class StylesheetParseError(StylesheetError):
    """Raised when the stylesheet could not be parsed."""
    def __init__(self, errors: StylesheetErrors) -> None:
        ...
    
    def __rich__(self) -> RenderableType:
        ...
    


class StylesheetErrors:
    """A renderable for stylesheet errors."""
    def __init__(self, rules: list[RuleSet]) -> None:
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    


class CssSource(NamedTuple):
    """Contains the CSS content and whether or not the CSS comes from user defined stylesheets
    vs widget-level stylesheets.

    Args:
        content: The CSS as a string.
        is_defaults: True if the CSS is default (i.e. that defined at the widget level).
            False if it's user CSS (which will override the defaults).
        tie_breaker: Specificity tie breaker.
        scope: Scope of CSS.
    """
    content: str
    is_defaults: bool
    tie_breaker: int = ...
    scope: str = ...


@rich.repr.auto(angular=True)
class Stylesheet:
    """A Stylesheet generated from Textual CSS."""
    def __init__(self, *, variables: dict[str, str] | None = ...) -> None:
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    
    @property
    def rules(self) -> list[RuleSet]:
        """List of rule sets.

        Returns:
            List of rules sets for this stylesheet.
        """
        ...
    
    @property
    def rules_map(self) -> dict[str, list[RuleSet]]:
        """Structure that maps a selector on to a list of rules.

        Returns:
            Mapping of selector to rule sets.
        """
        ...
    
    @property
    def css(self) -> str:
        """The equivalent TCSS for this stylesheet.

        Note that this may not produce the same content as the file(s) used to generate the stylesheet.
        """
        ...
    
    def copy(self) -> Stylesheet:
        """Create a copy of this stylesheet.

        Returns:
            New stylesheet.
        """
        ...
    
    def set_variables(self, variables: dict[str, str]) -> None:
        """Set CSS variables.

        Args:
            variables: A mapping of name to variable.
        """
        ...
    
    def parse_style(self, style_text: str | Style) -> Style:
        """Parse a (visual) Style.

        Args:
            style_text: Visual style, such as "bold white 90% on $primary"

        Returns:
            New Style instance.
        """
        ...
    
    def read(self, filename: str | PurePath) -> None:
        """Read Textual CSS file.

        Args:
            filename: Filename of CSS.

        Raises:
            StylesheetError: If the CSS could not be read.
            StylesheetParseError: If the CSS is invalid.
        """
        ...
    
    def read_all(self, paths: Sequence[PurePath]) -> None:
        """Read multiple CSS files, in order.

        Args:
            paths: The paths of the CSS files to read, in order.

        Raises:
            StylesheetError: If the CSS could not be read.
            StylesheetParseError: If the CSS is invalid.
        """
        ...
    
    def has_source(self, path: str, class_var: str = ...) -> bool:
        """Check if the stylesheet has this CSS source already.

        Args:
            path: The file path of the source in question.
            class_var: The widget class variable we might be reading the CSS from.

        Returns:
            Whether the stylesheet is aware of this CSS source or not.
        """
        ...
    
    def add_source(self, css: str, read_from: CSSLocation | None = ..., is_default_css: bool = ..., tie_breaker: int = ..., scope: str = ...) -> None:
        """Parse CSS from a string.

        Args:
            css: String with CSS source.
            read_from: The original source location of the CSS.
            path: The path of the source if a file, or some other identifier.
            is_default_css: True if the CSS is defined in the Widget, False if the CSS is defined
                in a user stylesheet.
            tie_breaker: Integer representing the priority of this source.
            scope: CSS type name to limit scope or empty string for no scope.

        Raises:
            StylesheetError: If the CSS could not be read.
            StylesheetParseError: If the CSS is invalid.
        """
        ...
    
    def parse(self) -> None:
        """Parse the source in the stylesheet.

        Raises:
            StylesheetParseError: If there are any CSS related errors.
        """
        ...
    
    def reparse(self) -> None:
        """Re-parse source, applying new variables.

        Raises:
            StylesheetError: If the CSS could not be read.
            StylesheetParseError: If the CSS is invalid.
        """
        ...
    
    _EXCLUDE_PSEUDO_CLASSES_FROM_CACHE: Final[set[str]] = ...
    def apply(self, node: DOMNode, *, animate: bool = ..., cache: dict[tuple, RulesMap] | None = ...) -> None:
        """Apply the stylesheet to a DOM node.

        Args:
            node: The `DOMNode` to apply the stylesheet to.
                Applies the styles defined in this `Stylesheet` to the node.
                If the same rule is defined multiple times for the node (e.g. multiple
                classes modifying the same CSS property), then only the most specific
                rule will be applied.
            animate: Animate changed rules.
            cache: An optional cache when applying a group of nodes.
        """
        ...
    
    @classmethod
    def replace_rules(cls, node: DOMNode, rules: RulesMap, animate: bool = ...) -> None:
        """Replace style rules on a node, animating as required.

        Args:
            node: A DOM node.
            rules: Mapping of rules.
            animate: Enable animation.
        """
        ...
    
    def update(self, root: DOMNode, animate: bool = ...) -> None:
        """Update styles on node and its children.

        Args:
            root: Root note to update.
            animate: Enable CSS animation.
        """
        ...
    
    def update_nodes(self, nodes: Iterable[DOMNode], animate: bool = ...) -> None:
        """Update styles for nodes.

        Args:
            nodes: Nodes to update.
            animate: Enable CSS animation.
        """
        ...
    


