"""
This type stub file was generated by pyright.
"""

import rich.repr
from dataclasses import dataclass
from typing import Any, Iterable, Iterator, Literal, TYPE_CHECKING
from rich.style import Style
from typing_extensions import TypedDict
from textual._animator import Animatable, EasingFunction
from textual._types import AnimationLevel, CallbackType
from textual.color import Color
from textual.css._style_properties import StringEnumProperty
from textual.css.scalar import Scalar, ScalarOffset
from textual.css.scalar_animation import ScalarAnimation
from textual.css.transition import Transition
from textual.css.types import AlignHorizontal, AlignVertical, BoxSizing, CSSLocation, Constrain, Display, Expand, Overflow, Overlay, PointerShape, ScrollbarGutter, Specificity3, Specificity6, TextAlign, TextOverflow, TextWrap, Visibility
from textual.geometry import Spacing
from textual.dom import DOMNode
from textual.layout import Layout

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
class RulesMap(TypedDict, total=False):
    """A typed dict for CSS rules.

    Any key may be absent, indicating that rule has not been set.

    Does not define composite rules, that is a rule that is made of a combination of other rules.
    """
    display: Display
    visibility: Visibility
    layout: Layout
    auto_color: bool
    color: Color
    background: Color
    text_style: Style
    background_tint: Color
    opacity: float
    text_opacity: float
    padding: Spacing
    margin: Spacing
    offset: ScalarOffset
    position: str
    border_top: tuple[str, Color]
    border_right: tuple[str, Color]
    border_bottom: tuple[str, Color]
    border_left: tuple[str, Color]
    border_title_align: AlignHorizontal
    border_subtitle_align: AlignHorizontal
    outline_top: tuple[str, Color]
    outline_right: tuple[str, Color]
    outline_bottom: tuple[str, Color]
    outline_left: tuple[str, Color]
    keyline: tuple[str, Color]
    box_sizing: BoxSizing
    width: Scalar
    height: Scalar
    min_width: Scalar
    min_height: Scalar
    max_width: Scalar
    max_height: Scalar
    dock: str
    split: str
    overflow_x: Overflow
    overflow_y: Overflow
    layers: tuple[str, ...]
    layer: str
    transitions: dict[str, Transition]
    tint: Color
    scrollbar_color: Color
    scrollbar_color_hover: Color
    scrollbar_color_active: Color
    scrollbar_corner_color: Color
    scrollbar_background: Color
    scrollbar_background_hover: Color
    scrollbar_background_active: Color
    scrollbar_gutter: ScrollbarGutter
    scrollbar_size_vertical: int
    scrollbar_size_horizontal: int
    scrollbar_visibility: ScrollbarVisibility
    align_horizontal: AlignHorizontal
    align_vertical: AlignVertical
    content_align_horizontal: AlignHorizontal
    content_align_vertical: AlignVertical
    grid_size_rows: int
    grid_size_columns: int
    grid_gutter_horizontal: int
    grid_gutter_vertical: int
    grid_rows: tuple[Scalar, ...]
    grid_columns: tuple[Scalar, ...]
    row_span: int
    column_span: int
    text_align: TextAlign
    link_color: Color
    auto_link_color: bool
    link_background: Color
    link_style: Style
    link_color_hover: Color
    auto_link_color_hover: bool
    link_background_hover: Color
    link_style_hover: Style
    auto_border_title_color: bool
    border_title_color: Color
    border_title_background: Color
    border_title_style: Style
    auto_border_subtitle_color: bool
    border_subtitle_color: Color
    border_subtitle_background: Color
    border_subtitle_style: Style
    hatch: tuple[str, Color] | Literal["none"]
    overlay: Overlay
    constrain_x: Constrain
    constrain_y: Constrain
    text_wrap: TextWrap
    text_overflow: TextOverflow
    expand: Expand
    line_pad: int
    pointer: PointerShape
    ...


RULE_NAMES = ...
RULE_NAMES_SET = ...
_rule_getter = ...
class StylesBase:
    """A common base class for Styles and RenderStyles"""
    ANIMATABLE = ...
    display = ...
    visibility = ...
    layout = ...
    auto_color = ...
    color = ...
    background = ...
    background_tint = ...
    text_style = ...
    opacity = ...
    text_opacity = ...
    padding = ...
    margin = ...
    offset = ...
    position = ...
    border = ...
    border_top = ...
    border_right = ...
    border_bottom = ...
    border_left = ...
    border_title_align = ...
    border_subtitle_align = ...
    outline = ...
    outline_top = ...
    outline_right = ...
    outline_bottom = ...
    outline_left = ...
    keyline = ...
    box_sizing = ...
    width = ...
    height = ...
    min_width = ...
    min_height = ...
    max_width = ...
    max_height = ...
    dock = ...
    split = ...
    overflow_x = ...
    overflow_y = ...
    layer = ...
    layers = ...
    transitions = ...
    tint = ...
    scrollbar_color = ...
    scrollbar_color_hover = ...
    scrollbar_color_active = ...
    scrollbar_corner_color = ...
    scrollbar_background = ...
    scrollbar_background_hover = ...
    scrollbar_background_active = ...
    scrollbar_gutter = ...
    scrollbar_size_vertical = ...
    scrollbar_size_horizontal = ...
    scrollbar_visibility = ...
    align_horizontal = ...
    align_vertical = ...
    align = ...
    content_align_horizontal = ...
    content_align_vertical = ...
    content_align = ...
    grid_rows = ...
    grid_columns = ...
    grid_size_columns = ...
    grid_size_rows = ...
    grid_gutter_horizontal = ...
    grid_gutter_vertical = ...
    row_span = ...
    column_span = ...
    text_align: StringEnumProperty[TextAlign] = ...
    link_color = ...
    auto_link_color = ...
    link_background = ...
    link_style = ...
    link_color_hover = ...
    auto_link_color_hover = ...
    link_background_hover = ...
    link_style_hover = ...
    auto_border_title_color = ...
    border_title_color = ...
    border_title_background = ...
    border_title_style = ...
    auto_border_subtitle_color = ...
    border_subtitle_color = ...
    border_subtitle_background = ...
    border_subtitle_style = ...
    hatch = ...
    overlay = ...
    constrain_x: StringEnumProperty[Constrain] = ...
    constrain_y: StringEnumProperty[Constrain] = ...
    text_wrap: StringEnumProperty[TextWrap] = ...
    text_overflow: StringEnumProperty[TextOverflow] = ...
    expand: StringEnumProperty[Expand] = ...
    line_pad = ...
    pointer: StringEnumProperty[PointerShape] = ...
    @property
    def node(self) -> DOMNode | None:
        """The DOM node the styles will be applied to, or `None` if it is not set."""
        ...
    
    def __textual_animation__(self, attribute: str, start_value: object, value: object, start_time: float, duration: float | None, speed: float | None, easing: EasingFunction, on_complete: CallbackType | None = ..., level: AnimationLevel = ...) -> ScalarAnimation | None:
        ...
    
    def __eq__(self, styles: object) -> bool:
        """Check that Styles contains the same rules."""
        ...
    
    def __getitem__(self, key: str) -> object:
        ...
    
    def get(self, key: str, default: object | None = ...) -> object:
        ...
    
    def __len__(self) -> int:
        ...
    
    def __iter__(self) -> Iterator[str]:
        ...
    
    def __contains__(self, key: object) -> bool:
        ...
    
    def keys(self) -> Iterable[str]:
        ...
    
    def values(self) -> Iterable[object]:
        ...
    
    def items(self) -> Iterable[tuple[str, object]]:
        ...
    
    @property
    def gutter(self) -> Spacing:
        """Get space around widget.

        Returns:
            Space around widget content.
        """
        ...
    
    @property
    def auto_dimensions(self) -> bool:
        """Check if width or height are set to 'auto'."""
        ...
    
    @property
    def is_relative_width(self, _relative_units=...) -> bool:
        """Does the node have a relative width?"""
        ...
    
    @property
    def is_relative_height(self, _relative_units=...) -> bool:
        """Does the node have a relative width?"""
        ...
    
    @property
    def is_auto_width(self, _auto=...) -> bool:
        """Does the node have automatic width?"""
        ...
    
    @property
    def is_auto_height(self, _auto=...) -> bool:
        """Does the node have automatic height?"""
        ...
    
    @property
    def is_dynamic_height(self, _dynamic_units=...) -> bool:
        """Does the node have a dynamic (not fixed) height?"""
        ...
    
    @property
    def is_docked(self) -> bool:
        """Is the node docked?"""
        ...
    
    @property
    def is_split(self) -> bool:
        """Is the node split?"""
        ...
    
    def has_rule(self, rule_name: str) -> bool:
        """Check if a rule is set on this Styles object.

        Args:
            rule_name: Rule name.

        Returns:
            ``True`` if the rules is present, otherwise ``False``.
        """
        ...
    
    def clear_rule(self, rule_name: str) -> bool:
        """Removes the rule from the Styles object, as if it had never been set.

        Args:
            rule_name: Rule name.

        Returns:
            ``True`` if a rule was cleared, or ``False`` if the rule is already not set.
        """
        ...
    
    def get_rules(self) -> RulesMap:
        """Get the rules in a mapping.

        Returns:
            A TypedDict of the rules.
        """
        ...
    
    def set_rule(self, rule_name: str, value: object | None) -> bool:
        """Set a rule.

        Args:
            rule_name: Rule name.
            value: New rule value.

        Returns:
            ``True`` if the rule changed, otherwise ``False``.
        """
        ...
    
    def get_rule(self, rule_name: str, default: object = ...) -> object:
        """Get an individual rule.

        Args:
            rule_name: Name of rule.
            default: Default if rule does not exists.

        Returns:
            Rule value or default.
        """
        ...
    
    def refresh(self, *, layout: bool = ..., children: bool = ..., parent: bool = ..., repaint: bool = ...) -> None:
        """Mark the styles as requiring a refresh.

        Args:
            layout: Also require a layout.
            children: Also refresh children.
            parent: Also refresh the parent.
            repaint: Repaint the widgets.
        """
        ...
    
    def reset(self) -> None:
        """Reset the rules to initial state."""
        ...
    
    def merge(self, other: StylesBase) -> None:
        """Merge values from another Styles.

        Args:
            other: A Styles object.
        """
        ...
    
    def merge_rules(self, rules: RulesMap) -> None:
        """Merge rules into Styles.

        Args:
            rules: A mapping of rules.
        """
        ...
    
    def get_render_rules(self) -> RulesMap:
        """Get rules map with defaults."""
        ...
    
    @classmethod
    def is_animatable(cls, rule: str) -> bool:
        """Check if a given rule may be animated.

        Args:
            rule: Name of the rule.

        Returns:
            ``True`` if the rule may be animated, otherwise ``False``.
        """
        ...
    
    @classmethod
    def parse(cls, css: str, read_from: CSSLocation, *, node: DOMNode | None = ...) -> Styles:
        """Parse CSS and return a Styles object.

        Args:
            css: Textual CSS.
            read_from: Location where the CSS was read from.
            node: Node to associate with the Styles.

        Returns:
            A Styles instance containing result of parsing CSS.
        """
        ...
    
    @property
    def partial_rich_style(self) -> Style:
        """Get the style properties associated with this node only (not including parents in the DOM).

        Returns:
            Rich Style object.
        """
        ...
    


@rich.repr.auto
@dataclass
class Styles(StylesBase):
    node: DOMNode | None = ...
    _rules: RulesMap = ...
    _updates: int = ...
    important: set[str] = ...
    def __post_init__(self) -> None:
        ...
    
    def copy(self) -> Styles:
        """Get a copy of this Styles object."""
        ...
    
    def clear_rule(self, rule_name: str) -> bool:
        """Removes the rule from the Styles object, as if it had never been set.

        Args:
            rule_name: Rule name.

        Returns:
            ``True`` if a rule was cleared, or ``False`` if it was already not set.
        """
        ...
    
    def get_rules(self) -> RulesMap:
        ...
    
    def set_rule(self, rule: str, value: object | None) -> bool:
        """Set a rule.

        Args:
            rule: Rule name.
            value: New rule value.

        Returns:
            ``True`` if the rule changed, otherwise ``False``.
        """
        ...
    
    def refresh(self, *, layout: bool = ..., children: bool = ..., parent: bool = ..., repaint=...) -> None:
        ...
    
    def reset(self) -> None:
        """Reset the rules to initial state."""
        ...
    
    def merge(self, other: StylesBase) -> None:
        """Merge values from another Styles.

        Args:
            other: A Styles object.
        """
        ...
    
    def merge_rules(self, rules: RulesMap) -> None:
        ...
    
    def extract_rules(self, specificity: Specificity3, is_default_rules: bool = ..., tie_breaker: int = ...) -> list[tuple[str, Specificity6, Any]]:
        """Extract rules from Styles object, and apply !important css specificity as
        well as higher specificity of user CSS vs widget CSS.

        Args:
            specificity: A node specificity.
            is_default_rules: True if the rules we're extracting are
                default (i.e. in Widget.DEFAULT_CSS) rules. False if they're from user defined CSS.

        Returns:
            A list containing a tuple of <RULE NAME>, <SPECIFICITY> <RULE VALUE>.
        """
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    
    @property
    def css_lines(self) -> list[str]:
        ...
    
    @property
    def css(self) -> str:
        ...
    


@rich.repr.auto
class RenderStyles(StylesBase):
    """Presents a combined view of two Styles object: a base Styles and inline Styles."""
    def __init__(self, node: DOMNode, base: Styles, inline_styles: Styles) -> None:
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    
    @property
    def node(self) -> DOMNode | None:
        """The DOM node the styles will be applied to, or `None` if it is not set."""
        ...
    
    @property
    def base(self) -> Styles:
        """Quick access to base (css) style."""
        ...
    
    @property
    def inline(self) -> Styles:
        """Quick access to the inline styles."""
        ...
    
    @property
    def rich_style(self) -> Style:
        """Get a Rich style for this Styles object."""
        ...
    
    @property
    def gutter(self) -> Spacing:
        """Get space around widget (padding + border)

        Returns:
            Space around widget content.
        """
        ...
    
    def animate(self, attribute: str, value: str | float | Animatable, *, final_value: object = ..., duration: float | None = ..., speed: float | None = ..., delay: float = ..., easing: EasingFunction | str = ..., on_complete: CallbackType | None = ..., level: AnimationLevel = ...) -> None:
        """Animate an attribute.

        Args:
            attribute: Name of the attribute to animate.
            value: The value to animate to.
            final_value: The final value of the animation. Defaults to `value` if not set.
            duration: The duration (in seconds) of the animation.
            speed: The speed of the animation.
            delay: A delay (in seconds) before the animation starts.
            easing: An easing method.
            on_complete: A callable to invoke when the animation is finished.
            level: Minimum level required for the animation to take place (inclusive).
        """
        ...
    
    def __rich_repr__(self) -> rich.repr.Result:
        ...
    
    def refresh(self, *, layout: bool = ..., children: bool = ..., parent: bool = ..., repaint: bool = ...) -> None:
        ...
    
    def merge(self, other: StylesBase) -> None:
        """Merge values from another Styles.

        Args:
            other: A Styles object.
        """
        ...
    
    def merge_rules(self, rules: RulesMap) -> None:
        ...
    
    def reset(self) -> None:
        """Reset the rules to initial state."""
        ...
    
    def has_rule(self, rule_name: str) -> bool:
        """Check if a rule has been set."""
        ...
    
    def has_any_rules(self, *rule_names: str) -> bool:
        """Check if any of the supplied rules have been set.

        Args:
            rule_names: Number of rules.

        Returns:
            `True` if any of the supplied rules have been set, `False` if none have.
        """
        ...
    
    def set_rule(self, rule_name: str, value: object | None) -> bool:
        ...
    
    def get_rule(self, rule_name: str, default: object = ...) -> object:
        ...
    
    def clear_rule(self, rule_name: str) -> bool:
        """Clear a rule (from inline)."""
        ...
    
    def get_rules(self) -> RulesMap:
        """Get rules as a dictionary"""
        ...
    
    @property
    def css(self) -> str:
        """Get the CSS for the combined styles."""
        ...
    


