"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from typing import Callable, Iterable, Optional, TYPE_CHECKING, Union
from .text import Text, TextType
from .console import Console, ConsoleRenderable
from .table import Table
from rich.console import Console

if TYPE_CHECKING:
    ...
FormatTimeCallable = Callable[[datetime], Text]
class LogRender:
    def __init__(self, show_time: bool = ..., show_level: bool = ..., show_path: bool = ..., time_format: Union[str, FormatTimeCallable] = ..., omit_repeated_times: bool = ..., level_width: Optional[int] = ...) -> None:
        ...
    
    def __call__(self, console: Console, renderables: Iterable[ConsoleRenderable], log_time: Optional[datetime] = ..., time_format: Optional[Union[str, FormatTimeCallable]] = ..., level: TextType = ..., path: Optional[str] = ..., line_no: Optional[int] = ..., link_path: Optional[str] = ...) -> Table:
        ...
    


if __name__ == "__main__":
    c = ...
