"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from .color import Color
from .console import Console, ConsoleOptions, RenderResult
from .jupyter import JupyterMixin
from .measure import Measurement

BEGIN_BLOCK_ELEMENTS = ...
END_BLOCK_ELEMENTS = ...
FULL_BLOCK = ...
class Bar(JupyterMixin):
    """Renders a solid block bar.

    Args:
        size (float): Value for the end of the bar.
        begin (float): Begin point (between 0 and size, inclusive).
        end (float): End point (between 0 and size, inclusive).
        width (int, optional): Width of the bar, or ``None`` for maximum width. Defaults to None.
        color (Union[Color, str], optional): Color of the bar. Defaults to "default".
        bgcolor (Union[Color, str], optional): Color of bar background. Defaults to "default".
    """
    def __init__(self, size: float, begin: float, end: float, *, width: Optional[int] = ..., color: Union[Color, str] = ..., bgcolor: Union[Color, str] = ...) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    
    def __rich_measure__(self, console: Console, options: ConsoleOptions) -> Measurement:
        ...
    


