"""
This type stub file was generated by pyright.
"""

from enum import IntEnum
from functools import lru_cache
from typing import NamedTuple, Optional, TYPE_CHECKING, Tuple
from .color_triplet import ColorTriplet
from .repr import Result, rich_repr
from .terminal_theme import TerminalTheme
from .text import Text

if TYPE_CHECKING:
    ...
WINDOWS = ...
class ColorSystem(IntEnum):
    """One of the 3 color system supported by terminals."""
    STANDARD = ...
    EIGHT_BIT = ...
    TRUECOLOR = ...
    WINDOWS = ...
    def __repr__(self) -> str:
        ...
    
    def __str__(self) -> str:
        ...
    


class ColorType(IntEnum):
    """Type of color stored in Color class."""
    DEFAULT = ...
    STANDARD = ...
    EIGHT_BIT = ...
    TRUECOLOR = ...
    WINDOWS = ...
    def __repr__(self) -> str:
        ...
    


ANSI_COLOR_NAMES = ...
class ColorParseError(Exception):
    """The color could not be parsed."""
    ...


RE_COLOR = ...
@rich_repr
class Color(NamedTuple):
    """Terminal color definition."""
    name: str
    type: ColorType
    number: Optional[int] = ...
    triplet: Optional[ColorTriplet] = ...
    def __rich__(self) -> Text:
        """Displays the actual color if Rich printed."""
        ...
    
    def __rich_repr__(self) -> Result:
        ...
    
    @property
    def system(self) -> ColorSystem:
        """Get the native color system for this color."""
        ...
    
    @property
    def is_system_defined(self) -> bool:
        """Check if the color is ultimately defined by the system."""
        ...
    
    @property
    def is_default(self) -> bool:
        """Check if the color is a default color."""
        ...
    
    def get_truecolor(self, theme: Optional[TerminalTheme] = ..., foreground: bool = ...) -> ColorTriplet:
        """Get an equivalent color triplet for this color.

        Args:
            theme (TerminalTheme, optional): Optional terminal theme, or None to use default. Defaults to None.
            foreground (bool, optional): True for a foreground color, or False for background. Defaults to True.

        Returns:
            ColorTriplet: A color triplet containing RGB components.
        """
        ...
    
    @classmethod
    def from_ansi(cls, number: int) -> Color:
        """Create a Color number from it's 8-bit ansi number.

        Args:
            number (int): A number between 0-255 inclusive.

        Returns:
            Color: A new Color instance.
        """
        ...
    
    @classmethod
    def from_triplet(cls, triplet: ColorTriplet) -> Color:
        """Create a truecolor RGB color from a triplet of values.

        Args:
            triplet (ColorTriplet): A color triplet containing red, green and blue components.

        Returns:
            Color: A new color object.
        """
        ...
    
    @classmethod
    def from_rgb(cls, red: float, green: float, blue: float) -> Color:
        """Create a truecolor from three color components in the range(0->255).

        Args:
            red (float): Red component in range 0-255.
            green (float): Green component in range 0-255.
            blue (float): Blue component in range 0-255.

        Returns:
            Color: A new color object.
        """
        ...
    
    @classmethod
    def default(cls) -> Color:
        """Get a Color instance representing the default color.

        Returns:
            Color: Default color.
        """
        ...
    
    @classmethod
    @lru_cache(maxsize=1024)
    def parse(cls, color: str) -> Color:
        """Parse a color definition."""
        ...
    
    @lru_cache(maxsize=1024)
    def get_ansi_codes(self, foreground: bool = ...) -> Tuple[str, ...]:
        """Get the ANSI escape codes for this color."""
        ...
    
    @lru_cache(maxsize=1024)
    def downgrade(self, system: ColorSystem) -> Color:
        """Downgrade a color system to a system with fewer colors."""
        ...
    


def parse_rgb_hex(hex_color: str) -> ColorTriplet:
    """Parse six hex characters in to RGB triplet."""
    ...

def blend_rgb(color1: ColorTriplet, color2: ColorTriplet, cross_fade: float = ...) -> ColorTriplet:
    """Blend one RGB color in to another."""
    ...

if __name__ == "__main__":
    console = ...
    table = ...
    colors = ...
