"""
This type stub file was generated by pyright.
"""

from typing import Literal, Optional, TYPE_CHECKING, Union
from .jupyter import JupyterMixin
from .style import Style
from .console import Console, ConsoleOptions, RenderResult
from rich.console import Console

if TYPE_CHECKING:
    ...
EmojiVariant = Literal["emoji", "text"]
class NoEmoji(Exception):
    """No emoji by that name."""
    ...


class Emoji(JupyterMixin):
    __slots__ = ...
    VARIANTS = ...
    def __init__(self, name: str, style: Union[str, Style] = ..., variant: Optional[EmojiVariant] = ...) -> None:
        """A single emoji character.

        Args:
            name (str): Name of emoji.
            style (Union[str, Style], optional): Optional style. Defaults to None.

        Raises:
            NoEmoji: If the emoji doesn't exist.
        """
        ...
    
    @classmethod
    def replace(cls, text: str) -> str:
        """Replace emoji markup with corresponding unicode characters.

        Args:
            text (str): A string with emojis codes, e.g. "Hello :smiley:!"

        Returns:
            str: A string with emoji codes replaces with actual emoji.
        """
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    


if __name__ == "__main__":
    console = ...
    columns = ...
