"""
This type stub file was generated by pyright.
"""

import io
from typing import Any, IO, TYPE_CHECKING
from .console import Console

if TYPE_CHECKING:
    ...
class FileProxy(io.TextIOBase):
    """Wraps a file (e.g. sys.stdout) and redirects writes to a console."""
    def __init__(self, console: Console, file: IO[str]) -> None:
        ...
    
    @property
    def rich_proxied_file(self) -> IO[str]:
        """Get proxied file."""
        ...
    
    def __getattr__(self, name: str) -> Any:
        ...
    
    def write(self, text: str) -> int:
        ...
    
    def flush(self) -> None:
        ...
    
    def fileno(self) -> int:
        ...
    


