"""
This type stub file was generated by pyright.
"""

from typing import Any, Iterable, TYPE_CHECKING
from .segment import Segment

if TYPE_CHECKING:
    ...
if TYPE_CHECKING:
    ...
JUPYTER_HTML_FORMAT = ...
class JupyterRenderable:
    """A shim to write html to Jupyter notebook."""
    def __init__(self, html: str, text: str) -> None:
        ...
    


class JupyterMixin:
    """Add to an Rich renderable to make it render in Jupyter notebook."""
    __slots__ = ...


def display(segments: Iterable[Segment], text: str) -> None:
    """Render segments to Jupyter."""
    ...

def print(*args: Any, **kwargs: Any) -> None:
    """Proxy for Console print."""
    ...

