"""
This type stub file was generated by pyright.
"""

from typing import ClassVar
from markdown_it.token import Token
from .console import Console, ConsoleOptions, JustifyMethod, RenderResult
from .jupyter import JupyterMixin
from .style import Style
from .text import TextType
from rich.console import Console

class MarkdownElement:
    new_line: ClassVar[bool] = ...
    @classmethod
    def create(cls, markdown: Markdown, token: Token) -> MarkdownElement:
        """Factory to create markdown element,

        Args:
            markdown (Markdown): The parent Markdown object.
            token (Token): A node from markdown-it.

        Returns:
            MarkdownElement: A new markdown element
        """
        ...
    
    def on_enter(self, context: MarkdownContext) -> None:
        """Called when the node is entered.

        Args:
            context (MarkdownContext): The markdown context.
        """
        ...
    
    def on_text(self, context: MarkdownContext, text: TextType) -> None:
        """Called when text is parsed.

        Args:
            context (MarkdownContext): The markdown context.
        """
        ...
    
    def on_leave(self, context: MarkdownContext) -> None:
        """Called when the parser leaves the element.

        Args:
            context (MarkdownContext): [description]
        """
        ...
    
    def on_child_close(self, context: MarkdownContext, child: MarkdownElement) -> bool:
        """Called when a child element is closed.

        This method allows a parent element to take over rendering of its children.

        Args:
            context (MarkdownContext): The markdown context.
            child (MarkdownElement): The child markdown element.

        Returns:
            bool: Return True to render the element, or False to not render the element.
        """
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    


class UnknownElement(MarkdownElement):
    """An unknown element.

    Hopefully there will be no unknown elements, and we will have a MarkdownElement for
    everything in the document.

    """
    ...


class TextElement(MarkdownElement):
    """Base class for elements that render text."""
    style_name = ...
    def on_enter(self, context: MarkdownContext) -> None:
        ...
    
    def on_text(self, context: MarkdownContext, text: TextType) -> None:
        ...
    
    def on_leave(self, context: MarkdownContext) -> None:
        ...
    


class Paragraph(TextElement):
    """A Paragraph."""
    style_name = ...
    justify: JustifyMethod
    @classmethod
    def create(cls, markdown: Markdown, token: Token) -> Paragraph:
        ...
    
    def __init__(self, justify: JustifyMethod) -> None:
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    


class Heading(TextElement):
    """A heading."""
    @classmethod
    def create(cls, markdown: Markdown, token: Token) -> Heading:
        ...
    
    def on_enter(self, context: MarkdownContext) -> None:
        ...
    
    def __init__(self, tag: str) -> None:
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    


class CodeBlock(TextElement):
    """A code block with syntax highlighting."""
    style_name = ...
    @classmethod
    def create(cls, markdown: Markdown, token: Token) -> CodeBlock:
        ...
    
    def __init__(self, lexer_name: str, theme: str) -> None:
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    


class BlockQuote(TextElement):
    """A block quote."""
    style_name = ...
    def __init__(self) -> None:
        ...
    
    def on_child_close(self, context: MarkdownContext, child: MarkdownElement) -> bool:
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    


class HorizontalRule(MarkdownElement):
    """A horizontal rule to divide sections."""
    new_line = ...
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    


class TableElement(MarkdownElement):
    """MarkdownElement corresponding to `table_open`."""
    def __init__(self) -> None:
        ...
    
    def on_child_close(self, context: MarkdownContext, child: MarkdownElement) -> bool:
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    


class TableHeaderElement(MarkdownElement):
    """MarkdownElement corresponding to `thead_open` and `thead_close`."""
    def __init__(self) -> None:
        ...
    
    def on_child_close(self, context: MarkdownContext, child: MarkdownElement) -> bool:
        ...
    


class TableBodyElement(MarkdownElement):
    """MarkdownElement corresponding to `tbody_open` and `tbody_close`."""
    def __init__(self) -> None:
        ...
    
    def on_child_close(self, context: MarkdownContext, child: MarkdownElement) -> bool:
        ...
    


class TableRowElement(MarkdownElement):
    """MarkdownElement corresponding to `tr_open` and `tr_close`."""
    def __init__(self) -> None:
        ...
    
    def on_child_close(self, context: MarkdownContext, child: MarkdownElement) -> bool:
        ...
    


class TableDataElement(MarkdownElement):
    """MarkdownElement corresponding to `td_open` and `td_close`
    and `th_open` and `th_close`."""
    @classmethod
    def create(cls, markdown: Markdown, token: Token) -> MarkdownElement:
        ...
    
    def __init__(self, justify: JustifyMethod) -> None:
        ...
    
    def on_text(self, context: MarkdownContext, text: TextType) -> None:
        ...
    


class ListElement(MarkdownElement):
    """A list element."""
    @classmethod
    def create(cls, markdown: Markdown, token: Token) -> ListElement:
        ...
    
    def __init__(self, list_type: str, list_start: int | None) -> None:
        ...
    
    def on_child_close(self, context: MarkdownContext, child: MarkdownElement) -> bool:
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    


class ListItem(TextElement):
    """An item in a list."""
    style_name = ...
    def __init__(self) -> None:
        ...
    
    def on_child_close(self, context: MarkdownContext, child: MarkdownElement) -> bool:
        ...
    
    def render_bullet(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    
    def render_number(self, console: Console, options: ConsoleOptions, number: int, last_number: int) -> RenderResult:
        ...
    


class Link(TextElement):
    @classmethod
    def create(cls, markdown: Markdown, token: Token) -> MarkdownElement:
        ...
    
    def __init__(self, text: str, href: str) -> None:
        ...
    


class ImageItem(TextElement):
    """Renders a placeholder for an image."""
    new_line = ...
    @classmethod
    def create(cls, markdown: Markdown, token: Token) -> MarkdownElement:
        """Factory to create markdown element,

        Args:
            markdown (Markdown): The parent Markdown object.
            token (Any): A token from markdown-it.

        Returns:
            MarkdownElement: A new markdown element
        """
        ...
    
    def __init__(self, destination: str, hyperlinks: bool) -> None:
        ...
    
    def on_enter(self, context: MarkdownContext) -> None:
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    


class MarkdownContext:
    """Manages the console render state."""
    def __init__(self, console: Console, options: ConsoleOptions, style: Style, inline_code_lexer: str | None = ..., inline_code_theme: str = ...) -> None:
        ...
    
    @property
    def current_style(self) -> Style:
        """Current style which is the product of all styles on the stack."""
        ...
    
    def on_text(self, text: str, node_type: str) -> None:
        """Called when the parser visits text."""
        ...
    
    def enter_style(self, style_name: str | Style) -> Style:
        """Enter a style context."""
        ...
    
    def leave_style(self) -> Style:
        """Leave a style context."""
        ...
    


class Markdown(JupyterMixin):
    """A Markdown renderable.

    Args:
        markup (str): A string containing markdown.
        code_theme (str, optional): Pygments theme for code blocks. Defaults to "monokai". See https://pygments.org/styles/ for code themes.
        justify (JustifyMethod, optional): Justify value for paragraphs. Defaults to None.
        style (Union[str, Style], optional): Optional style to apply to markdown.
        hyperlinks (bool, optional): Enable hyperlinks. Defaults to ``True``.
        inline_code_lexer: (str, optional): Lexer to use if inline code highlighting is
            enabled. Defaults to None.
        inline_code_theme: (Optional[str], optional): Pygments theme for inline code
            highlighting, or None for no highlighting. Defaults to None.
    """
    elements: ClassVar[dict[str, type[MarkdownElement]]] = ...
    inlines = ...
    def __init__(self, markup: str, code_theme: str = ..., justify: JustifyMethod | None = ..., style: str | Style = ..., hyperlinks: bool = ..., inline_code_lexer: str | None = ..., inline_code_theme: str | None = ...) -> None:
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        """Render markdown to the console."""
        ...
    


if __name__ == "__main__":
    parser = ...
    args = ...
    markdown = ...
