"""
This type stub file was generated by pyright.
"""

from typing import Callable, Match, NamedTuple, Optional, Union
from .emoji import EmojiVariant
from .style import Style
from .text import Text

RE_TAGS = ...
RE_HANDLER = ...
class Tag(NamedTuple):
    """A tag in console markup."""
    name: str
    parameters: Optional[str]
    def __str__(self) -> str:
        ...
    
    @property
    def markup(self) -> str:
        """Get the string representation of this tag."""
        ...
    


_ReStringMatch = Match[str]
_ReSubCallable = Callable[[_ReStringMatch], str]
_EscapeSubMethod = Callable[[_ReSubCallable, str], str]
def escape(markup: str, _escape: _EscapeSubMethod = ...) -> str:
    """Escapes text so that it won't be interpreted as markup.

    Args:
        markup (str): Content to be inserted in to markup.

    Returns:
        str: Markup with square brackets escaped.
    """
    ...

def render(markup: str, style: Union[str, Style] = ..., emoji: bool = ..., emoji_variant: Optional[EmojiVariant] = ...) -> Text:
    """Render console markup in to a Text instance.

    Args:
        markup (str): A string containing console markup.
        style: (Union[str, Style]): The style to use.
        emoji (bool, optional): Also render emoji code. Defaults to True.
        emoji_variant (str, optional): Optional emoji variant, either "text" or "emoji". Defaults to None.


    Raises:
        MarkupError: If there is a syntax error in the markup.

    Returns:
        Text: A test instance.
    """
    ...

if __name__ == "__main__":
    MARKUP = ...
    grid = ...
