"""
This type stub file was generated by pyright.
"""

from functools import lru_cache
from typing import Iterable, Sequence, TYPE_CHECKING, Tuple
from .color_triplet import ColorTriplet
from rich.table import Table
from rich.console import Console, ConsoleOptions
from rich.segment import Segment

if TYPE_CHECKING:
    ...
class Palette:
    """A palette of available colors."""
    def __init__(self, colors: Sequence[Tuple[int, int, int]]) -> None:
        ...
    
    def __getitem__(self, number: int) -> ColorTriplet:
        ...
    
    def __rich__(self) -> Table:
        ...
    
    @lru_cache(maxsize=1024)
    def match(self, color: Tuple[int, int, int]) -> int:
        """Find a color from a palette that most closely matches a given color.

        Args:
            color (Tuple[int, int, int]): RGB components in range 0 > 255.

        Returns:
            int: Index of closes matching color.
        """
        ...
    


if __name__ == "__main__":
    class ColorBox:
        def __rich_console__(self, console: Console, options: ConsoleOptions) -> Iterable[Segment]:
            ...
        
    
    
    console = ...
