"""
This type stub file was generated by pyright.
"""

from typing import Optional, TYPE_CHECKING
from .align import AlignMethod
from .box import Box
from .jupyter import JupyterMixin
from .measure import Measurement
from .padding import PaddingDimensions
from .style import StyleType
from .text import TextType
from .console import Console, ConsoleOptions, RenderResult, RenderableType

if TYPE_CHECKING:
    ...
class Panel(JupyterMixin):
    """A console renderable that draws a border around its contents.

    Example:
        >>> console.print(Panel("Hello, World!"))

    Args:
        renderable (RenderableType): A console renderable object.
        box (Box): A Box instance that defines the look of the border (see :ref:`appendix_box`. Defaults to box.ROUNDED.
        title (Optional[TextType], optional): Optional title displayed in panel header. Defaults to None.
        title_align (AlignMethod, optional): Alignment of title. Defaults to "center".
        subtitle (Optional[TextType], optional): Optional subtitle displayed in panel footer. Defaults to None.
        subtitle_align (AlignMethod, optional): Alignment of subtitle. Defaults to "center".
        safe_box (bool, optional): Disable box characters that don't display on windows legacy terminal with *raster* fonts. Defaults to True.
        expand (bool, optional): If True the panel will stretch to fill the console width, otherwise it will be sized to fit the contents. Defaults to True.
        style (str, optional): The style of the panel (border and contents). Defaults to "none".
        border_style (str, optional): The style of the border. Defaults to "none".
        width (Optional[int], optional): Optional width of panel. Defaults to None to auto-detect.
        height (Optional[int], optional): Optional height of panel. Defaults to None to auto-detect.
        padding (Optional[PaddingDimensions]): Optional padding around renderable. Defaults to 0.
        highlight (bool, optional): Enable automatic highlighting of panel title (if str). Defaults to False.
    """
    def __init__(self, renderable: RenderableType, box: Box = ..., *, title: Optional[TextType] = ..., title_align: AlignMethod = ..., subtitle: Optional[TextType] = ..., subtitle_align: AlignMethod = ..., safe_box: Optional[bool] = ..., expand: bool = ..., style: StyleType = ..., border_style: StyleType = ..., width: Optional[int] = ..., height: Optional[int] = ..., padding: PaddingDimensions = ..., highlight: bool = ...) -> None:
        ...
    
    @classmethod
    def fit(cls, renderable: RenderableType, box: Box = ..., *, title: Optional[TextType] = ..., title_align: AlignMethod = ..., subtitle: Optional[TextType] = ..., subtitle_align: AlignMethod = ..., safe_box: Optional[bool] = ..., style: StyleType = ..., border_style: StyleType = ..., width: Optional[int] = ..., height: Optional[int] = ..., padding: PaddingDimensions = ..., highlight: bool = ...) -> Panel:
        """An alternative constructor that sets expand=False."""
        ...
    
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        ...
    
    def __rich_measure__(self, console: Console, options: ConsoleOptions) -> Measurement:
        ...
    


if __name__ == "__main__":
    c = ...
    p = ...
