"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from typing import Any, Optional, TYPE_CHECKING
from .text import TextType
from .console import ConsoleRenderable

if TYPE_CHECKING:
    ...
def render_scope(scope: Mapping[str, Any], *, title: Optional[TextType] = ..., sort_keys: bool = ..., indent_guides: bool = ..., max_length: Optional[int] = ..., max_string: Optional[int] = ...) -> ConsoleRenderable:
    """Render python variables in a given scope.

    Args:
        scope (Mapping): A mapping containing variable names and values.
        title (str, optional): Optional title. Defaults to None.
        sort_keys (bool, optional): Enable sorting of items. Defaults to True.
        indent_guides (bool, optional): Enable indentation guides. Defaults to False.
        max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation.
            Defaults to None.
        max_string (int, optional): Maximum length of string before truncating, or None to disable. Defaults to None.

    Returns:
        ConsoleRenderable: A renderable object.
    """
    ...

if __name__ == "__main__":
    def test(foo: float, bar: float) -> None:
        ...
    
